### ISSUE TITLE
Jenkins SSL: CERTIFICATE_VERIFY_FAILED for api.components.espressif.com (IDFGH-8648)

### ISSUE THREAD

**Issue by ddomnik** [espressif/esp-idf#10094]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

01d014c42def8d0c19e1ce55c07de6761e092ffa

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### What is the expected behavior?

Resolving components managed by idf component manager.

### What is the actual behavior?

SSL: CERTIFICATE_VERIFY_FAILED error for api.components.espressif.com

### Steps to reproduce.

1. Set up jenkins environment
2. Add managed components
3. build

### Build or installation Logs.

```plain
Detecting the Python interpreter
Checking "python3" ...
Python 3.10.6
"python3" has been detected
Checking Python compatibility
Checking other ESP-IDF version.
Adding ESP-IDF tools to PATH...
Using Python interpreter in /home/XXX/.espressif/python_env/idf5.0_py3.10_env/bin/python
Checking if Python packages are up to date...
Downloading https://dl.espressif.com/dl/esp-idf/espidf.constraints.v5.0.txt
Destination: /home/XXX/.espressif/espidf.constraints.v5.0.txt.tmp

0%
100%
Done
Python requirements are satisfied.
Constraint file: /home/XXX/.espressif/espidf.constraints.v5.0.txt
Requirement files:
 - /home/XXX/esp/esp-idf/tools/requirements/requirements.core.txt
Python being checked: /home/XXX/.espressif/python_env/idf5.0_py3.10_env/bin/python
Added the following directories to PATH:

	[...]
	
Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build

-- Found Git: /usr/bin/git (found version "2.17.1") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/XXX/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc
-- Check for working C compiler: /home/XXX/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc
-- Check for working C compiler: /home/XXX/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/XXX/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++
-- Check for working CXX compiler: /home/XXX/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
Processing 2 dependencies:
[1/2] espressif/libsodium (1.0.20)
CMake Error at /home/XXX/esp/esp-idf/tools/cmake/build.cmake:476 (message):
  Traceback (most recent call last):

    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
      httplib_response = self._make_request(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
      self._validate_conn(conn)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
      conn.connect()
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
      self.sock = ssl_wrap_socket(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
      ssl_sock = _ssl_wrap_socket_impl(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
      return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
      return self.sslsocket_class._create(
    File "/usr/lib/python3.10/ssl.py", line 1071, in _create
      self.do_handshake()
    File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
      self._sslobj.do_handshake()

  ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
  verify failed: self signed certificate in certificate chain (_ssl.c:997)

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
      resp = conn.urlopen(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
      return self.urlopen(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
      return self.urlopen(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
      return self.urlopen(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
      retries = retries.increment(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

  urllib3.exceptions.MaxRetryError:
  HTTPSConnectionPool(host='api.components.espressif.com', port=443): Max
  retries exceeded with url: /components/espressif/libsodium/ (Caused by
  SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
  certificate verify failed: self signed certificate in certificate chain
  (_ssl.c:997)')))

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 158, in _base_request
      response = self.session.request(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
      resp = self.send(prep, **send_kwargs)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
      r = adapter.send(request, **kwargs)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
      raise SSLError(e, request=request)

  requests.exceptions.SSLError:
  HTTPSConnectionPool(host='api.components.espressif.com', port=443): Max
  retries exceeded with url: /components/espressif/libsodium/ (Caused by
  SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
  certificate verify failed: self signed certificate in certificate chain
  (_ssl.c:997)')))

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/__main__.py", line 3, in <module>
      main()
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 126, in main
      args.func(args)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 39, in prepare_dep_dirs
      ComponentManager(args.project_dir).prepare_dep_dirs(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/core.py", line 404, in prepare_dep_dirs
      downloaded_component_paths = download_project_dependencies(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/dependencies.py", line 128, in download_project_dependencies
      download_paths = fetcher.download()
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/sources/fetcher.py", line 51, in download
      return self.source.download(self.component, self.managed_path)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/sources/web_service.py", line 129, in download
      component_manifest = self.api_client.component(component.name, component.version)
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 225, in component
      response = self._base_request(
    File "/home/XXX/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 178, in _base_request
      raise APIClientError('HTTP request error')

  idf_component_tools.api_client_errors.APIClientError: HTTP request error
```
```


### More Information.

_No response_

**Comment by kumekay** [comment]
Hi @ddomnik 
it looks like the root certificates of your distro are outdated. What distribution are you using in your CI?

Please try upgrading `ca-certificates` package. 

The source of the problem is explained here https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by ddomnik** [comment]
> Hi @ddomnik it looks like the root certificates of your distro are outdated. What distribution are you using in your CI?
> 
> Please try upgrading `ca-certificates` package.
> 
> The source of the problem is explained here https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Thank you!
Was just looking into the root certificate / x3 expiration as cause before I noticed that you already replied. But now I am sure.

**Comment by ddomnik** [comment]
For others that face the same problem:

In fact, it was not the ubuntu distribution that caused that error. It was python itself. Idf.py uses urllib3 which uses certifi's certificate bundle. 
You can tell python to use the systems certificates by adding this env 
`export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

@kumekay you may want to consider using the systems' bundle as well, or tell idf.py to update pythons bundle once in a while.

**Comment by kumekay** [comment]
@ddomnik Thank you for the comment, 
could you please help me to reproduce your issue? What version of what distro are you using (or what docker image?) And how did you install esp-idf there?

**Comment by ddomnik** [comment]
@kumekay I am sorry, I don't have free access to our build server. The distro was an Ubuntu (16.04. or 18.04) VM. While setting IDF up we had some problems installing virtualenv beacause ensurepip was not available, but got it running somehow. So maybe python 3.4 was installed.
