### ISSUE TITLE
nvs_partition_gen.py error with provided example

### ISSUE THREAD

**Issue by javoerro** [espressif/esp-idf#10891]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.3 and 5.0

### Operating System used.

Windows

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

i tryed the provided example in the [repository](https://github.com/espressif/esp-idf/tree/master/components/nvs_flash/nvs_partition_generator)

`python nvs_partition_gen.py generate sample_singlepage_blob.csv sample.bin 0x3000`

expecting the generation of a binary called sample.bin with the corresponding content

### What is the actual behavior?

but the result was and an empty sample.bin file

### Steps to reproduce.

1. open cmd
2. cd [IDF-DIR]\components\nvs_flash\nvs_partition_generator
3. python nvs_partition_gen.py generate sample_singlepage_blob.csv sample.bin 0x3000
...

### Build or installation Logs.

```plain
Creating NVS binary with version: V2 - Multipage Blob Support Enabled
Traceback (most recent call last):
  File "nvs_partition_gen.py", line 1025, in <module>
    main()
  File "nvs_partition_gen.py", line 1021, in main
    args.func(args)
  File "nvs_partition_gen.py", line 908, in generate
    write_entry(nvs_obj, row['key'], row['type'], row['encoding'], row['value'])
  File "nvs_partition_gen.py", line 636, in write_entry
    nvs_instance.write_entry(key, value, encoding)
  File "nvs_partition_gen.py", line 555, in write_entry
    self.cur_page.write_varlen_data(key, value, encoding, self.namespace_idx,self)
  File "nvs_partition_gen.py", line 397, in write_varlen_data
    datalen,total_entry_count, encoding, nvs_obj)
  File "nvs_partition_gen.py", line 290, in write_varlen_binary_data
    nvs_obj.create_new_page()
  File "nvs_partition_gen.py", line 499, in create_new_page
    curr_page_state = struct.unpack('<I', self.cur_page.page_buf[0:4])[0]
struct.error: unpack requires a string argument of length 4
```

**Comment by javoerro** [comment]
the problem was that i was using python 2 to run the script. running with python 3 worked ok.
