### ISSUE TITLE
Crashed by ble (IDFGH-9658)

### ISSUE THREAD

**Issue by sxsx2yzyz** [espressif/esp-idf#11000]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2-384-g3047225a9f

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32c3   2MB flash

### Power Supply used.

External 3.3V

### What is the expected behavior?

The following crash occurred when I used the Android mobile phone for ble. The following is the output of my call to 
`espcoredump.py info_corefile -t raw -c ./error ./build/led_ble_wifi.elf`
```
bash-3.2$ espcoredump.py info_corefile -t raw -c ./error ./build/led_ble_wifi.elf
espcoredump.py v0.4-dev
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3fcbc0f4, name: 'hciT', GDB name: 'process 1070317812'

================== CURRENT THREAD REGISTERS ===================
ra             0x4201cd50       0x4201cd50 <reassemble_and_dispatch+294>
sp             0x3fcbc020       0x3fcbc020
gp             0x3fc93200       0x3fc93200 <chb+84>
tp             0x3fc96964       0x3fc96964 <xIsrStack+1780>
t0             0x4005890e       1074104590
t1             0x4201cc2a       1107414058
t2             0x0      0
fp             0x3fcdc194       0x3fcdc194
s1             0x0      0
a0             0x0      0
a1             0x3fcdc19d       1070449053
a2             0xb      11
a3             0x1      1
a4             0x1      1
a5             0x1100   4352
a6             0x1      1
a7             0x0      0
s2             0x1      1
s3             0xb      11
s4             0x3fc9d5bc       1070192060
s5             0xfb1c   64284
s6             0xfb00   64256
s7             0x3fcdc19c       1070449052
s8             0xfff    4095
s9             0x3fcdc19f       1070449055
s10            0x0      0
s11            0x0      0
t3             0x0      0
t4             0x0      0
t5             0x0      0
t6             0x0      0
pc             0x4201cd5e       0x4201cd5e <reassemble_and_dispatch+308>

==================== CURRENT THREAD STACK =====================
#0  0x4201cd5e in reassemble_and_dispatch (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/packet_fragmenter.c:174
#1  reassemble_and_dispatch (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/packet_fragmenter.c:136
#2  0x42045626 in hci_hal_h4_hdl_rx_packet (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/hci_hal_h4.c:466
#3  hci_upstream_data_handler (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/hci_hal_h4.c:226
#4  0x4203fac2 in osi_thread_run (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/thread.c:165
#5  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

======================== THREADS INFO =========================
  Id   Target Id          Frame 
* 1    process 1070317812 0x4201cd5e in reassemble_and_dispatch (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/packet_fragmenter.c:174
  2    process 1070392852 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  3    process 1070219456 prvIdleTask (pvParameters=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/tasks.c:3940
  4    process 1070254260 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  5    process 1070332420 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  6    process 1070247948 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  7    process 1070396576 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  8    process 1070331532 0x4038d624 in vPortExitCritical () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:343
  9    process 1070343352 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  10   process 1070404012 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  11   process 1070389016 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  12   process 1070354464 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  13   process 1070212568 0x4038d624 in vPortExitCritical () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:343
  14   process 1070325588 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  15   process 1070313056 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
  16   process 1070300488 0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363

==================== THREAD 1 (TCB: 0x3fcbc0f4, name: 'hciT') =====================
#0  0x4201cd5e in reassemble_and_dispatch (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/packet_fragmenter.c:174
#1  reassemble_and_dispatch (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/packet_fragmenter.c:136
#2  0x42045626 in hci_hal_h4_hdl_rx_packet (packet=0x3fcdc194) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/hci_hal_h4.c:466
#3  hci_upstream_data_handler (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/host/bluedroid/hci/hci_hal_h4.c:226
#4  0x4203fac2 in osi_thread_run (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/thread.c:165
#5  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 2 (TCB: 0x3fcce614, name: 'adcTask') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4200cb7c in adcTask () at /Users/yangzhen/esp/esp-app/FINDPOP/main/_adc.c:162
#3  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 3 (TCB: 0x3fca40c0, name: 'IDLE') =====================
#0  prvIdleTask (pvParameters=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/tasks.c:3940
#1  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 4 (TCB: 0x3fcac8b4, name: 'sendTask') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b504 in xQueueSemaphoreTake (xQueue=0x3fcac4c4, xTicksToWait=<optimized out>, xTicksToWait@entry=25) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1696
#3  0x420640da in rmt_wait_tx_done (channel=channel@entry=RMT_CHANNEL_0, wait_time=wait_time@entry=25) at /Users/yangzhen/esp/esp-idf-v4.4/components/driver/rmt.c:1183
#4  0x4200ca7a in ws2811Send (data=data@entry=0x3fca943c <error: Cannot access memory at address 0x3fca943c>) at /Users/yangzhen/esp/esp-app/FINDPOP/main/ws2811rmt.c:142
#5  0x420072a6 in sendTask () at /Users/yangzhen/esp/esp-app/FINDPOP/main/led.c:752
#6  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 5 (TCB: 0x3fcbfa04, name: 'tiT') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fcbf97c, pvBuffer=pvBuffer@entry=0x3fcc138c, xTicksToWait=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x4207fb38 in sys_arch_mbox_fetch (mbox=mbox@entry=0x3fc9d718 <tcpip_mbox>, msg=msg@entry=0x3fcc138c, timeout=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/lwip/port/esp32/freertos/sys_arch.c:330
#4  0x42072814 in tcpip_timeouts_mbox_fetch (mbox=<optimized out>, msg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/lwip/lwip/src/api/tcpip.c:110
#5  tcpip_thread (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/lwip/lwip/src/api/tcpip.c:148
#6  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 6 (TCB: 0x3fcab00c, name: 'computeTask') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fca9a08, pvBuffer=pvBuffer@entry=0x0, xTicksToWait=<optimized out>, xTicksToWait@entry=1000) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x42007482 in computeTask () at /Users/yangzhen/esp/esp-app/FINDPOP/main/led.c:682
#4  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 7 (TCB: 0x3fccf4a0, name: 'receiver_rf433') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fcce76c, pvBuffer=pvBuffer@entry=0x3fccf45c, xTicksToWait=<optimized out>, xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x42010ef6 in receiver_rf433 (pvParameter=<optimized out>) at /Users/yangzhen/esp/esp-app/FINDPOP/components/esp32-rf-receiver/esp32_rf_receiver.c:201
#4  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 8 (TCB: 0x3fcbf68c, name: 'dTc') =====================
#0  0x4038d624 in vPortExitCritical () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:343
#1  0x4038cee4 in ulTaskGenericNotifyTake (uxIndexToWait=uxIndexToWait@entry=0, xClearCountOnExit=xClearCountOnExit@entry=1, xTicksToWait=xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/tasks.c:5401
#2  0x420098be in delayToConnect (param=<optimized out>) at /Users/yangzhen/esp/esp-app/FINDPOP/main/_wifi.c:186
#3  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 9 (TCB: 0x3fcc24b8, name: 'sys_evt') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fcc1404, pvBuffer=pvBuffer@entry=0x3fcc2430, xTicksToWait=<optimized out>, xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x420e01ae in esp_event_loop_run (event_loop=event_loop@entry=0x3fcc13e8, ticks_to_run=ticks_to_run@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_event/esp_event.c:632
#4  0x420e0216 in esp_event_loop_run_task (args=0x3fcc13e8) at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_event/esp_event.c:115
#5  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 10 (TCB: 0x3fcd11ac, name: 'espnow_main') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fcd1304, pvBuffer=pvBuffer@entry=0x3fcd10f0, xTicksToWait=<optimized out>, xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x420110e6 in espnow_main_task (arg=<optimized out>) at /Users/yangzhen/esp/esp-app/FINDPOP/components/espnow/src/espnow.c:792
#4  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 11 (TCB: 0x3fccd718, name: 'httpd') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b504 in xQueueSemaphoreTake (xQueue=0x3fccd8e4, xTicksToWait=<optimized out>, xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1696
#3  0x4207f9ce in sys_arch_sem_wait (sem=<optimized out>, timeout=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/lwip/port/esp32/freertos/sys_arch.c:184
#4  0x420723b4 in lwip_select (maxfdp1=maxfdp1@entry=56, readset=readset@entry=0x3fccd698, writeset=writeset@entry=0x0, exceptset=exceptset@entry=0x0, timeout=timeout@entry=0x0) at /Users/yangzhen/esp/esp-idf-v4.4/components/lwip/lwip/src/api/sockets.c:2153
#5  0x42002554 in esp_vfs_select (nfds=56, readfds=readfds@entry=0x3fccd698, writefds=writefds@entry=0x0, errorfds=errorfds@entry=0x0, timeout=timeout@entry=0x0) at /Users/yangzhen/esp/esp-idf-v4.4/components/vfs/vfs.c:1019
#6  0x420831ec in httpd_server (hd=0x3fccbb24) at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_http_server/src/httpd_main.c:205
#7  httpd_thread (arg=0x3fccbb24) at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_http_server/src/httpd_main.c:250
#8  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 12 (TCB: 0x3fcc5020, name: 'wifi') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b358 in xQueueReceive (xQueue=0x3fcc2f2c, pvBuffer=0x3fcc4fb8, xTicksToWait=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1487
#3  0x400407be in ?? ()

==================== THREAD 13 (TCB: 0x3fca25d8, name: 'esp_timer') =====================
#0  0x4038d624 in vPortExitCritical () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:343
#1  0x4038cee4 in ulTaskGenericNotifyTake (uxIndexToWait=uxIndexToWait@entry=0, xClearCountOnExit=xClearCountOnExit@entry=1, xTicksToWait=xTicksToWait@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/tasks.c:5401
#2  0x42005b7e in timer_task (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_timer/src/esp_timer.c:384
#3  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 14 (TCB: 0x3fcbdf54, name: 'BTU_TASK') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b504 in xQueueSemaphoreTake (xQueue=0x3fcbcc48, xTicksToWait=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1696
#3  0x42040116 in osi_sem_take (sem=sem@entry=0x3fcbc8a4, timeout=timeout@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/semaphore.c:60
#4  0x4203fa88 in osi_thread_run (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/thread.c:156
#5  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 15 (TCB: 0x3fcbae60, name: 'BTC_TASK') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b504 in xQueueSemaphoreTake (xQueue=0x3fcb9f54, xTicksToWait=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1696
#3  0x42040116 in osi_sem_take (sem=sem@entry=0x3fcb9b20, timeout=timeout@entry=4294967295) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/semaphore.c:60
#4  0x4203fa88 in osi_thread_run (arg=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/bt/common/osi/thread.c:156
#5  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171
Backtrace stopped: frame did not save the PC

==================== THREAD 16 (TCB: 0x3fcb7d48, name: 'btController') =====================
#0  0x4038d4b8 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:363
#1  0x4038d672 in vPortYield () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:371
#2  0x4038b504 in xQueueSemaphoreTake (xQueue=0x3fcaee64, xTicksToWait=<optimized out>) at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/queue.c:1696
#3  0x40382418 in btdm_controller_task () at /Users/yangzhen/esp/esp-idf-v4.4/components/esp_timer/src/esp_timer.c:263
#4  0x4038d454 in prvTaskExitError () at /Users/yangzhen/esp/esp-idf-v4.4/components/freertos/port/riscv/port.c:171


======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.force_fast 0x50000010 0x0 RW  
.rtc.data 0x50000010 0x10 RW A
.rtc_noinit 0x50000020 0x0 RW  
.rtc.force_slow 0x50000020 0x0 RW  
.iram0.text 0x40380000 0x12850 R XA
.dram0.data 0x3fc92a00 0x363c RW A
.noinit 0x3fc9603c 0x0 RW  
.flash.text 0x42000020 0xe11da R XA
.flash.appdesc 0x3c0f0020 0x100 R  A
.flash.rodata 0x3c0f0120 0x25780 RW A
.eh_frame 0x3c1158a0 0x710 R  A
.iram0.data 0x40392a00 0x0 RW  
.iram0.bss 0x40392a00 0x0 RW  
.coredump.tasks.data 0x3fcbc0f4 0x154 RW 
.coredump.tasks.data 0x3fcbbf80 0x160 RW 
.coredump.tasks.data 0x3fcce614 0x154 RW 
.coredump.tasks.data 0x3fcce510 0xf0 RW 
.coredump.tasks.data 0x3fca40c0 0x154 RW 
.coredump.tasks.data 0x3fca3ff0 0xc0 RW 
.coredump.tasks.data 0x3fcac8b4 0x154 RW 
.coredump.tasks.data 0x3fcabc20 0x140 RW 
.coredump.tasks.data 0x3fcbfa04 0x154 RW 
.coredump.tasks.data 0x3fcc1290 0x150 RW 
.coredump.tasks.data 0x3fcab00c 0x154 RW 
.coredump.tasks.data 0x3fcaae80 0x180 RW 
.coredump.tasks.data 0x3fccf4a0 0x154 RW 
.coredump.tasks.data 0x3fccf380 0x110 RW 
.coredump.tasks.data 0x3fcbf68c 0x154 RW 
.coredump.tasks.data 0x3fcc0470 0x160 RW 
.coredump.tasks.data 0x3fcc24b8 0x154 RW 
.coredump.tasks.data 0x3fcc2360 0x150 RW 
.coredump.tasks.data 0x3fcd11ac 0x154 RW 
.coredump.tasks.data 0x3fcd1000 0x1a0 RW 
.coredump.tasks.data 0x3fccd718 0x154 RW 
.coredump.tasks.data 0x3fccd4b0 0x260 RW 
.coredump.tasks.data 0x3fcc5020 0x154 RW 
.coredump.tasks.data 0x3fcc4ee0 0x130 RW 
.coredump.tasks.data 0x3fca25d8 0x154 RW 
.coredump.tasks.data 0x3fca24f0 0xe0 RW 
.coredump.tasks.data 0x3fcbdf54 0x154 RW 
.coredump.tasks.data 0x3fcbde10 0x130 RW 
.coredump.tasks.data 0x3fcbae60 0x154 RW 
.coredump.tasks.data 0x3fcbad20 0x130 RW 
.coredump.tasks.data 0x3fcb7d48 0x154 RW 
.coredump.tasks.data 0x3fcb7c10 0x130 RW 

===================== ESP32 CORE DUMP END =====================
===============================================================
```

### What is the actual behavior?

crash and reset

### Steps to reproduce.

We have 20 chips with the same program. When I use the BLE of Android to connect and control at the same time, two or three devices have the above errors.
Please tell me what happened and what caused the error. Thank you.

**Comment by Weijian-Espressif** [comment]
@sxsx2yzyz Please check if the system memory is used up
