### ISSUE TITLE
But I switch to v4.4, it will error when I run `. export.sh` or `./install.sh` (IDFGH-9723)

### ISSUE THREAD

**Issue by waruqi** [espressif/esp-idf#11059]
But I switch to v4.4, it will error when I run `. export.sh` or `./install.sh`

```
$ ./install.sh 
Detecting the Python interpreter
Checking "python" ...
Checking "python3" ...
Python 3.10.8
"python3" has been detected
Installing ESP-IDF tools
Traceback (most recent call last):
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1828, in <module>
    main(sys.argv[1:])
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1824, in main
    action_func(args)
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1420, in action_install
    targets = clean_targets(args.targets)
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1083, in clean_targets
    export_targets_to_idf_env_json(targets_from_tools_json)
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1051, in export_targets_to_idf_env_json
    targets = list(set(targets + get_user_defined_targets()))
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1097, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
ruki-2:esp-idf ruki$ . export.sh 
Detecting the Python interpreter
Checking "python" ...
Checking "python3" ...
Python 3.10.8
"python3" has been detected
Adding ESP-IDF tools to PATH...
Traceback (most recent call last):
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1828, in <module>
    main(sys.argv[1:])
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1824, in main
    action_func(args)
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1175, in action_export
    tools_info = filter_tools_info(tools_info)
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1117, in filter_tools_info
    targets = get_user_defined_targets()
  File "/Users/ruki/projects/personal/esp-idf/tools/idf_tools.py", line 1097, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
```

_Originally posted by @waruqi in https://github.com/espressif/esp-idf/issues/11058#issuecomment-1484555470_

**Comment by dobairoland** [comment]
Please search for the issue in the issue tracker. You will find the workaround and also links that this has been fixed in all release branches (you need to use the latest bugfix releases).
