### ISSUE TITLE
[v5.1][idf.py] coredump-info, partition[0], IndexError: list index out of range (IDFGH-10305)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#11564]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

release/v5.1

### Operating System used.

MacOS

### How did you build your project?

Command line with idf.py

### Development Kit.

ESP32-S3

### What is the expected behavior?

I should get the coredump. 

Note: my partition table is not at the default location `CONFIG_PARTITION_TABLE_OFFSET=0xf000`, but `idf.py` does not have an argument to set its location?

### What is the actual behavior?

Exception thrown.

### Steps to reproduce.

Run `idf.py coredump-info`

It may be required to have your partition table at a non-default location.

### Debug Logs.

```
charlesweinberger@Chips-Macbook-Pro-2 jamcorder_app % idf.py coredump-info
Executing action: coredump-info
Serial port /dev/cu.usbserial-10
Connecting....
Detecting chip type... ESP32-S3
Failed to load core dump: parttool script execution failed with error 1, failed command was: '/Volumes/User/MBP-Google-Drive/jamcorder/firmware/.espressif/python_env/idf5.1_py3.11_env/bin/python /Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py --port /dev/cu.usbserial-10 read_partition --partition-type data --partition-subtype coredump --output /var/folders/kc/8ph49dv51xg62gfz9z77dp9w0000gn/T/tmptn9m651q'

┌────── Additional information about the error: 
│   
│   esptool.py v4.5.1
│   Serial port /dev/cu.usbserial-10
│   Connecting....
│   Detecting chip type... ESP32-S3
│   Chip is ESP32-S3 (revision v0.1)
│   Features: WiFi, BLE
│   Crystal is 40MHz
│   MAC: 7c:df:a1:f3:bc:a4
│   Uploading stub...
│   Running stub...
│   Stub running...
│   3072 (100 %)
│   3072 (100 %)
│   Read 3072 bytes at 0x00008000 in 0.3 seconds (86.3 kbit/s)...
│   Hard resetting via RTS pin...
│   Running /Volumes/User/MBP-Google-Drive/jamcorder/firmware/.espressif/python_env/idf5.1_py3.11_env/bin/python /Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/esptool_py/esptool/esptool.py --port /dev/cu.usbserial-10 read_flash 32768 3072 /var/folders/kc/8ph49dv51xg62gfz9z77dp9w0000gn/T/tmpx4745eh4...
│   Traceback (most recent call last):
│     File "/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py", line 358, in <module>
│       main()
│     File "/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py", line 351, in main
│       op(**common_args)
│     File "/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py", line 182, in _read_partition
│       target.read_partition(partition_id, output)
│     File "/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py", line 158, in read_partition
│       partition = self.get_partition_info(partition_id)
│                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│     File "/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/partition_table/parttool.py", line 140, in get_partition_info
│       partition = partition[0]
│                   ~~~~~~~~~^^^
│   IndexError: list index out of range

│   
└────── end of additional information about the error.
```

**Comment by chipweinberger** [comment]
> Read 3072 bytes at 0x00008000 in 0.3 seconds (86.4 kbit/s)

It is reading the wrong location for that parition table...
