### ISSUE TITLE
assert failed: ieee802154_isr esp_ieee802154_dev.c:463 (IDFGH-10813)

### ISSUE THREAD

**Issue by nomis** [espressif/esp-idf#12024]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C6-DevKitC-1

### Power Supply used.

USB

### What is the expected behavior?

The ieee802154 driver does not crash receiving RX events while idle on startup, before Zigbee is started.

### What is the actual behavior?

The ieee802154 driver crashes with an assertion failure if it receives RX events while idle on startup, before Zigbee is started.

### Steps to reproduce.

1. Run one of the Zigbee on/off server examples and pair the device
2. Check you can switch an endpoint using the coordinator (to ensure communication currently works)
3. Restart the ESP32-C6
4. Immediately switch an endpoint multiple times to transmit messages while the ESP is starting up
5. Assertion failure in `ieee802154_isr`

### Debug Logs.

```plain
assert failed: ieee802154_isr esp_ieee802154_dev.c:463 (s_ieee802154_state == IEEE802154_STATE_RX || s_ieee802154_state == IEEE802154_STATE_RX_ACK || s_ieee802154_state == IEEE802154_STATE_TX || s_ie
Stack dump detected
Core  0 register dump:
MEPC    : 0x4080062e  RA      : 0x40807936  SP      : 0x40811750  GP      : 0x4080e6b0  
0x4080062e: panic_abort at /home/simon/src/esp-idf/components/esp_system/panic.c:452

0x40807936: __ubsan_include at /home/simon/src/esp-idf/components/esp_system/ubsan.c:313

TP      : 0x4080c088  T0      : 0x54535f34  T1      : 0x65656569  T2      : 0x35313230  
0x4080c088: ieee802154_isr at /home/simon/src/esp-idf/components/ieee802154/driver/esp_ieee802154_dev.c:481 (discriminator 2)

S0/FP   : 0x00000000  S1      : 0x0000008f  A0      : 0x408117a4  A1      : 0x42066b47  
A2      : 0x73207c7c  A3      : 0x00000065  A4      : 0x00000001  A5      : 0x40817000  
A6      : 0x00000020  A7      : 0x31323038  S2      : 0x00000007  S3      : 0x40811937  
S4      : 0x42066ab8  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000001  
S8      : 0x00000000  S9      : 0x00000400  S10     : 0x0000000a  S11     : 0x00000000  
T3      : 0x5f73207c  T4      : 0x7c204b43  T5      : 0x415f5852  T6      : 0x5f455441  
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
0x40800001: _vector_table at ??:?

MHARTID : 0x00000000  


Backtrace:


panic_abort (details=details@entry=0x408117a4 <xIsrStack+1812> "assert failed: ieee802154_isr esp_ieee802154_dev.c:463 (s_ieee802154_state == IEEE802154_STATE_RX || s_ieee802154_state == IEEE802154_STATE_RX_ACK || s_ieee802154_state == IEEE802154_STATE_TX || s_ie") at /home/simon/src/esp-idf/components/esp_system/panic.c:452
452	    *((volatile int *) 0) = 0; // NOLINT(clang-analyzer-core.NullDereference) should be an invalid operation on targets
#0  panic_abort (details=details@entry=0x408117a4 <xIsrStack+1812> "assert failed: ieee802154_isr esp_ieee802154_dev.c:463 (s_ieee802154_state == IEEE802154_STATE_RX || s_ieee802154_state == IEEE802154_STATE_RX_ACK || s_ieee802154_state == IEEE802154_STATE_TX || s_ie") at /home/simon/src/esp-idf/components/esp_system/panic.c:452
#1  0x40807936 in esp_system_abort (details=details@entry=0x408117a4 <xIsrStack+1812> "assert failed: ieee802154_isr esp_ieee802154_dev.c:463 (s_ieee802154_state == IEEE802154_STATE_RX || s_ieee802154_state == IEEE802154_STATE_RX_ACK || s_ieee802154_state == IEEE802154_STATE_TX || s_ie") at /home/simon/src/esp-idf/components/esp_system/port/esp_system_chip.c:84
#2  0x4080ce62 in __assert_func (file=file@entry=0x4206692b "", line=line@entry=463, func=<optimized out>, func@entry=0x42066f48 <__func__.3> "", expr=expr@entry=0x42066ab8 "") at /home/simon/src/esp-idf/components/newlib/assert.c:81
#3  0x4080c02e in ieee802154_isr (arg=arg@entry=0x0) at /home/simon/src/esp-idf/components/ieee802154/driver/esp_ieee802154_dev.c:463
#4  0x4080cf6c in _global_interrupt_handler (sp=<optimized out>, mcause=<optimized out>) at /home/simon/src/esp-idf/components/riscv/interrupt.c:57
#5  0x408001ec in _interrupt_handler ()
```

### More Information.

I've made the assertions more useful by reporting what the current state is: https://github.com/espressif/esp-idf/compare/v5.1...nomis:esp-idf:ieee802154_assert_debug

The current state when the IEEE802154_EVENT_RX_SFD_DONE event occurs is IEEE802154_STATE_IDLE:
```plain
/IDF/components/ieee802154/driver/esp_ieee802154_dev.c:486 s_ieee802154_state=IEEE802154_STATE_IDLE

#0  panic_abort (details=details@entry=0x42069bac "") at /home/simon/src/esp-idf/components/esp_system/panic.c:452
#1  0x408081ba in esp_system_abort (details=details@entry=0x42069bac "") at /home/simon/src/esp-idf/components/esp_system/port/esp_system_chip.c:84
#2  0x4080c7c8 in ieee802154_isr (arg=arg@entry=0x0) at /home/simon/src/esp-idf/components/ieee802154/driver/esp_ieee802154_dev.c:486
#3  0x4080de0c in _global_interrupt_handler (sp=<optimized out>, mcause=<optimized out>) at /home/simon/src/esp-idf/components/riscv/interrupt.c:57
#4  0x408001ec in _interrupt_handler ()
```

**Comment by chshu** [comment]
@nomis There was a bug that 15.4 MAC was not reset during initialization, it has been fixed in latest release/v5.1 branch, but not in v5.1 tag,=.

Could you pull the latest release/v5.1 branch and check if the issue has been fixed there.
