### ISSUE TITLE
Coredump-info broken on 5.1 (IDFGH-11123)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#12293]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

On v5.1.1-439-gcb174b0fe1
calling `coredump-info` on an example project with coredump to flash enabled and nothing but a `abort()` call inside `app_main` results in
```
Executing action: coredump-info
Failed to load core dump: parttool script execution failed with error 1, failed command was: '/tools/python_env/idf5.1_py3.11_env/bin/python /esp-idf/components/partition_table/parttool.py --port /dev/ttyUSB2 --baud 2000000 read_partition --partition-type data --partition-subtype coredump --output /tmp/tmphzas8usu'

┌────── Additional information about the error: 
│   
│   esptool.py v4.7.dev1
│   Serial port /dev/ttyUSB2
│   Connecting....
│   Detecting chip type... Unsupported detection protocol, switching and trying again...
│   Connecting......
│   Detecting chip type... ESP32
│   Chip is ESP32-D0WD-V3 (revision v3.0)
│   Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
│   Crystal is 40MHz
│   MAC: 8c:4b:14:16:76:60
│   Uploading stub...
│   Running stub...
│   Stub running...
│   Changing baud rate to 2000000
│   Changed.
│   3072 (100 %)
│   3072 (100 %)
│   Read 3072 bytes at 0x00008000 in 0.1 seconds (484.4 kbit/s)...
│   Hard resetting via RTS pin...
│   Running /tools/python_env/idf5.1_py3.11_env/bin/python /esp-idf/components/esptool_py/esptool/esptool.py --port /dev/ttyUSB2 --baud 2000000 read_flash 32768 3072 /tmp/tmp11qteib5...
│   Traceback (most recent call last):
│     File "/esp-idf/components/partition_table/parttool.py", line 358, in <module>
│       main()
│     File "/esp-idf/components/partition_table/parttool.py", line 327, in main
│       target = ParttoolTarget(**target_args)
│                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│     File "/esp-idf/components/partition_table/parttool.py", line 105, in __init__
│       partition_table = gen.PartitionTable.from_binary(f.read())
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│     File "/esp-idf/components/partition_table/gen_esp32part.py", line 318, in from_binary
│       result.append(PartitionDefinition.from_binary(data))
│                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│     File "/esp-idf/components/partition_table/gen_esp32part.py", line 467, in from_binary
│       res.name = res.name.decode()
│                  ^^^^^^^^^^^^^^^^^
│   UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte

│   
└────── end of additional information about the error.
```
but it works on master.

**Comment by erhankur** [comment]
We haven't heard of such an issue for a while. I believe it was fixed in one of the IDF releases. @KaeLL Feel free to reopen this if you encounter any issues.
