### ISSUE TITLE
ESP32S2 unable to flash firmware on coredump enabled (IDFGH-11287)

### ISSUE THREAD

**Issue by tsctrl** [espressif/esp-idf#12443]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

idf v4.4.6

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

i have spend 1 day by rebuilding sdkconfig changes to find the exact issue with my flash upload error when enable core dump and end up with specific configuration that was causing issue as below

### What is the actual behavior?

what would be the cause i am not be able to enable c++ exception on coredump? i am using esp32 arduino as component and mostly codes are in class based and c++

this issue happen specifically on s2 where the same config was enabled on older esp32-U without issue 

### Steps to reproduce.

1. change configuration as below:

CONFIG_COMPILER_CXX_EXCEPTIONS=y
CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE=0

CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH=y
HASH CONFIG_ESP32_ENABLE_COREDUMP_TO_UART is not set
HASH CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE is not set
HASH CONFIG_ESP32_COREDUMP_DATA_FORMAT_BIN is not set
CONFIG_ESP32_COREDUMP_DATA_FORMAT_ELF=y
CONFIG_ESP32_COREDUMP_CHECKSUM_CRC32=y
CONFIG_ESP32_ENABLE_COREDUMP=y
CONFIG_ESP32_CORE_DUMP_MAX_TASKS_NUM=16
CONFIG_ESP32_CORE_DUMP_STACK_SIZE=0
`
![image](https://github.com/espressif/esp-idf/assets/75555993/592e46ac-2564-45e2-b817-95dbac05b472)

2. create dump partition
3. rebuild project and flash

### Build or installation Logs.

```plain
tools stop unexpectedly during firmware upload:

Writing at 0x00020000... (10 %)
Writing at 0x0002bc4a... (20 %)
Writing at 0x0003892b... (30 %)
Traceback (most recent call last):
  File "esptool.py", line 5655, in <module>
    _main()
  File "esptool.py", line 5648, in _main
    main()
  File "esptool.py", line 5080, in main
    operation_func(esp, args)
  File "esptool.py", line 4228, in write_flash
    esp.flash_defl_block(block, seq, timeout=timeout)
  File "esptool.py", line 168, in inner
    return func(*args, **kwargs)
  File "esptool.py", line 984, in flash_defl_block
    self.check_command(
  File "esptool.py", line 520, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "esptool.py", line 493, in command
    p = self.read()
  File "esptool.py", line 438, in read
    return next(self._slip_reader)
StopIteration
CMake Error at run_serial_tool.cmake:56 (message):
  python
  esptool.py
  --chip esp32s2 failed
```

### More Information.

on successful flash:
I (315) esp_core_dump_flash: Init core dump to flash
I (320) esp_core_dump_flash: Found partition 'coredump' @ 3a0000 65536 bytes
I (332) esp_core_dump_flash: Core dump data checksum is correct
I (334) esp_core_dump_flash: Found core dump 5156 bytes in flash @ [   764]

might be other issue that cause by the same changes : https://github.com/espressif/esp-idf/issues/3857

**Comment by tsctrl** [comment]
i am closing this issue as i am not able to replicate the issue using new project, probably issue from codes on my end
