### ISSUE TITLE
gen_crt_bundle.py fails with ImportError at 'from cryptography import x509' on M1 Mac (IDFGH-11427)

### ISSUE THREAD

**Issue by dlheard17** [espressif/esp-idf#12565]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-dev-3318-g8fc8f3f

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I expect the 'idf.py build' command to build the hello_world example without an error

### What is the actual behavior?

Build fails with error described in title and the logs. I have ran all of the package setup and even running the gen_crt_bundle.py command afterwords works fine for me.
I also have confirmed that I am able to import the cryptography package when I run the same version of python in the idf5.2_py3.9_env env.

### Steps to reproduce.

1. Run package installation (brew install cmake ninja dfu-util)
2. Run Rosetta for safe measure (/usr/sbin/softwareupdate --install-rosetta --agree-to-license)
3. Clone esp-idf repo
4. Run install.sh
5. Run export.sh
6. Run `idf.py build` in the hello_world dir

### Build or installation Logs.

```plain
idf.py build
.
.
.
-- Adding linker script /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/bootloader/subproject/main/ld/esp32/bootloader.rom.ld
-- Components: bootloader bootloader_support efuse esp_app_format esp_bootloader_format esp_common esp_hw_support esp_rom esp_system esptool_py freertos hal log main micro-ecc newlib partition_table soc spi_flash xtensa
-- Component paths: /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/bootloader /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/bootloader_support /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/efuse /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_app_format /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_bootloader_format /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_common /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_hw_support /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_rom /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esp_system /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/esptool_py /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/freertos /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/hal /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/log /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/bootloader/subproject/main /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/bootloader/subproject/components/micro-ecc /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/newlib /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/partition_table /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/soc /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/spi_flash /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/xtensa
-- Configuring done (8.2s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/DerekHeard_1/embedded_projects/esp/esp-idf/examples/get-started/hello_world/build/bootloader
[671/907] Generating x509_crt_bundle
FAILED: esp-idf/mbedtls/x509_crt_bundle /Users/DerekHeard_1/embedded_projects/esp/esp-idf/examples/get-started/hello_world/build/esp-idf/mbedtls/x509_crt_bundle 
cd /Users/DerekHeard_1/embedded_projects/esp/esp-idf/examples/get-started/hello_world/build/esp-idf/mbedtls && /Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/bin/python /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem /Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_local.pem -q
ImportError: dlopen(/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (no such file), '/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/DerekHeard_1/embedded_projects/esp/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py", line 25, in <module>
    from cryptography import x509
  File "/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/Users/DerekHeard_1/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
[105/106] Generating binary image from built executable
```

**Comment by dobairoland** [comment]
> (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

I assume that running `file /usr/bin/python3` would yield something similar:
```
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):    Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):    Mach-O 64-bit executable arm64e
```

Could you install a Python with `homebrew`? `file /opt/homebrew/bin//python3` should yield something like:
```
/opt/homebrew/bin//python3: Mach-O 64-bit executable arm64
```

After that please follow these steps:

1. remove ~/.espressif/python_env/idf*
2. explicitly set priotity to PATH to Homebrew Python: export PATH=/opt/homebrew/bin/:$PATH
3. double check the Python: file `which python3`- only one arch should be displayed
4. run install.sh

If the above helps then kudos to @georgik. I've re-applied his solution to this issue.
