### ISSUE TITLE
Coredump occasionally doesn't work on v4.4

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#13044]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.6-374-gbb8dd9d35b

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

The auto info_corefile after a crash should reliably read and parse coredumps.

### What is the actual behavior?

Occasionally, processing of the coredump doesn't work.

### Steps to reproduce.

I couldn't reproduce it in a throwaway project in which I'd just trigger the watchdog (which is what is crashing the app and leading to this error when processing the core dump). It occasionally breaks on my main project.
Here's my defconfig
<details>
<summary>defconfig</summary>

```
CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_PERF=y
CONFIG_BOOTLOADER_LOG_LEVEL_NONE=y
CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y
CONFIG_BOOTLOADER_SKIP_VALIDATE_ALWAYS=y
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
# CONFIG_ESPTOOLPY_FLASHSIZE_DETECT is not set
CONFIG_ESPTOOLPY_AFTER_NORESET=y
CONFIG_ESPTOOLPY_MONITOR_BAUD_CONSOLE=y
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions_ota.csv"
CONFIG_PARTITION_TABLE_OFFSET=0xC000
CONFIG_COMPILER_WARN_WRITE_STRINGS=y
CONFIG_BT_ENABLED=y
CONFIG_BTDM_CTRL_BLE_MAX_CONN=1
# CONFIG_BTDM_CTRL_MODEM_SLEEP is not set
# CONFIG_BTDM_BLE_SCAN_DUPL is not set
# CONFIG_BTDM_BLE_ADV_REPORT_FLOW_CTRL_SUPP is not set
# CONFIG_BT_BLE_SMP_ENABLE is not set
CONFIG_BT_STACK_NO_LOG=y
CONFIG_BT_ACL_CONNECTIONS=1
# CONFIG_BT_MULTI_CONNECTION_ENBALE is not set
CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY=y
CONFIG_BT_BLE_HOST_QUEUE_CONG_CHECK=y
CONFIG_SPI_MASTER_IN_IRAM=y
# CONFIG_SPI_SLAVE_ISR_IN_IRAM is not set
CONFIG_ESP_TLS_INSECURE=y
CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY=y
CONFIG_ESP32_REV_MIN_1=y
CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y
CONFIG_ESP32_ULP_COPROC_ENABLED=y
CONFIG_ESP32_ULP_COPROC_RESERVE_MEM=128
# CONFIG_ESP32_DEBUG_OCDAWARE is not set
CONFIG_ESP32_RTC_CLK_SRC_INT_8MD256=y
CONFIG_ETH_DMA_BUFFER_SIZE=256
CONFIG_ETH_DMA_RX_BUFFER_NUM=3
CONFIG_ETH_DMA_TX_BUFFER_NUM=3
# CONFIG_ETH_USE_SPI_ETHERNET is not set
# CONFIG_ESP_EVENT_POST_FROM_ISR is not set
CONFIG_ESP_HTTP_CLIENT_ENABLE_BASIC_AUTH=y
# CONFIG_ESP_HTTP_CLIENT_ENABLE_DIGEST_AUTH is not set
CONFIG_OTA_ALLOW_HTTP=y
# CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE is not set
CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT=y
CONFIG_ESP_MAIN_TASK_STACK_SIZE=10240
CONFIG_ESP_CONSOLE_UART_CUSTOM=y
CONFIG_ESP_CONSOLE_UART_BAUDRATE=921600
CONFIG_ESP_INT_WDT_TIMEOUT_MS=30
CONFIG_ESP_TASK_WDT_PANIC=y
CONFIG_ESP_TASK_WDT_TIMEOUT_S=2
# CONFIG_ESP32_WIFI_NVS_ENABLED is not set
# CONFIG_ESP32_WIFI_IRAM_OPT is not set
# CONFIG_ESP32_WIFI_RX_IRAM_OPT is not set
CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE=y
CONFIG_ESP_COREDUMP_ENABLE_TO_UART=y
CONFIG_ESP_COREDUMP_MAX_TASKS_NUM=30
CONFIG_ESP_COREDUMP_STACK_SIZE=1024
CONFIG_FREERTOS_CORETIMER_1=y
CONFIG_FREERTOS_HZ=200
CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK=y
# CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER is not set
CONFIG_HEAP_ABORT_WHEN_ALLOCATION_FAILS=y
CONFIG_LOG_DEFAULT_LEVEL_DEBUG=y
CONFIG_LWIP_TCP_SND_BUF_DEFAULT=5744
CONFIG_LWIP_TCP_WND_DEFAULT=5744
CONFIG_LWIP_SNTP_MAX_SERVERS=4
CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN=y
CONFIG_MBEDTLS_TLS_CLIENT_ONLY=y
# CONFIG_MQTT_TRANSPORT_WEBSOCKET is not set
CONFIG_NVS_ASSERT_ERROR_CHECK=y
# CONFIG_SPI_FLASH_ENABLE_ENCRYPTED_READ_WRITE is not set
CONFIG_WIFI_PROV_BLE_BONDING=y
CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION=y
CONFIG_EMAC_RECV_TASK_CORE=0
```

</details>

### Build or installation Logs.

<details>
<summary>Log of the crash followed by the failed coredump</summary>

```
E (10783) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (10783) task_wdt:  - IDLE0 (CPU 0)
E (10783) task_wdt: Tasks currently running:
E (10783) task_wdt: CPU 0: mqtt_task
E (10783) task_wdt: CPU 1: IDLE1
E (10783) task_wdt: Aborting.

abort() was called at PC 0x4013b4cc on core 0
0x4013b4cc: task_wdt_isr at /esp-idf/components/esp_system/task_wdt.c:176 (discriminator 3)



Backtrace: 0x40081e66:0x3ffbeaa0 0x400940f1:0x3ffbeac0 0x4009a8ca:0x3ffbeae0 0x4013b4cc:0x3ffbeb50 0x4008347d:0x3ffbeb70 0x4016c3fc:0x3ffd4b00 0x4016d0fb:0x3ffd4b20 0x4016f735:0x3ffd4bb0 0x40170855:0x3ffd4c10 0x40170a22:0x3ffd4c60 0x40170e9b:0x3ffd4d20 0x4016ec43:0x3ffd4d60 0x4016ed9a:0x3ffd4dc0 0x4016edc5:0x3ffd4df0 0x4016ef16:0x3ffd4e10 0x4016b579:0x3ffd4e40 0x4016b97f:0x3ffd4e70 0x40169557:0x3ffd4e90 0x40169589:0x3ffd4eb0 0x40160359:0x3ffd4ed0 0x4015f631:0x3ffd4ef0 0x4015faff:0x3ffd4f10 0x4015fe3b:0x3ffd4f90 0x4016230b:0x3ffd4fc0 0x401ca0e5:0x3ffd4fe0 0x401283e8:0x3ffd5000
0x40081e66: panic_abort at /esp-idf/components/esp_system/panic.c:408

0x400940f1: esp_system_abort at /esp-idf/components/esp_system/esp_system.c:137

0x4009a8ca: abort at /esp-idf/components/newlib/abort.c:46

0x4013b4cc: task_wdt_isr at /esp-idf/components/esp_system/task_wdt.c:176 (discriminator 3)

0x4008347d: _xt_lowint1 at /esp-idf/components/freertos/port/xtensa/xtensa_vectors.S:1118

0x4016c3fc: mbedtls_mpi_cmp_mpi at /esp-idf/components/mbedtls/mbedtls/library/bignum.c:1107

0x4016d0fb: mbedtls_mpi_inv_mod at /esp-idf/components/mbedtls/mbedtls/library/bignum.c:2670

0x4016f735: ecp_normalize_jac_many at /esp-idf/components/mbedtls/mbedtls/library/ecp.c:1424

0x40170855: ecp_precompute_comb at /esp-idf/components/mbedtls/mbedtls/library/ecp.c:1993

0x40170a22: ecp_mul_comb at /esp-idf/components/mbedtls/mbedtls/library/ecp.c:2390

0x40170e9b: mbedtls_ecp_mul_restartable at /esp-idf/components/mbedtls/mbedtls/library/ecp.c:2763

0x4016ec43: ecdh_compute_shared_restartable at /esp-idf/components/mbedtls/mbedtls/library/ecdh.c:127

0x4016ed9a: mbedtls_ecdh_compute_shared at /esp-idf/components/mbedtls/mbedtls/library/ecdh.c:155

0x4016edc5: ecdh_calc_secret_internal at /esp-idf/components/mbedtls/mbedtls/library/ecdh.c:685

0x4016ef16: mbedtls_ecdh_calc_secret at /esp-idf/components/mbedtls/mbedtls/library/ecdh.c:722

0x4016b579: ssl_write_client_key_exchange at /esp-idf/components/mbedtls/mbedtls/library/ssl_cli.c:3753

0x4016b97f: mbedtls_ssl_handshake_client_step at /esp-idf/components/mbedtls/mbedtls/library/ssl_cli.c:4347

0x40169557: mbedtls_ssl_handshake_step at /esp-idf/components/mbedtls/mbedtls/library/ssl_tls.c:5770

0x40169589: mbedtls_ssl_handshake at /esp-idf/components/mbedtls/mbedtls/library/ssl_tls.c:5808

0x40160359: esp_mbedtls_handshake at /esp-idf/components/esp-tls/esp_tls_mbedtls.c:176

0x4015f631: esp_tls_handshake at /esp-idf/components/esp-tls/esp_tls.c:82

0x4015faff: esp_tls_low_level_conn at /esp-idf/components/esp-tls/esp_tls.c:433 (discriminator 9)

0x4015fe3b: esp_tls_conn_new_sync at /esp-idf/components/esp-tls/esp_tls.c:495

0x4016230b: ssl_connect at /esp-idf/components/tcp_transport/transport_ssl.c:105

0x401ca0e5: esp_transport_connect at /esp-idf/components/tcp_transport/transport.c:123

0x401283e8: esp_mqtt_task at /esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:1472





ELF file SHA256: 95107ea7f9956ef4

Initiating core dump!
I (10795) esp_core_dump_uart: Press Enter to print core dump to UART...
I (10796) esp_core_dump_uart: Print core dump to uart...
I (10797) esp_core_dump_common: Backing up stack @ 0x3ffbe870 and use core dump stack @ 0x3ffc5a80
Core dump started (further output muted)
Received  30 kB...
Core dump finished!
Failed to run espcoredump script: Command '['/tools/python_env/idf4.4_py3.11_env/bin/python', '/esp-idf/tools/idf_monitor_base/../../components/espcoredump/espcoredump.py', 'info_corefile', '--core', '/tmp/tmp2qkerm9j', '--core-format', 'b64', '/project/build/project.elf']' returned non-zero exit status 1.
b'espcoredump.py v0.4-dev\nTraceback (most recent call last):\n  File "/esp-idf/tools/idf_monitor_base/../../components/espcoredump/espcoredump.py", line 430, in <module>\n    temp_core_files = info_corefile()\n                      ^^^^^^^^^^^^^^^\n  File "/esp-idf/tools/idf_monitor_base/../../components/espcoredump/espcoredump.py", line 220, in info_corefile\n    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/esp-idf/tools/idf_monitor_base/../../components/espcoredump/espcoredump.py", line 115, in get_core_dump_elf\n    loader.create_corefile(exe_name=args.prog, e_machine=e_machine)\n  File "/esp-idf/components/espcoredump/corefile/loader.py", line 244, in create_corefile\n    self._extract_elf_corefile(exe_name, e_machine)\n  File "/esp-idf/components/espcoredump/corefile/loader.py", line 285, in _extract_elf_corefile\n    raise ESPCoreDumpLoaderError(\ncorefile.ESPCoreDumpLoaderError: Invalid application image for coredump: coredump SHA256(95107ea7f9956ef4) != app SHA256(aebe6ed9707da33f).\n'


================= CORE DUMP START =================
```

</details>

**Comment by KaeLL** [comment]
Just realized the elf used wasn't the one used to generate the binary for the app. My mistake.
