### ISSUE TITLE
Cannot run install.ps1: Invalid argument (IDFGH-12090)

### ISSUE THREAD

**Issue by xobs** [espressif/esp-idf#13148]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3-dev-1978-g4fb231088d

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Before, when I wanted to update `esp-idf`, I would do `git pull`. If it required a new toolchain, I would run `install.ps1`. I expected this to continue to work.

### What is the actual behavior?

An error is thrown in `idf_tools.py` line 3157:

```
[9:53:33 am] ~/esp/esp-idf> .\install.ps1
Installing ESP-IDF tools
Traceback (most recent call last):
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 3157, in <module>
    main(sys.argv[1:])
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 3149, in main
    action_func(args)
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 2303, in action_install
    targets = add_and_check_targets(idf_env_obj, args.targets)
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1710, in add_and_check_targets
    targets = parse_targets_arg(targets_str)
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1691, in parse_targets_arg
    targets_from_tools_json = get_all_targets_from_tools_json()
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1744, in get_all_targets_from_tools_json
    tools_info = load_tools_info()
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1538, in load_tools_info
    return parse_tools_info_json(tools_info)  # type: ignore
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1553, in parse_tools_info_json
    tool = IDFTool.from_json(tool_dict)
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 1230, in from_json
    if Platforms.get(platform_id) is None:
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 215, in get
    platform_name = Platforms.detect_linux_arm_platform(platform_name)
  File "C:\Users\Sean\esp\esp-idf\tools\idf_tools.py", line 186, in detect_linux_arm_platform
    with open(sys.executable, 'rb') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Sean\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe'
[9:53:36 am] ~/esp/esp-idf> git describe --tags
v5.3-dev-1978-g4fb231088d
[9:54:07 am] ~/esp/esp-idf> C:\\Users\\Sean\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
[9:56:05 am] ~/esp/esp-idf>
```

### Steps to reproduce.

1. Clone `esp-idf`
2. Run `install.ps1`

**Comment by xobs** [comment]
Note that it works if I checkout `v5.3-dev` rather than `master`, so the issue seems to have been introduced since then.

**Comment by xobs** [comment]
Thanks for the fix!
