### ISSUE TITLE
Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))-[xtensa-esp32s3-espidf] (IDFGH-12351)

### ISSUE THREAD

**Issue by blue-freedom-technologies** [espressif/esp-idf#13382]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2

### Espressif SoC revision.

ESP32-S3 (revision: v0.1)

### Operating System used.

Linux

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-S3-DevKitC-1-N32R8V

### Power Supply used.

USB

### What is the expected behavior?

Connect to a RPC node (A RPC Node is a server in a network that can process RPC requests from clients) using my ESP32-S3 board.

### What is the actual behavior?

```text
I (11148) mcu_app: Connection error: Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))
```

### Steps to reproduce.

1. cargo run --bin mcu-app --release
2. I (11148) mcu_app: Connection error: Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))
...

### Debug Logs.

```plain
I (9908) mcu_app: Wifi connected...!!!
I (9918) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (9918) wifi:<ba-add>idx:0 (ifx:0, fc:34:97:8a:61:c0), tid:6, ssn:1, winSize:64
I (10908) esp_netif_handlers: sta ip: 192.168.50.97, mask: 255.255.255.0, gw: 192.168.50.1
I (10908) mcu_app: Wifi netif up...!!!
I (10908) mcu_app: Wifi DHCP info: IpInfo { ip: 192.168.50.97, subnet: Subnet { gateway: 192.168.50.1, mask: Mask(24) }, dns: Some(192.168.50.1), secondary_dns: Some(0.0.0.0) }
I (10928) wifi:<ba-add>idx:1 (ifx:0, fc:34:97:8a:61:c0), tid:0, ssn:1, winSize:64
I (11148) mcu_app: Connection error: Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))
```

### More Information.

cargo run --bin mcu-app --release

sdkconfig.defaults
```text
CONFIG_ESP_MAIN_TASK_STACK_SIZE=8000

CONFIG_ESP_TASK_WDT_TIMEOUT_S=15

CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y
CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE=y
CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE_PATH="certs"

CONFIG_SPIRAM=y


CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_TYPE_AUTO=y
CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=y
CONFIG_SPIRAM_CLK_IO=30
CONFIG_SPIRAM_CS_IO=26
CONFIG_SPIRAM_SPEED_40M=y
CONFIG_SPIRAM_SPEED=40
CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768

```

**Comment by MabezDev** [comment]
I'm not sure why you closed https://github.com/esp-rs/esp-idf-hal/issues/393 and posted it here without adding more context? For instance, we don't know what APIs you're using, or ones you've tried. Can you post a minimal reproduction and then we can help you.

**Comment by blue-freedom-technologies** [comment]
Hi,

For my understanding, the ESP x509 Certificate Bundle API provides an way to include a bundle of custom x509 root certificates for TLS server verification.

[CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y](https://docs.espressif.com/projects/esp-idf/en/stable/esp32s2/api-reference/kconfig.html#config-mbedtls-certificate-bundle)

When enabled this option allows us to store default root certificates. I this correct ?

If yes, we should not have  this error message "Failed to load system certs: No valid certificate found".

I am doing something wrong here ? Or I need to create a custom certificate just for this to work ?

**Comment by blue-freedom-technologies** [comment]
ok, after some changings we have a proper error in generating of the x509 crt bundle.

I am using this [cacert.pem](https://curl.se/ca/cacert.pem)  bundle and executing this command.

```
RUST_BACKTRACE=full cargo build --bin mcu-app --release
```

<details>

<summary>Generating x509_crt_bundle</summary>

```text
The following warnings were emitted during compilation:

warning: esp-idf-sys@0.34.1: Compiler version doesn't include clang or GCC: "./espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/xtensa-esp32-elf-cc" "--version"
warning: esp-idf-sys@0.34.1: Compiler version doesn't include clang or GCC: "c++" "--version"

error: failed to run custom build command for `esp-idf-sys v0.34.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/mcu-app/target/release/build/esp-idf-sys-567c6d69b47f1bee/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENT_MANAGER
  IDF_PYTHON_ENV_PATH=/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env
  ESP_IDF_VERSION=5.1
  PATH=/mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin:/mcu-app/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/mcu-app/.embuild/espressif/tools/cmake/3.24.0/bin:/mcu-app/.embuild/espressif/tools/ninja/1.10.2/:/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools:$PATH
  IDF_DEACTIVATE_FILE_PATH=/tmp/tmp_vw0xvzvidf_81157
  Current system platform: linux-amd64
  Skipping xtensa-esp32s3-elf@esp-12.2.0_20230208 (already installed)
  Skipping cmake@3.24.0 (already installed)
  Skipping ninja@1.10.2 (already installed)
  Skipping esp32ulp-elf@2.35_20220830 (already installed)
  IDF_PYTHON_ENV_PATH=/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env
  ESP_IDF_VERSION=5.1
  PATH=/mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin:/mcu-app/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/mcu-app/.embuild/espressif/tools/cmake/3.24.0/bin:/mcu-app/.embuild/espressif/tools/ninja/1.10.2/:/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools:$PATH
  IDF_DEACTIVATE_FILE_PATH=/tmp/tmp95e2ueljidf_81157
  cargo:rerun-if-changed=/mcu-app/sdkconfig.defaults
  cargo:warning=Compiler version doesn't include clang or GCC: "./espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/xtensa-esp32-elf-cc" "--version"
  cargo:warning=Compiler version doesn't include clang or GCC: "c++" "--version"
  CMAKE_PREFIX_PATH_xtensa-esp32s3-espidf = None
  CMAKE_PREFIX_PATH_xtensa_esp32s3_espidf = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_xtensa-esp32s3-espidf = None
  CMAKE_xtensa_esp32s3_espidf = None
  TARGET_CMAKE = None
  CMAKE = None
  running: cd "/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/build" && CMAKE_PREFIX_PATH="" EXTRA_COMPONENT_DIRS="" IDF_COMPONENT_MANAGER="1" IDF_PATH="/mcu-app/.embuild/espressif/esp-idf/v5.1.2" IDF_TARGET="esp32s3" IDF_TOOLS_PATH="/mcu-app/.embuild/espressif" PATH="/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/mcu-app/.embuild/espressif/tools/ninja/1.10.2/:/mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin:/mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools:/mcu-app/.embuild/espressif/tools/cmake/3.24.0/bin:/mcu-app/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:./nvm/versions/node/v18.14.2/bin:./cargo/bin:./local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/Android/Sdk/emulator:/Android/Sdk/platform-tools:/opt/riscv/bin:/usr/local/bin/" PROJECT_DIR="/mcu-app" SDKCONFIG_DEFAULTS="/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/gen-sdkconfig.defaults;/mcu-app/sdkconfig.defaults" "cmake" "/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out" "-G" "Ninja" "-DCMAKE_TOOLCHAIN_FILE=/mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools/cmake/toolchain-esp32s3.cmake" "-DCMAKE_BUILD_TYPE=" "-DPYTHON=/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin/python" "-DCMAKE_INSTALL_PREFIX=/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out" "-DCMAKE_C_FLAGS= -mlongcalls -ffunction-sections -fdata-sections -mlongcalls" "-DCMAKE_CXX_FLAGS= -mlongcalls -ffunction-sections -fdata-sections" "-DCMAKE_ASM_FLAGS= -mlongcalls -ffunction-sections -fdata-sections -mlongcalls"
  -- Found Git: /usr/bin/git (found version "2.34.1") 
  -- The C compiler identification is GNU 12.2.0
  -- The CXX compiler identification is GNU 12.2.0
  -- The ASM compiler identification is GNU
  -- Found assembler: /mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Building ESP-IDF components for target esp32s3
  -- Checking Python dependencies...
  Python requirements are satisfied.
  Constraint file: /mcu-app/.embuild/espressif/espidf.constraints.v5.1.txt
  Requirement files:
   - /mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools/requirements/requirements.core.txt
  Python being checked: /mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin/python
  -- Project sdkconfig file /mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/sdkconfig
  Loading defaults file /mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/gen-sdkconfig.defaults...
  Loading defaults file /mcu-app/sdkconfig.defaults...
  /tmp/kconfgen_tmpgkeb49f7:8 line was updated to #CONFIG_VFS_SUPPORT_TERMIOS=n
  /tmp/kconfgen_tmpgkeb49f7:11 line was updated to #CONFIG_ESP_DEBUG_STUBS_ENABLE=n
  /tmp/kconfgen_tmpgkeb49f7:12 line was updated to #CONFIG_ESP_ERR_TO_NAME_LOOKUP=n
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of time_t
  -- Check size of time_t - done
  -- Found Python3: /mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin/python (found version "3.10.12") found components: Interpreter 
  -- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
  -- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
  -- App "libespidf" version: 2eed4d5
  -- Adding linker script /mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/build/esp-idf/esp_system/ld/memory.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_system/ld/esp32s3/sections.ld.in
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom/esp32s3/ld/esp32s3.rom.version.ld
  -- Adding linker script /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/soc/esp32s3/ld/esp32s3.peripherals.ld
  -- Components: app_trace app_update bootloader bootloader_support bt cmock console cxx driver efuse esp-tls esp_adc esp_app_format esp_coex esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_mm esp_netif esp_netif_stack esp_partition esp_phy esp_pm esp_psram esp_ringbuf esp_rom esp_system esp_timer esp_wifi espcoredump esptool_py fatfs freertos hal heap http_parser idf_test ieee802154 json log lwip main mbedtls mqtt newlib nvs_flash openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport touch_element ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
  -- Component paths: /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/app_trace /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/app_update /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/bootloader /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/bootloader_support /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/bt /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/cmock /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/console /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/cxx /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/driver /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/efuse /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp-tls /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_adc /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_app_format /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_coex /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_common /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_eth /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_event /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_gdbstub /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_hid /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_http_client /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_http_server /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_https_ota /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_https_server /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_hw_support /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_lcd /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_local_ctrl /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_mm /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_netif /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_netif_stack /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_partition /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_phy /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_pm /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_psram /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_ringbuf /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_rom /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_system /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_timer /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esp_wifi /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/espcoredump /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/esptool_py /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/fatfs /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/freertos /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/hal /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/heap /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/http_parser /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/idf_test /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/ieee802154 /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/json /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/log /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/lwip /mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/main /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/mbedtls /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/mqtt /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/newlib /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/nvs_flash /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/openthread /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/partition_table /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/perfmon /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/protobuf-c /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/protocomm /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/pthread /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/sdmmc /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/soc /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/spi_flash /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/spiffs /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/tcp_transport /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/touch_element /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/ulp /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/unity /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/usb /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/vfs /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/wear_levelling /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/wifi_provisioning /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/wpa_supplicant /mcu-app/.embuild/espressif/esp-idf/v5.1.2/components/xtensa
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/build
  running: cd "/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/build" && EXTRA_COMPONENT_DIRS="" IDF_COMPONENT_MANAGER="1" IDF_PATH="/mcu-app/.embuild/espressif/esp-idf/v5.1.2" IDF_TARGET="esp32s3" IDF_TOOLS_PATH="/mcu-app/.embuild/espressif" PATH="/mcu-app/.embuild/espressif/python_env/idf5.1_py3.10_env/bin:/mcu-app/.embuild/espressif/tools/ninja/1.10.2/:/mcu-app/.embuild/espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin:/mcu-app/.embuild/espressif/esp-idf/v5.1.2/tools:/mcu-app/.embuild/espressif/tools/cmake/3.24.0/bin:/mcu-app/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:./nvm/versions/node/v18.14.2/bin:./cargo/bin:./local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/Android/Sdk/emulator:/Android/Sdk/platform-tools:/opt/riscv/bin:/usr/local/bin/" PROJECT_DIR="/mcu-app" SDKCONFIG_DEFAULTS="/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/gen-sdkconfig.defaults;/mcu-app/sdkconfig.defaults" "cmake" "--build" "." "--config" "Release" "--parallel" "8"

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: Some(
          "esp32s3",
      ),
      native: NativeConfig {
          esp_idf_version: Some(
              Tag(
                  "v5.1.2",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [],
          esp_idf_components: None,
          esp_idf_component_manager: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Tag("v5.1.2") }
  Using esp-idf v5.1.2 at '/mcu-app/.embuild/espressif/esp-idf/v5.1.2'
  Compiler supported targets: xtensa-esp32s3-elf

  ninja: error: '/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/certs', needed by 'esp-idf/mbedtls/x509_crt_bundle', missing and no known rule to make it
  thread 'main' panicked at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  stack backtrace:
     0:     0x5851e0c9926a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ff8fc9f179cb0e2
     1:     0x5851e0cc8480 - core::fmt::write::h9b3b3f647ad2b677
     2:     0x5851e0c897ee - std::io::Write::write_fmt::hcfcce02ced682e64
     3:     0x5851e0c98ff4 - std::sys_common::backtrace::print::h0891e23eacfc9b7d
     4:     0x5851e0c76c13 - std::panicking::default_hook::{{closure}}::h914ba34d884b80ea
     5:     0x5851e0c76934 - std::panicking::default_hook::h527f8f43da2ce6c9
     6:     0x5851e0c77075 - std::panicking::rust_panic_with_hook::hc767fbf24362fef9
     7:     0x5851e0c99772 - std::panicking::begin_panic_handler::{{closure}}::haa4e1f439b5c6e64
     8:     0x5851e0c994a6 - std::sys_common::backtrace::__rust_end_short_backtrace::he160198b19b60fbb
     9:     0x5851e0c76db0 - rust_begin_unwind
    10:     0x5851e0339255 - core::panicking::panic_fmt::hcbed93a894a59bd5
    11:     0x5851e057a681 - cmake::fail::h7a225077c1f2588e
    12:     0x5851e0579e17 - cmake::run::h88731c208537eef3
    13:     0x5851e057674d - cmake::Config::build::h27b52bd634179bc7
    14:     0x5851e03b9d62 - build_script_build::native::cargo_driver::build::h0f7c82aec3da8660
    15:     0x5851e035bf8b - build_script_build::native::build::h3f9dbd1ccb9133ee
    16:     0x5851e039a39a - build_script_build::main::h43431f3f1efc304f
    17:     0x5851e036b143 - core::ops::function::FnOnce::call_once::hc8211f5b57297070
    18:     0x5851e03587c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9c75ce69f635a059
    19:     0x5851e03c2849 - std::rt::lang_start::{{closure}}::h44370f98e89a4ada
    20:     0x5851e0c79087 - std::rt::lang_start_internal::h9b2adcc63a960161
    21:     0x5851e03c2827 - std::rt::lang_start::hcd1b98c131f75878
    22:     0x5851e039d535 - main
    23:     0x7651ba629d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    24:     0x7651ba629e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    25:     0x5851e0339b15 - _start
    26:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...

```
</details>

ninja: error: '/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/certs', needed by 'esp-idf/mbedtls/x509_crt_bundle', missing and no known rule to make it
  thread 'main' panicked at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

Cheers,

**Comment by blue-freedom-technologies** [comment]
This error is clearly a bug:

```text
ninja: error: '/mcu-app/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-79fed1f10b9c81ba/out/certs', needed by 'esp-idf/mbedtls/x509_crt_bundle', missing and no known rule to make it
thread 'main' panicked at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:
```

Because as soon as we manually copy the certificates into that path, everything goes well.

![image](https://github.com/espressif/esp-idf/assets/142290531/1340c73c-b707-479f-accf-c50749aa0cf3)


But my main error stays the same:
```text
Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))
```

No certificate is installed in the ESP32-S3 certificate store.

**Comment by blue-freedom-technologies** [comment]
Unfortunately, The [native certificate store](https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.use_native_rustls) crate does not support the ESP-IDF framework.
