### ISSUE TITLE
Wi-Fi Provisioning using console scheme & `esp_prov` fails with type error (IDFGH-13068)

### ISSUE THREAD

**Issue by anujdeshpande** [espressif/esp-idf#14013]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.2-163-gf81b598d10

### Espressif SoC revision.

esp32s3

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32s3 devkit

### Power Supply used.

USB

### What is the expected behavior?

I expected `esp_prov` to parse response from console

### What is the actual behavior?

```
 python esp_prov.py -v --transport console  --pop abcd1234 --sec_ver 1  --ssid SSID --passphrase PASSWORD
Client->Device msg : proto-ver 0 6e6f5f706f70
Enter device->client msg : 7b0a092270726f76223a097b0a090922766572223a092276312e31222c0a0909227365635f766572223a09312c0a090922636170223a095b22776966695f7363616e225d0a097d0a7d

==== Starting Session ====
++++ Client Public Key: 0xa8f74fd6215e7179bb4c50527fce464f791f0d0e2fc02d48cdb8d02153b91c4a ++++
Client->Device msg : prov-session 0 10015a25a201220a20a8f74fd6215e7179bb4c50527fce464f791f0d0e2fc02d48cdb8d02153b91c4a
Enter device->client msg : 10015a390801aa013412206bd18a8f70d8d5b553bea0af87e7fb6d838e8b7537df7027dd8724a133ff721a1a10704c41b4eb9cf6c838cf3c269b8ca5fd
Traceback (most recent call last):
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/esp_prov.py", line 534, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/esp_prov.py", line 456, in main
    if not await establish_session(obj_transport, obj_security):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/esp_prov.py", line 155, in establish_session
    request = sec.security_session(response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/security/security1.py", line 46, in security1_session
    self.setup0_response(response_data)
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/security/security1.py", line 79, in setup0_response
    setup_resp.ParseFromString(str_to_bytes(response_data))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tony/frameworks/esp/esp-idf/tools/esp_prov/utils/convenience.py", line 19, in str_to_bytes
    return bytes(s, encoding='latin-1')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: encoding without a string argument
```

### Steps to reproduce.

My patch for adding support for console to the existing IDF example

[0001-Add-support-for-console.patch](https://github.com/user-attachments/files/15887236/0001-Add-support-for-console.patch)

### Debug Logs.

```plain
I (467) wifi:wifi driver task: 3fcabdc4, prio:23, stack:6656, core=0
I (467) wifi:wifi firmware version: 803d274
I (467) wifi:wifi certification version: v7.0
I (467) wifi:config NVS flash: enabled
I (467) wifi:config nano formating: disabled
I (477) wifi:Init data frame dynamic rx buffer num: 32
I (477) wifi:Init static rx mgmt buffer num: 5
I (487) wifi:Init management short buffer num: 32
I (487) wifi:Init dynamic tx buffer num: 32
I (497) wifi:Init static tx FG buffer num: 2
I (497) wifi:Init static rx buffer size: 1600
I (497) wifi:Init static rx buffer num: 10
I (507) wifi:Init dynamic rx buffer num: 32
I (507) wifi_init: rx ba win: 6
I (517) wifi_init: tcpip mbox: 32
I (517) wifi_init: udp mbox: 6
I (517) wifi_init: tcp mbox: 6
I (527) wifi_init: tcp tx win: 5760
I (527) wifi_init: tcp rx win: 5760
I (537) wifi_init: tcp mss: 1440
I (537) wifi_init: WiFi IRAM OP enabled
I (537) wifi_init: WiFi RX IRAM OP enabled
I (547) app: Starting provisioning
I (547) phy_init: phy_version 670,b7bc9b9,Apr 30 2024,10:54:13
I (597) wifi:mode : sta (ec:da:3b:54:b3:74)
I (597) wifi:enable tsf
I (607) uart: queue free spaces: 8
I (607) wifi_prov_mgr: Provisioning started with service name : PROV_54B374
I (607) app: Provisioning started

>> proto-ver 0 6e6f5f706f70

7b0a092270726f76223a097b0a090922766572223a092276312e31222c0a0909227365635f766572223a09312c0a090922636170223a095b22776966695f7363616e225d0a097d0a7d

>> prov-session 0 10015a25a201220a20a8f74fd6215e7179bb4c50527fce464f791f0d0e2fc02d48cdb8d02153b91c4a

10015a390801aa013412206bd18a8f70d8d5b553bea0af87e7fb6d838e8b7537df7027dd8724a133ff721a1a10704c41b4eb9cf6c838cf3c269b8ca5fd

>>
```
```


### More Information.

_No response_

**Comment by Harshal5** [comment]
Hi @anujdeshpande,

Thanks for reporting the issue, I am able to recreate it on my end.
This seems to be due to incorrect decoding of the console input and I think the fix should be replacing `hex_str_to_bytes(resp)` with `bytearray.fromhex(resp).decode('latin-1')` [here](https://github.com/espressif/esp-idf/blob/master/tools/esp_prov/transport/transport_console.py#L19).

Taking up this internally.
Thanks!
