### ISSUE TITLE
Hanging in spi_flash_disable_interrupts_caches_and_other_cpu() with esp-idf 5.3 (IDFGH-13656)

### ISSUE THREAD

**Issue by pragulka** [espressif/esp-idf#14535]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello, 

We've been trying to upgrade from ESP-IDF 5.0 to 5.3 for our product line.
However the firmware update process fails on devices with ESP-IDF 5.3 and  ESP32-S3 v0.1. No issues with chip v0.2 or ESP-IDF 5.0.
With chip v0.1 and ESP-iDF 5.3 ESP32-S3 always restarts with InterruptWDTTimoutCPU1 and CPU0 hangs in spi_flash_disable_interrupts_caches_and_other_cpu () at /opt/esp/idf/components/spi_flash/cache_utils.c:208
This is likely a software issue, since our devices have been working fine with ESP-IDF 5.0, however it is difficult to pinpoint the root cause.
I've tried increasing "offending" and interrupt task sizes and interrupt watchdog timeout, but it has not helped so far.
Not enabling imu_task solves the crash, but not the issue.
What else could I try?

>==================== THREAD 1 (TCB: 0x3fcb2650, name: 'imu_task') =====================
#0  0x403883b2 in xPortEnterCriticalTimeout (mux=<optimized out>, timeout=-1) at /opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:488
#1  0x4037841a in vPortEnterCritical (mux=0x3fca596c <spinlock>) at /opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:567
#2  shared_intr_isr (arg=0x3fcc6e58) at /opt/esp/idf/components/esp_hw_support/intr_alloc.c:440
#3  0x4037b40c in _xt_lowint1 () at /opt/esp/idf/components/xtensa/xtensa_vectors.S:1240
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
>
>==================== THREAD 6 (TCB: 0x3fcdbef8, name: 'fota_task') =====================
#0  0x40376bfe in spi_flash_disable_interrupts_caches_and_other_cpu () at /opt/esp/idf/components/spi_flash/cache_utils.c:208
#1  0x40376a66 in cache_disable (arg=0x0) at /opt/esp/idf/components/spi_flash/spi_flash_os_func_app.c:70
#2  0x40376a6e in spi1_start (arg=0x3fca7ddc <main_flash_arg>) at /opt/esp/idf/components/spi_flash/spi_flash_os_func_app.c:122
#3  0x403822ae in spiflash_start_default (chip=0x3fca7d64 <default_chip>) at /opt/esp/idf/components/spi_flash/esp_flash_api.c:188
#4  0x40375eb0 in flash_end_flush_cache (chip=0x3fca7d64 <default_chip>, err=0, bus_acquired=<optimized out>, address=4325376, length=4096) at /opt/esp/idf/components/spi_flash/esp_flash_api.c:229
#5  0x40376890 in esp_flash_write_encrypted (chip=<optimized out>, address=4325376, buffer=0x3fcac0f8 <chunk>, length=4096) at /opt/esp/idf/components/spi_flash/esp_flash_api.c:1400
#6  0x420e6492 in esp_partition_write (partition=<optimized out>, dst_offset=<optimized out>, src=0x3fcac0f8 <chunk>, size=4096) at /opt/esp/idf/components/esp_partition/partition_target.c:85
#7  0x4206ca60 in esp_ota_write (handle=<optimized out>, data=<optimized out>, size=4096) at /opt/esp/idf/components/app_update/esp_ota_ops.c:246
#8  0x42011d91 in handle_compressed_message ()
#9  0x42011f9d in fota_task ()
#10 0x4038816c in vPortTaskWrapper (pxCode=0x42011ec4 <fota_task>, pvParameters=0x2) at /opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

**Comment by pragulka** [comment]
Migrated from legacy i2c drivers. No OTA issues with ESP-IDF 5.3.1 so far.
