### ISSUE TITLE
[TW#18513] xtensa-esp32-elf-ar: libmain.a: Permission denied

### ISSUE THREAD

**Issue by Tianxiaomo** [espressif/esp-idf#1596]
I have a problem compiling any example. I'm using eclipse and mingw32.exe on Windows 7.

15:29:01 **** Incremental Build of configuration Default for project esp-idf ****
make all 
AR libmain.a
xtensa-esp32-elf-ar: libmain.a: Permission denied
LD spi_master.elf
/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find -lmain
collect2: error: ld returned 1 exit status
esptool.py v2.0-beta2
Traceback (most recent call last):
  File "/cygdrive/d/AiThinkerIDE_V0.5/cygwin/home/aithinker/project/esp-idf/components/esptool_py/esptool/esptool.py", line 2294, in <module>
    main()
  File "/cygdrive/d/AiThinkerIDE_V0.5/cygwin/home/aithinker/project/esp-idf/components/esptool_py/esptool/esptool.py", line 2096, in main
    operation_func(args)
  File "/cygdrive/d/AiThinkerIDE_V0.5/cygwin/home/aithinker/project/esp-idf/components/esptool_py/esptool/esptool.py", line 1713, in elf2image
    e = ELFFile(args.input)
  File "/cygdrive/d/AiThinkerIDE_V0.5/cygwin/home/aithinker/project/esp-idf/components/esptool_py/esptool/esptool.py", line 1325, in __init__
    with open(self.name, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/aithinker/project/esp-idf/examples/peripherals/spi_master/build/spi_master.elf'
To flash all build output, run 'make flash' or:
python /cygdrive/d/AiThinkerIDE_V0.5/cygwin/home/aithinker/project/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 /home/aithinker/project/esp-idf/examples/peripherals/spi_master/build/bootloader/bootloader.bin 0x10000 /home/aithinker/project/esp-idf/examples/peripherals/spi_master/build/spi_master.bin 0x8000 /home/aithinker/project/esp-idf/examples/peripherals/spi_master/build/partitions_singleapp.bin

**Comment by igrr** [comment]
From the log it looks like you are using Cygwin environment (`/cygdrive/d/AiThinkerIDE_V0.5/cygwin`). ESP-IDF build system does not support Cygwin. Please follow the [Getting Started Guide for Windows](http://esp-idf.readthedocs.io/en/latest/get-started/windows-setup.html) to install MSYS2 environment.
