### ISSUE TITLE
[TW#26744] make flash is error in MAC env

### ISSUE THREAD

**Issue by rillhu** [espressif/esp-idf#2554]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Core (if using chip or module): ESP-WROOM32
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    221eced06
- Development Env:		Make
- Operating System:		MacOS 0.14 (18A391)
- Power Supply:         USB

## Problem Description
When I run make flash it gives below error. It looks esptoolpy cannot open Serial port cu.SLAB_USBtoUART, but I can use coolTerm successfully.

Toolchain path: /Users/hongfei/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
Python requirements from /Users/hongfei/esp/esp-idf/requirements.txt are satisfied.
Flashing binaries to serial port cu.SLAB_USBtoUART (app at offset 0x10000)...
esptool.py v2.5.1
Serial port cu.SLAB_USBtoUART
Traceback (most recent call last):
  File "/Users/hongfei/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2853, in <module>
    _main()
  File "/Users/hongfei/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2846, in _main
    main()
  File "/Users/hongfei/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2553, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "/Users/hongfei/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 213, in __init__
    self._port = serial.serial_for_url(port)
  File "/Library/Python/2.7/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/Library/Python/2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port cu.SLAB_USBtoUART: [Errno 2] No such file or directory: 'cu.SLAB_USBtoUART'
make: *** [flash] Error 1

//Detailed problem description goes here.

### Expected Behavior

make flash successfully

**Comment by igrr** [comment]
Have you set the port in menuconfig, or by `export ESPPORT=...`? In the first case, please attach your sdkconfig and the output of `make flash V=1`. In the second case, please check that you set the port name as `/dev/cu.SLAB_USBtoUART` and not `cu.SLAB_USBtoUART`.
