### ISSUE TITLE
idf.py fails if project and IDF paths are on different drives on Windows computer (IDFGH-478)

### ISSUE THREAD

**Issue by j-e-f-f-williams** [espressif/esp-idf#2753]
## Environment

- Development Kit:      ESP32-WROOM32 board (unknown vendor)

- Module or chip used:  ESP32-WROOM-32

- IDF version (run ``git describe --tags`` to find it): v3.3-dev-97-gfc1995437

- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0

- Operating System:     Windows 10
- Power Supply:         USB

## Problem Description
- IDF location C:\dev\esp-idf  
- env variable setup correctly and can compile Hello World on example on C:
- project location D:\projects\TrackDAQ
- idf.py build completes with error

### Expected Behavior
- no errors

### Actual Behavior
following python error:

Project build complete. To flash, run this command:
Traceback (most recent call last):
  File "C:\dev\esp-idf\tools\idf.py", line 523, in <module>
    main()
  File "C:\dev\esp-idf\tools\idf.py", line 519, in main
    print_closing_message(args)
  File "C:\dev\esp-idf\tools\idf.py", line 371, in print_closing_message
    print_flashing_message("Project", "project")
  File "C:\dev\esp-idf\tools\idf.py", line 364, in print_flashing_message
    os.path.relpath("%s/components/esptool_py/esptool/esptool.py" % os.environ["IDF_PATH"]),
  File "C:\Python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive d:

### Steps to repropduce

1. install IDF and IDF tools on C:
2. copy esp-idf\examples\get-started\hello_world to directory on D:
3. execute 'idf.py build' in D: based hellow_world example directory
4. wait for message

### Code to reproduce this issue
No code - build issue

## Debug Logs
[41/43] Linking C static library bootloader_support\libbootloader_support.a
[42/43] Linking C executable bootloader.elf
[43/43] Generating bootloader.bin
esptool.py v2.6-beta1
[734/734] Generating hello-world.bin
esptool.py v2.6-beta1

Project build complete. To flash, run this command:
Traceback (most recent call last):
  File "C:\dev\esp-idf\tools\idf.py", line 523, in <module>
    main()
  File "C:\dev\esp-idf\tools\idf.py", line 519, in main
    print_closing_message(args)
  File "C:\dev\esp-idf\tools\idf.py", line 371, in print_closing_message
    print_flashing_message("Project", "project")
  File "C:\dev\esp-idf\tools\idf.py", line 364, in print_flashing_message
    os.path.relpath("%s/components/esptool_py/esptool/esptool.py" % os.environ["IDF_PATH"]),
  File "C:\Python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive d:

**Comment by projectgus** [comment]
Hi @j-e-f-f-williams ,

Thanks for being patient while someone got back to you about this. A fix has been merged for this issue and should be pushed to GitHub soon.


Angus
