### ISSUE TITLE
Error cp65001 in idf.py (IDFGH-1006)

### ISSUE THREAD

**Issue by raldone01** [espressif/esp-idf#3334]
## Environment

- IDF version master a20d02b7f196c407bc9f39b781e31a0a4f665968
- Build System:         CMake
- Operating System:  Windows

## Problem
Using ctrl+t and ctrl+f or ctrl+t and ctrl+a in the idf.py monitor correctly builds the project. The function get_default_serial_port crashes the script.
```
Traceback (most recent call last):
  File "C:/Users/_/Desktop/projects/c_esp32clock/cmake-build-debug/esp_deps-src/
idf2.py", line 12, in <module>
    foo.main()
  File "C:/esp32deps/v3.2/esp-idf/tools/idf.py", line 516, in main
    execute_action(actions[0], actions[1:])
  File "C:/esp32deps/v3.2/esp-idf/tools/idf.py", line 510, in execute_action
    function(action, args)
  File "C:/esp32deps/v3.2/esp-idf/tools/idf.py", line 259, in flash
    esptool_args = _get_esptool_args(args)
  File "C:/esp32deps/v3.2/esp-idf/tools/idf.py", line 243, in _get_esptool_args
    args.port = get_default_serial_port()
  File "C:/esp32deps/v3.2/esp-idf/tools/idf.py", line 427, in get_default_serial
_port
    print ("Choosing default port %s (use '-p PORT' option to set a specific ser
ial port)" % ports[0])
LookupError: unknown encoding: cp65001
```
## Possible solution
Converting the unicode string in ports[0] to ascii fixed the issue.
https://github.com/espressif/esp-idf/blob/a20d02b7f196c407bc9f39b781e31a0a4f665968/tools/idf.py#L472
Fixed:
``` python
print ("Choosing default port %s (use '-p PORT' option to set a specific serial port)" % ports[0].encode('ascii', 'ignore'))
```

**Comment by projectgus** [comment]
Hi @raldone01 ,

Thanks for the report and the suggested fix. The fix will be merged to master shortly.

Angus
