### ISSUE TITLE
Exception when invoking spi_device_transmit 

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#334]
I have an application that sends data outbound through SPI.   After having sent a few bytes, the ESP32 crashes with the following GDB output:
```
Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x40082f37  PS      : 0x00060833  A0      : 0x800e8494  A1      : 0x3ffb8c30  
A2      : 0xe67ec000  A3      : 0x3ffb8c80  A4      : 0xe67ec048  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000003  A8      : 0x80082f34  A9      : 0x3ffb8c10  
A10     : 0xe67ec048  A11     : 0x00060820  A12     : 0x3ffb8b84  A13     : 0x00000000  
A14     : 0x00000003  A15     : 0xff000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xe67ec038  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffc  

Backtrace: 0x40082f37:0x3ffb8c30 0x400e8494:0x3ffb8c70 0x400e84fe:0x3ffb8cb0 0x400e6ece:0x3ffb8ce0 0x400e9bb0:0x3ffb8d50 0x400ea725:0x3ffb8d70 0x400e9cdf:0x3ffb8d90 0x400e9d08:0x3ffb8db0 0x400ea67c:0x3ffb8dd0 0x400e9a5d:0x3ffb8e00 0x400e9a7c:0x3ffb8e20 0x400e9ac9:0x3ffb8e40 0x400e6f30:0x3ffb8e60


Remote debugging using /dev/ttyUSB0
0x40082f37 in xQueueGenericSend (xQueue=0xe67ec000, pvItemToQueue=0x3ffb8c80, xTicksToWait=4294967295, xCopyPosition=0) at /home/kolban/esp32/esptest/esp-idf/components/freertos/./queue.c:742
742				if( ( pxQueue->uxMessagesWaiting < pxQueue->uxLength ) || ( xCopyPosition == queueOVERWRITE ) )
(gdb) bt
#0  0x40082f37 in xQueueGenericSend (xQueue=0xe67ec000, pvItemToQueue=0x3ffb8c80, xTicksToWait=4294967295, xCopyPosition=0) at /home/kolban/esp32/esptest/esp-idf/components/freertos/./queue.c:742
#1  0x400e8494 in spi_device_queue_trans (handle=0x30203030, trans_desc=0x3ffb8cf0, ticks_to_wait=4294967295) at /home/kolban/esp32/esptest/esp-idf/components/driver/./spi_master.c:678
#2  0x400e84fe in spi_device_transmit (handle=0x30203030, trans_desc=0x3ffb8cf0) at /home/kolban/esp32/esptest/esp-idf/components/driver/./spi_master.c:699
#3  0x400e6ece in msg_comms_cb (u8x8=<optimized out>, msg=<optimized out>, arg_int=128 '\200', arg_ptr=0x3ffb4040 <buf>) at /home/kolban/esp32/esptest/apps/workspace/u8g2/main/./test_SSD1306.c:194

```
 I configure the SPI as follows:

```
spi_bus_config_t bus_config;
bus_config.sclk_io_num   = PIN_CLK; // CLK
bus_config.mosi_io_num   = PIN_MOSI; // MOSI
bus_config.miso_io_num   = -1; // MISO
bus_config.quadwp_io_num = -1; // Not used
bus_config.quadhd_io_num = -1; // Not used
ESP_LOGI(tag, "... Initializing bus.");
ESP_ERROR_CHECK(spi_bus_initialize(HSPI_HOST, &bus_config, 1));


spi_device_interface_config_t dev_config;
dev_config.address_bits     = 0;
dev_config.command_bits     = 0;
dev_config.dummy_bits       = 0;
dev_config.mode             = 0;
dev_config.duty_cycle_pos   = 0;
dev_config.cs_ena_posttrans = 0;
dev_config.cs_ena_pretrans  = 0;
dev_config.clock_speed_hz   = 10000;
dev_config.spics_io_num     = PIN_CS;
dev_config.flags            = 0;
dev_config.queue_size       = 200;
dev_config.pre_cb           = NULL;
dev_config.post_cb          = NULL;
ESP_LOGI(tag, "... Adding device bus.");
ESP_ERROR_CHECK(spi_bus_add_device(HSPI_HOST, &dev_config, &handle));
```

In an effort to reduce variables while debugging I changed my code to always transmit only 1 byte of data using:

```
char data[1];
data[0] = 0;
spi_transaction_t trans_desc;
trans_desc.address   = 0;
trans_desc.command   = 0;
trans_desc.flags     = 0;
trans_desc.length    = 1*8;
trans_desc.rxlength  = 0;
trans_desc.tx_buffer = data;
trans_desc.rx_buffer = NULL;

ESP_LOGI(tag, "... Transmitting %d bytes.", arg_int);
spi_device_transmit(handle, &trans_desc);
```

The crash doesn't happen on the first send but appears to happen after about a dozen or more sends.

**Comment by nkolban** [comment]
It turned out that I was stepping on storage I didn't own in another (unrelated) part of my application ... I was thus corrupting ESP32-IDF data.
