### ISSUE TITLE
idf.py incorrect execution sequence (IDFGH-1710)

### ISSUE THREAD

**Issue by no1seman** [espressif/esp-idf#3948]
## Environment

- Development Kit:  ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v4.1
- Module or chip used: ESP32-WROVER-B
- IDF version: v4.1-dev-58-g02c7c3885
- Build System: CMake
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System: Linux
- Power Supply:  USB|external 5V&Battery

## Problem Description
'idf.py build flash monitor' executes 'flash' task firstly, then - 'monitor' and finally 'build'

### Expected Behavior
'idf.py build flash monitor' must firstly execute 'build', then 'flash' and finally 'monitor'
### Actual Behavior
'idf.py build flash monitor' executes 'flash' task firstly, then - 'monitor' and finally 'build'
### Steps to repropduce
simply run 'idf.py build flash monitor'

## Debug Logs

```
user@ubuntudev:~/esp/mqtt_bug$ idf.py build flash monitor
Checking Python dependencies...
Python requirements from /home/user/esp/esp-mdf/esp-idf/requirements.txt are satisfied.
Executing action: flash
Choosing default port /dev/ttyUSB0 (use '-p PORT' option to set a specific serial port)
Traceback (most recent call last):
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 1345, in <module>
    main()
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 1260, in main
    cli(prog_name=PROG)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 900, in execute_tasks
    task.run(ctx, global_args, task.action_args)
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 563, in run
    self.callback(self.name, context, global_args, **action_args)
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 356, in flash
    esptool_args = _get_esptool_args(args)
  File "/home/user/esp/esp-mdf/esp-idf/tools/idf.py", line 334, in _get_esptool_args
    with open(os.path.join(args.build_dir, "flasher_args.json")) as f:
IOError: [Errno 2] No such file or directory: '/home/user/esp/mqtt_bug/build/flasher_args.json'

```

**Comment by projectgus** [comment]
Hi @no1seman ,

Thanks for reporting. A regression in `idf.py` dependency tracking was merged to master yesterday. Will fix ASAP.

In the meantime you can `git checkout 691b81ec25c859e83f509ba2df151337b2cfddb0` to get a version (also from yesterday) where this bug is not present.
