### ISSUE TITLE
espcoredump broken pipe

### ISSUE THREAD

**Issue by forthlightning** [espressif/esp-idf#409]
Hi I am trying to use espcoredump, but I am getting a broken pipe issue. 

```
python $COREDUMP_PATH/espcoredump.py info_corefile -t b64 -c coredump.dat build/my_thing.elf

espcoredump.py v0.1-dev
===============================================================
==================== ESP32 CORE DUMP START ====================

================== CURRENT THREAD REGISTERS ===================
/Users/ivan/e/ESPTools/crosstool-NG/.build/src/gdb-7.10/gdb/findvar.c:290: internal-error: struct value *value_of_register_lazy(struct frame_info *, int): Assertion `frame_id_p (get_frame_id (frame))' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]
/Users/ivan/e/ESPTools/crosstool-NG/.build/src/gdb-7.10/gdb/findvar.c:290: internal-error: struct value *value_of_register_lazy(struct frame_info *, int): Assertion `frame_id_p (get_frame_id (frame))' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]
GDB/MI command failed (None / None)!

==================== CURRENT THREAD STACK =====================
Traceback (most recent call last):
  File ".../esp-idf/components/espcoredump/espcoredump.py", line 1106, in <module>
    main()
  File ".../esp-idf/components/espcoredump/espcoredump.py", line 1101, in main
    operation_func(args)
  File ".../esp-idf/components/espcoredump/espcoredump.py", line 1009, in info_corefile
    p.stdin.write("-interpreter-exec console \"bt\"\n")
IOError: [Errno 32] Broken pipe
```

**Comment by nkolban** [comment]
What is in "coredump.dat"?

**Comment by forthlightning** [comment]
```
+CUAAA4AAAB8AQAA
2N/8P8Dc/D/M3/w/
kN78P2Df/D/kpwEAICT8PyAk/D/Y3/w/GCT8PxQAAACkqvw/pKr8P9jf/D8AAAAA
BQAAANDb/D9zZG1fcmVhZGVyX3Rhc2sA////f8zf/D8BAAAAIA4GAAUAAABljp+R
BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADH2nw=
p9z8PwOSAEA2CAYAJEcIgIDd/D+IAAAAiAAAABAAAAD/////AAAAAOX///80Ivw/
AQAAACQAAAAkAAAACAAAAP////8AAAAA/////wUAAAABAAAAAAAAAEnDAEBrwwBA
/////wgAAAD/////vA8IQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAOIJAAAAAAAAph1APwAAAACaNQiAoN38P2Nvbm4AAAAA
rBAIQPC/AEAwDwYALEMIgMAWCIDQ3fw/BJz+P5wlQD8EnP4/8L8AQDAJBgAsQwiA
nCVAPwAAAAAAAAAAAAAAAGIXCIAQ3vw/BJz+PwEAAACQBfw/AAAAAAEAAAAAAAAA
AAAAAAEAAAABAAAAEwAAAFSc/j8AAAAAAAAAAAwAAACl9A2AQN78P/An/D8jAAYA
rBAIQKxLDkAwAAYANCEOgAEAAAABAAAAAAD/AAAAAP+HGAiAYN78P9bfnbQqSgUA
IAAGAAaoAQALAAAAAgAAAGy8AICA3vw/WOD8P8De/D8oQAiAIMn8PwMAAAAjAAYA
UxgAgKDe/D9Y4Pw/wN78PwAAAAAW3/w/AwAAAAAAAABIIA6AwN78PwAAAAAAAAAA
AAAAAMDS/D8jCQUAAAAAAAAAAADw3vw/AwAAAAAAAMHoAwAA8N78PwAAAMG+pQEA
yKr8PwAAAADkqvw/AAAAAAAAAABg3/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAQADAADAAAAAwAAAKAmv1gAAADBAwAAAAAAAAAAAAAA
AAMEAAwAArAqAAAAAAAAwVwp/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABs3/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
aKD+P2Cf/j9coP4/
YJ/+P/Cf/j+xqQEADCT8Pwwk/D9ooP4/BCT8PxUAAADk4fw/5OH8P2ig/j8AAAAA
BAAAAGCc/j9tZXNzYWdlX3JvdXRlcl8A////f1yg/j8AAAAAIAIGAAwAAAD1ITJQ
BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPo1A=
AAAAAIs5CIAgAgYAAAAAAAAAAADAn/4/AAAAAAAAAAAAAAAAyaUBACACBgDIsgEA
6AMAAMCf/j8AAAAAAAAAAAji/D8AAAAAAQAAAAUAAAAAAAAA8J/+PwAAAAAAAAAA
AwAAAJ0mv1gAAADBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD8n/4/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
yMr8P1DJ/D+8yvw/
UMn8P1DK/D/MRg4ovCP8P7wj/D/Iyvw/tCP8PxkAAADxDKXcu7rgX8jK/D8AAAAA
AAAAAIDF/D9JRExFACbTzHOyOI6ymecAAAAAALzK/D8AAAAAIQAGAAMAAADymnZp
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYsDo=
rBAIQIgYDUAwBAYAJEcIgBDK/D8IAAAAAQAAACMCBgDIyvw/AQAAAAAAAAB4Ivw/
8Mn8PwAAAAAgBAYAIAcGAKbSAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAK0SCECm0gAA2FIIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACAHBgCm0gAAAQAAAAAAAAAAAAAAMMr8PwAAAAAAAAAA
IwIGAMjK/D8BAAAAAAAAAAAAAABQyvw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXMr8PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
fBn9PzAY/T9wGf0/
MBj9PxAZ/T8LqAEA7A39PwTE/D98Gf0/oCP8PwcAAABoEP0/aBD9P3wZ/T9gEP0/
EgAAAHQR/T90aVQAxF/P0gVv1LIIER8A////f3AZ/T8AAAAAIAAGAAcAAACr0T3r
EgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAHy//j8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOcJU=
AAAAAIs5CIAgAAYAAAAAADhLEICQGP0/GGX8P+AY/T8AAAAAp6cBAAAAAAAAAAAA
ZAAAAAEAAAAAAAAAAAAAAIwQ/T8AAAAAAQAAAHgFAABn2g+AwBj9Pxhl/D/gGP0/
Z9oPgMAY/T8YZfw/4Bj9P2QAAACnpwEA9v///wEAAAAAAAAA4Bj9P+x0EEAAAAAA
IEoQQAAAAAABAAAAAAAAAAAAAAAQGf0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwZ/T8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
5A39PxAN/T/YDf0/
EA39P3AN/T8aqAEA/Kn+P4QZ/T/kDf0/oCP8PxQAAAD0/Pw/9Pz8P+QN/T8AAAAA
BQAAANz9/D9tYW5hZ2VfY29ubmVjdGkA////f9gN/T8AAAAAIA0GAAYAAAAGHJnL
BQAAAAAAAAAwm/4/AAAAAAAAAAAwYRBAAAAAAAAAAAALAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAFhR/z8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgNg4=
AAAAAJRGCIAgDQYAQgAAAAAAAABQDf0/AAAAAAAAAAB0/fw/AAAAACT9/D8BAAAA
AAAAAHAN/T8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAB8Df0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA=
9Kn+P4Co/j/oqf4/
gKj+P4Cp/j8nqAEAXNT8P+wN/T/0qf4/oCP8PxQAAADadCKX911fEfSp/j8AAAAA
BQAAAOyh/j9wdWJsaXNoZXJfdGFzawAA////f+ip/j8AAAAAIAIGAA0AAABoYA0T
BQAAAAAAAACoT/8/AAAAAAAAAAAwYRBAAAAAAAAAAAAMAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8QUP8/SB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADINP8=
AAAAAJRGCIAgAgYAnacBAAAAAADAqP4/AAAAAGwM/D9kAAAARKn+P8j8/D8GAAAA
AAAAAICp/j8AAAAAAAAAAAAAAAAAACDAMAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAFNvbFNlbnNlQzJEVFNUMDAxAAAAAAAAAAAAAADkDPw/nCa/WAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjKn+PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
VNT8P2DT/D9I1Pw/
YNP8P+DT/D+wrQEA6L/+P/yp/j9U1Pw/oCP8PxgAAAAUkvw/FJL8P1TU/D8Mkvw/
AQAAAEzM/D9UbXIgU3ZjAJJNoP+QlOkAAAAAAEjU/D8AAAAAIAsGAAQAAADEYKmW
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2p30=
AAAAAEpRCIAgCwYAAAAAAAAAAACw0/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
NocBAPzD/D8BAAAAAAAAAAAAAADg0/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOzT/D8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
4L/+P7DV/j981v4/
sNX+PxDW/j/kjwIAqCP8P1zU/D/gv/4/oCP8Pw8AAAAAAAAAAAAAAOC//j8AAAAA
CgAAAIDG/j9tcXR0X2NsaWVudF9sb28A////f3zW/j8AAAAAIAAGABAAAAAAAAAA
CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=
AAAAAJRGCIAgAAYAAAAAAAAAAADw1f4/AAAAAAAAAAAjCwYA4L/+PwEAAAAAAAAA
AAAAABDW/j8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAc1v4/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
/MP8PwDD/D/ww/w/
AMP8P5DD/D8GqAEAhBn9P6gj/D/8w/w/oCP8PxgAAABuxNVwoRdtifzD/D8AAAAA
AQAAAPSz/D9tYWluADQ6Yu0eSWsffe0AAAAAAPDD/D8AAAAAIAsGAAIAAACe3mpW
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxPhg=
AAAAAJRGCIAgCwYABQAAAJEQDYBAw/w/////fwAQAAAAEAAAAAAAAAoAAAAAAAAA
AAAAAHDD/D8AAAAAAAAAAP///38AAAAAAAAAAAAAAAAjAAYAVNT8PwEAAAAAAAAA
AAAAAJDD/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACcw/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
YPz9PxCH/j8EiP4/
EIf+P6CH/j/iJPoxbCn9P3iy/D9g/P0/RCP8PwQAAACU+/0/lPv9P2D8/T+M+/0/
FQAAAAiA/j9wbVQAx0OIjQiG+70lfl8A////fwSI/j8AAAAAIA0GAAoAAABHiwCp
FQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIs0=
AAAAAIs5CIAgDQYA2FIIQAAAAABwh/4/SEf8P+BgQD8AAAAAgaUBAEhH/D/gYEA/
/////wAAAAAAAAAAAAAAALj7/T8AAAAAAQAAAAAAAAAAAAAAoIf+PwAAAAAAAAAA
BgAAAAAAAAAAAAAAAAAAAEhI/D/wAAAASEf8PwAAACAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACsh/4/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA==
ZCn9P0Ao/T9YKf0/
QCj9P/Ao/T+9b7Z+IJT+P2j8/T9kKf0/RCP8PwUAAAAsG/0/LBv9P2Qp/T8kG/0/
FAAAAFwh/T9ldmVudFRhc2sAkoWYJfoAAAAAAFgp/T8AAAAAIA0GAAgAAACVBSs9
FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAABCb/j8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADBxsA=
AAAAAIs5CIAgDQYAAAAAAAAAAACgKP0/AAAAAAAAAAAAAAAAhKUBACMNBQAAAAAA
/////6Ao/T8AAAAAAAAAAFAb/T8AAAAAAQAAAAAAAAAAAAAA8Cj9PwAAAAAAAAAA
BQAAAFNvbFNlbnNlAKWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlCPCfwj1ZSMiBsgEA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwo/T8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
GJT+PxCT/j8MlP4/
EJP+P6CT/j8o/hmHuCz9P2wp/T8YlP4/RCP8PwMAAABs/v0/bP79PxiU/j9k/v0/
FgAAABCI/j9ydFQAMCwkLcXthI+f+xEA////fwyU/j8AAAAAIAIGAAsAAAC/G1C5
FgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4Fpk=
AAAAAIs5CIAgAgYAAAAAAAAAAABwk/4/fHH8P9lw/D8AAAAA/aUBACMABQAAAAAA
/////3CT/j98cfw/2XD8P5D+/T8AAAAAAQAAAEiD/D8AAAAAoJP+PwAAAAAAAAAA
NHH8PwAAAAAAAAAAAAAAAIAX/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACsk/4/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
sCz9P6BW/T+oV/0/
oFb9P0BX/T/J3HfSTCP8PyCU/j+wLP0/RCP8PwIAAAA8Mf0/PDH9P7As/T80Mf0/
FwAAAKw3/T9wcFQASn9rfaVdXCCOeH8AAAAAAKhX/T8AAAAAIAIGAAkAAABxYQTP
FwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADiUzk=
AAAAAIs5CIAgAgYAWEj8PwAAAAAAV/0/kHj8P1hI/D8AAAAA3qcBAKISKgZYSPw/
/////wBX/T+QePw/WEj8P2Ax/T8AAAAAAQAAABAAAAAAAAAAQFf9PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACUePw/GAAAAB9SCUD0dvw/
AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAATFf9PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
cLL8P4Cx/D9ksvw/
gLH8PwCy/D9zNUEcaPz9P0wj/D9wsvw/RCP8PwEAAAD4rPw/+Kz8P3Cy/D/wrPw/
GAAAACit/D9pcGMwAPMlMKPOvdU42gIAAAAAAGSy/D8AAAAAIAAGAAEAAAA79kJO
GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIf8P4CH/D/oh/w/
AAAAAAAAAAABAAAAAAAAALCeQD8AAAAASB0AQAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAshss=
AAAAAIs5CIAgAAYAAAAAAAAAAADgsfw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
/////wAAAAAAAAAAAAAAAByt/D8AAAAAAQAAAAAAAAAAAAAAALL8PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAPoKCIAAPP4/NCP8P+wl/D8AAAAAAAAAAAyy/D8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by nkolban** [comment]
I just noticed ... it looks like you are using a custom build of the toolchain.  I have been using the distributed binaries of the tool chain found here ...http://esp-idf.readthedocs.io/en/latest/linux-setup.html#step-1-download-binary-toolchain-for-the-esp32

It may be that there are features of the coredump technology that are specific to this downloadable version of the code ... or maybe specific compilation flags or feature flags were enabled.

**Comment by forthlightning** [comment]
New toolchain seems to have cleared up my initial issue so I am not sure if this worked. So cheers once again Neil! 

I will close when I test the coredump.

How did you tell that I was using an old toolchain? I am pretty sure I downloaded this precompiled from a link on the github readme. 

@espressif folks, is there a change I can watch for in the IDF when a new toolchain comes out?

**Comment by forthlightning** [comment]
after updating the toolchain I am seeing the same issue.

**Comment by gerekon** [comment]
@forthlightning, It seems to be the same issue as described here https://github.com/espressif/esp-idf/issues/321.
Please, see my explanation and workaround (using 'dbg_corefile' command of core dump script) in that topic.
Let me know if you have further problems.

**Comment by forthlightning** [comment]
Ah it looks like that opens up fine. Thanks! Now to learn how to gdb...

**Comment by FayeY** [comment]
Hi forthlightning, is this problem solved? Can we close this issue?

**Comment by forthlightning** [comment]
yup, this looks to be all squared away!
