### ISSUE TITLE
ldgen fails when CONFIG_LWIP_IRAM_OPTIMIZATION is enabled

### ISSUE THREAD

**Issue by m-bruck** [espressif/esp-idf#5740]
- Development Kit: none
- Module or chip used: ESP32
- IDF version v4.1-rc
- Build System: idf.py
- Compiler version 2020r2
- Operating System: Windows, ESP Command Prompt
- Using an IDE?: No

When enabling CONFIG_LWIP_IRAM_OPTIMIZATION the linker script generation ldgen fails:

full [sdkconfig](https://github.com/espressif/esp-idf/files/5084562/sdkconfig.txt)

[745/747] Generating ld/esp32.project.ld
FAILED: esp-idf/esp32/ld/esp32.project.ld
cmd.exe /C "cd /D <...>\vc\proj-fw-esp32\fwesp32\build\esp-idf\esp32 && <...>\esp-idf-tools\python_env\idf4.1_py3.7_env\Scripts\python.exe <...>/esp-idf-v4.1-rc/tools/ldgen/ldgen.py --config <...>/vc/proj-fw-esp32/fwesp32/sdkconfig --fragments <...>/esp-idf-v4.1-rc/components/xtensa/linker.lf    <...>/esp-idf-v4.1-rc/components/esp_ringbuf/linker.lf <...>/esp-idf-v4.1-rc/components/spi_flash/linker.lf <...>/esp-idf-v4.1-rc/components/espcoredump/linker.lf <...>/esp-idf-v4.1-rc/components/esp32/linker.lf       <...>/esp-idf-v4.1-rc/components/esp32/ld/esp32_fragments.lf   <...>/esp-idf-v4.1-rc/components/soc/linker.lf       <...>/esp-idf-v4.1-rc/components/esp_event/linker.lf   <...>/esp-idf-v4.1-rc/components/esp_wifi/linker.lf    <...>/esp-idf-v4.1-rc/components/lwip/linker.lf      <...>/esp-idf-v4.1-rc/components/log/linker.lf <...>/esp-idf-v4.1-rc/components/heap/linker.lf        <...>/esp-idf-v4.1-rc/components/freertos/linker.lf    <...>/esp-idf-v4.1-rc/components/newlib/newlib.lf    <...>/esp-idf-v4.1-rc/components/app_trace/linker.lf   <...>/esp-idf-v4.1-rc/components/esp_gdbstub/linker.lf --input <...>/esp-idf-v4.1-rc/components/esp32/ld/esp32.project.ld.in --output <...>/vc/proj-fw-esp32/fwesp32/build/esp-idf/esp32/ld/esp32.project.ld --kconfig <...>/esp-idf-v4.1-rc/Kconfig --env-file <...>/vc/proj-fw-esp32/fwesp32/build/config.env --libraries-file <...>/vc/proj-fw-esp32/fwesp32/build/ldgen_libraries --objdump <...>/esp-idf-tools/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-objdump.exe"
Traceback (most recent call last):
  File "<...>/esp-idf-v4.1-rc/tools/ldgen/ldgen.py", line 158, in <module>
    main()
  File "<...>/esp-idf-v4.1-rc/tools/ldgen/ldgen.py", line 134, in main
    mapping_rules = generation_model.generate_rules(sections_infos)
  File "<...>\esp-idf-v4.1-rc\tools\ldgen\generation.py", line 352, in generate_rules
    self._create_exclusions(mapping_rules, default_rules, sections_infos)
  File "<...>\esp-idf-v4.1-rc\tools\ldgen\generation.py", line 451, in _create_exclusions
    general_rule.add_exclusion(specific_rule, sections_info)
  File "<...>\esp-idf-v4.1-rc\tools\ldgen\generation.py", line 100, in add_exclusion
    expansions = do_section_expansion(self, section)
  File "<...>\esp-idf-v4.1-rc\tools\ldgen\generation.py", line 84, in do_section_expansion
    expansions = fnmatch.filter(sections_in_obj, section)
  File "<...>\esp-idf-tools\python_env\idf4.1_py3.7_env\lib\fnmatch.py", line 59, in filter
    for name in names:
TypeError: 'NoneType' object is not iterable
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by m-bruck** [comment]
oops duplicate of #5734
