### ISSUE TITLE
Failed to successfully install toolchain and requirements using ./install.sh (IDFGH-3978)

### ISSUE THREAD

**Issue by commcad** [espressif/esp-idf#5862]
Following Espressif Guidance and steps taken below:

1. Extract file "esp32_win32_msys2_environment_and_toolchain-20181001.zip"
2. Copy folder msys32 and paste into D:\ESP_Toolchain\ 
3. Open D:\ESP_Toolchain\msys32 and run "mingw32.exe"
4. mkdir esp
5. cd esp
6. git clone --recursive https://github.com/espressif/esp-idf.git
7. cd esp-idf
8. ./install.sh

Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, o                                                           penocd-esp32, ninja, idf-exe, ccache, dfu-util
Installing xtensa-esp32-elf@esp-2020r2-8.2.0
....................................
....................................
....................................
  The script virtualenv.exe is installed in 'D:\ESP_Toolchain\msys32\home\comcad/.local/bin' which is n                                                 ot on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-scrip                                                 t-location.
Successfully installed configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.1 filelock-3.0.12 importli                                                 b-metadata-1.7.0 importlib-resources-3.0.0 pathlib2-2.3.5 scandir-1.10.0 singledispatch-3.4.0.3 typing-3                                                 .7.4.3 virtualenv-20.0.31 zipp-1.2.0
RuntimeError: missing required file ExePathRefToDest(src=D:/ESP_Toolchain/msys32/mingw32/bin/pythonw.exe                                                 , alias=[]) for creators CPython2Windows
Creating a new Python environment in D:\ESP_Toolchain\msys32\home\comcad/.espressif/python_env/idf4.3_p                                                 y2.7_env
Installing virtualenv
Traceback (most recent call last):
  File "D:/ESP_Toolchain/msys32/home/comcad/esp/esp-idf/tools/idf_tools.py", line 1492, in <module>
    main(sys.argv[1:])
  File "D:/ESP_Toolchain/msys32/home/comcad/esp/esp-idf/tools/idf_tools.py", line 1488, in main
    action_func(args)
  File "D:/ESP_Toolchain/msys32/home/comcad/esp/esp-idf/tools/idf_tools.py", line 1208, in action_insta                                                 ll_python_env
    stdout=sys.stdout, stderr=sys.stderr)
  File "D:/ESP_Toolchain/msys32/mingw32/lib/python2.7/subprocess.py", line 191, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:/ESP_Toolchain/msys32/mingw32/bin/python.exe', '-m', 'virtua                                                 lenv', 'D:\\ESP_Toolchain\\msys32\\home\\comcad/.espressif/python_env/idf4.3_py2.7_env']' returned non-                                                 zero exit status 1

**Comment by commcad** [comment]
This was resolved using one of the several other toolchain installation. Therefore closing.
