### ISSUE TITLE
otatool.py crashes when imported as external python lib (IDFGH-4942)

### ISSUE THREAD

**Issue by etchove** [espressif/esp-idf#6733]
## Problem Description

When importing `otatool.py` as an python lib, it crashes if path is set in main program.

### Code to reproduce this issue

```python
import os
import sys

PORT="COM8"

idf_path = os.environ["IDF_PATH"]
sys.path.append(os.path.join(idf_path, "components", "esptool_py", "esptool"))
sys.path.append(os.path.join(idf_path, "components", "partition_table"))
sys.path.append(os.path.join(idf_path, "components", "app_update"))

import otatool

esp_ota = otatool.OtatoolTarget("COM8")
esp_ota.switch_ota_partition(0)
```

## Debug Logs

```
Traceback (most recent call last):
  File "autoprog_esp.py", line 53, in <module>
    esp_ota.switch_ota_partition(0)
  File "C:/###/esp-idf\components\app_update\otatool.py", line 106, in switch_ota_partition
    sys.path.append(PARTTOOL_DIR)
NameError: name 'PARTTOOL_DIR' is not defined
```

## Proposal

Remove line 106 in `otatool.py` as it is already in path (verified at the top of the file `otatool.py` by try/except).
```python
sys.path.append(PARTTOOL_DIR)
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the proposal, we will look into.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we have a fix now under internal reviewing, and the issue will close automatically once the fix is available on GitHub. Thanks.
