### ISSUE TITLE
`spi_bus_intr_disable` not in IRAM (IDFGH-4992)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#6781]
As expected, it breaks when the spi interrupt runs and a flash operation is taking place.
IDF ver: 1067b2870
<details>
<summary>Backtrace</summary>

```
Re-enable cpu cache.
Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed). 

Core  0 register dump:
PC      : 0x401964dc  PS      : 0x00060034  A0      : 0x8009121e  A1      : 0x3ffbf840  
0x401964dc: spi_bus_intr_disable at /esp-idf/components/driver/spi_master.c:515

A2      : 0x3ffd0614  A3      : 0x3ffc4a98  A4      : 0x27fa57a9  A5      : 0x27fa57a9  
A6      : 0x3ffc4b4c  A7      : 0xffffedff  A8      : 0x80090764  A9      : 0x27fa57a9  
A10     : 0x3ffbb670  A11     : 0x00000001  A12     : 0x27fa57a9  A13     : 0x00000000  
A14     : 0x00060c23  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace:0x401964d9:0x3ffbf840 0x4009121b:0x3ffbf870 0x40086439:0x3ffbf8a0 0x40087121:0x3ffb7540 0x40091ee1:0x3ffb7570
0x401964d9: spi_master_deinit_driver at /esp-idf/components/driver/spi_master.c:291

0x4009121b: spi_intr at /esp-idf/components/driver/spi_master.c:606

0x40086439: _xt_lowint1 at /esp-idf/components/freertos/port/xtensa/xtensa_vectors.S:1105

0x40087121: spi_flash_op_block_func at /esp-idf/components/spi_flash/cache_utils.c:114

0x40091ee1: ipc_task at /esp-idf/components/esp_ipc/ipc.c:62
```

</details>

<details>
<summary>Piece of the coredump</summary>

```
==================== CURRENT THREAD STACK =====================
#0  spi_bus_intr_disable (host=0x3ffd0614) at /esp-idf/components/driver/spi_master.c:515
#1  0x40090764 in bg_disable (lock=0x3ffd0614) at /esp-idf/components/driver/spi_bus_lock.c:720
#2  bg_entry_core (lock=0x3ffd0614) at /esp-idf/components/driver/spi_bus_lock.c:480
#3  spi_bus_lock_bg_entry (lock=0x3ffd0614) at /esp-idf/components/driver/spi_bus_lock.c:720
#4  0x4009121e in spi_intr (arg=0x3ffbb670 <rwip_heap_msg+7248>) at /esp-idf/components/driver/spi_master.c:606
#5  0x4008643c in _xt_lowint1 () at /esp-idf/components/freertos/port/xtensa/xtensa_vectors.S:1105
```

</details>

**Comment by igrr** [comment]
Linking to https://github.com/espressif/esp-idf/issues/6529
