### ISSUE TITLE
ESP32 IDF4.3 MQTT实验中出现下面错误read failed: [Errno 6] Device not configured (IDFGH-5801)

### ISSUE THREAD

**Issue by gaojulong** [espressif/esp-idf#7509]
(685) example_connect: Connecting to iPhone12...
I (685) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
W (695) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
read failed: [Errno 6] Device not configured
Waiting for the device to reconnectException in thread Thread-2:
Traceback (most recent call last):
  File "/Users/apple/.espressif/python_env/idf4.3_py3.7_env/lib/python3.7/site-packages/serial/serialposix.py", line 575, in read
    buf = os.read(self.fd, size - len(read))
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/esp/esp-idf/tools/idf_monitor.py", line 401, in run
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/Users/apple/.espressif/python_env/idf4.3_py3.7_env/lib/python3.7/site-packages/serial/serialposix.py", line 581, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/apple/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/esp/esp-idf/tools/idf_monitor.py", line 187, in _run_outer
    self.run()
  File "/Users/apple/esp/esp-idf/tools/idf_monitor.py", line 412, in run
    self.serial.open()
  File "/Users/apple/.espressif/python_env/idf4.3_py3.7_env/lib/python3.7/site-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "/Users/apple/.espressif/python_env/idf4.3_py3.7_env/lib/python3.7/site-packages/serial/serialposix.py", line 520, in _reconfigure_port
    [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])
termios.error: (22, 'Invalid argument')

**Comment by gaojulong** [comment]
换了一个数据线好了
