### ISSUE TITLE
Cant install ESP Extension on vscode, certificate expired (IDFGH-5936)

### ISSUE THREAD

**Issue by italocjs** [espressif/esp-idf#7624]
## Environment
- Operating System:     [Windows]
- Using an IDE?: [Yes (VSCODE)]
- Power Supply:         [USB]

## Problem Description
Should be simple to fix, just updating a certificate.  But is there a way to install it bypassing the certificate and enabling it later?

### Steps to reproduce

1. Clean install of windows, vscode everything
2. Try to install ESPIDF extension for vscode,  run configure esp-idf extension
3. Fail to install

### Error LOG

```Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Error opening esp-idf version list file. HTTP/HTTPS Request error https://dl.espressif.com/dl/esp-idf/idf_versions.txt
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Error opening esp-idf version list file. HTTP/HTTPS Request error https://dl.espressif.com/dl/esp-idf/idf_versions.txt
Downloading C:\Users\Italo\.espressif\dist\idf-git-2.30.1-win64.zip...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Waiting 8 seconds...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Waiting 16 seconds...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Installing C:\Users\Italo\.espressif\tools\idf-git\2.30.1 ...
Error during ESP-IDF setup

```

**Comment by italocjs** [comment]
I also noticed compilation errors in other issues, related to the certificate,

**Comment by italocjs** [comment]
I found that installing the ESP IDF from the online installer, then selecting the already installed version (while installing it on vscode) works just fine,  just had to deal with another error created by the certificate but that was easy ( #7621 )
