### ISSUE TITLE
Failed to install ESP-IDF by ESP-IDF Windows Installer with an error "SSL: CERTIFICATE_VERIFY_FAILED" (IDFGH-5986)

### ISSUE THREAD

**Issue by takeaship** [espressif/esp-idf#7672]
## Environment
- IDF version (run ``git describe --tags`` to find it):
    - v4.3.1-29-ge493a4c30e
- Operating System:     [Windows]

## Problem Description
Installation by ESP-IDF Windows Installer failed.
The installer was dowloaded from https://dl.espressif.com/dl/esp-idf/?idf=4.4

It seems installation of "ninja-1.10.2-win64" by idf_tools.py failed because of expired certification.
I confirmed Let's encrypt's root certificate 'ISRG Root X1' is already installed to my PC.
In addition, I removerd "DST Root CA X3" from my PC, but it still occurred.

The error log is below.

```
2021-10-11 14:08:16.243   idf_tools.py command: C:\Users\masukawa\.espressif\tools\idf-python\3.8.7\python.exe "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py" --idf-path C:\Users\masukawa\esp32\esp-idf
2021-10-11 14:08:16.243   Installing tools:C:\Users\masukawa\.espressif\tools\idf-python\3.8.7\python.exe "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py" --idf-path C:\Users\masukawa\esp32\esp-idf install
2021-10-11 14:08:18.053   Done, exit code=1
2021-10-11 14:08:18.053   --------
2021-10-11 14:08:18.053   Running command: C:\Users\masukawa\.espressif\tools\idf-python\3.8.7\python.exe "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py" --idf-path C:\Users\masukawa\esp32\esp-idf install
                          Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, openocd-esp32, ninja, idf-exe, ccache, dfu-util
                          Skipping xtensa-esp32-elf@esp-2021r1-8.4.0 (already installed)
                          Skipping xtensa-esp32s2-elf@esp-2021r1-8.4.0 (already installed)
                          Skipping xtensa-esp32s3-elf@esp-2021r1-8.4.0 (already installed)
                          Skipping riscv32-esp-elf@esp-2021r1-8.4.0 (already installed)
                          Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
                          Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
                          Skipping cmake@3.16.4 (already installed)
                          Skipping openocd-esp32@v0.10.0-esp32-20210401 (already installed)
                          Installing ninja@1.10.2
                          Downloading ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          Downloading ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          Downloading ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\Users\masukawa\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          ERROR: Failed to download, and retry count has expired
                          Traceback (most recent call last):
                            File "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py", line 1675, in <module>
                              main(sys.argv[1:])
                            File "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py", line 1671, in main
                              action_func(args)
                            File "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py", line 1322, in action_install
                              tool_obj.download(tool_version)
                            File "C:\Users\masukawa\esp32\esp-idf\tools\idf_tools.py", line 705, in download
                              raise DownloadError()
                          __main__.DownloadError
                          
2021-10-11 14:08:18.054   --------
2021-10-11 14:08:18.054   Message box (OK):
                          Installation has failed with exit code 1
2021-10-11 14:08:20.864   User chose OK.
2021-10-11 14:08:20.885   Message box (Yes/No):
                          Installation log has been created, it may contain more information about the problem.
                          Display the installation log now?
2021-10-11 14:08:22.468   User chose Yes.
2021-10-11 14:08:22.521   CurStepChanged raised an exception.

```

### Expected Behavior
- Finish installation successfully.

### Actual Behavior
- Written in description.

### Steps to reproduce

1. Download ESP-IDF Windows Installer 2.11
2. Clone this repository by the command `git clone -b release/v4.3 --recursive https://github.com/espressif/esp-idf.git`
3. Execute the installer downloaded at step 1. 
4. Select the cloned repository in step 2 as the esp-idf directory, then continue.

**Comment by TakeshiMasukawa** [comment]
I could avoid this problem by editing idf_tools.py as followings.

idf_tools.py line 681-688
From:
```python
                if 'dl.espressif.com' in url:
                    try:
                        ctx = ssl.create_default_context()
                        ctx.load_verify_locations(cadata=ISRG_X1_ROOT_CERT)
                    except AttributeError:
                        # no ssl.create_default_context or load_verify_locations cadata argument
                        # in Python <=2.7.8
                        pass
```
To:
```python
                if 'dl.espressif.com' in url:
                    try:
                        ctx = ssl._create_unverified_context()
                    except AttributeError:
                        # no ssl.create_default_context or load_verify_locations cadata argument
                        # in Python <=2.7.8
                        pass
```

But this is a dirty solution. I hope a fundamental solution.

**Comment by dobairoland** [comment]
I believe that using [the offline version of the installer](https://github.com/espressif/idf-installer) could be used while the certificate issue is not solved.
