### ISSUE TITLE
espcoredump.py - "Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4" (IDFGH-6249)

### ISSUE THREAD

**Issue by vindicatorr** [espressif/esp-idf#7918]
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-C3]
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-346-g7af719e42
- Build System:         [Ninja]
- Compiler version (run ``riscv32-esp-elf-gcc --version`` to find it): esp-2021r2
- Operating System:     [Linux]
- Using an IDE?: [Yes] Visual Studio Code (not using the extension)
- Power Supply:         [USB]

## Problem Description

Cannot process dump

### Expected Behavior
Process the dump?

### Actual Behavior
Does not process the dump

### Steps to reproduce

1. Set up the menuconfig to output dumps
2. Cause a crash in the device app while running "Monitor" which tees out to a file
3. sed to extract the dump base 64 to a separate dump file
4. While the Monitor will produce the same output error, even manually running `IDF_PATH="<pathTo>/esp-idf" python <pathTo>/esp-idf/components/espcoredump/espcoredump.py --chip esp32c3 info_corefile -t b64 -c ./coredump.dmp ./build/<project>.elf` will return the same failure

### Code to reproduce this issue
Not applicable

## Debug Logs
For manually processing with "info_corefile":
```
espcoredump.py v0.4-dev
Traceback (most recent call last):
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 350, in <module>
    temp_core_files = info_corefile()
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 149, in info_corefile
    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 68, in get_core_dump_elf
    loader = ESPCoreDumpFileLoader(args.core, args.core_format == 'b64')
  File "<pathTo>/esp-idf/components/espcoredump/corefile/loader.py", line 564, in __init__
    self._get_core_src(path)
  File "<pathTo>/esp-idf/components/espcoredump/corefile/loader.py", line 582, in _get_core_src
    data = base64.standard_b64decode(line.rstrip(b'\r\n'))
  File "/usr/lib/python3.9/base64.py", line 105, in standard_b64decode
    return b64decode(s)
  File "/usr/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4
```

For manually processing with "info_corefile", but directly with the device (`IDF_PATH="<pathTo>/esp-idf" python <pathTo>/esp-idf/components/espcoredump/espcoredump.py info_corefile build/<project>.elf`):
```
espcoredump.py v0.4-dev
INFO: Invoke parttool to read image.
Traceback (most recent call last):
  File "<pathTo>/esp-idf/components/partition_table/parttool.py", line 365, in <module>
    main()
  File "<pathTo>/esp-idf/components/partition_table/parttool.py", line 358, in main
    op(**common_args)
  File "<pathTo>/esp-idf/components/partition_table/parttool.py", line 193, in _read_partition
    target.read_partition(partition_id, output)
  File "<pathTo>/esp-idf/components/partition_table/parttool.py", line 169, in read_partition
    partition = self.get_partition_info(partition_id)
  File "<pathTo>/esp-idf/components/partition_table/parttool.py", line 151, in get_partition_info
    partition = partition[0]
IndexError: list index out of range
ERROR: parttool script execution failed with err 1
INFO: b'esptool.py v3.2-dev\nSerial port /dev/ttyUSB0\nConnecting....\nDetecting chip type... ESP32-C3\nChip is ESP32-C3 (revision 3)\nFeatures: Wi-Fi\nCrystal is 40MHz\nMAC: 84:f7:03:3b:19:a4\nUploading stub...\nRunning stub...\nStub running...\n3072 (100 %)\n3072 (100 %)\nRead 3072 bytes at 0x8000 in 0.3 seconds (87.0 kbit/s)...\nHard resetting via RTS pin...\nRunning /usr/bin/python <pathTo>/esp-idf/components/esptool_py/esptool/esptool.py --port /dev/ttyUSB0 read_flash 32768 3072 /tmp/tmpiaq8hczk...\n'
ERROR: Error during the subprocess execution
Traceback (most recent call last):
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 350, in <module>
    temp_core_files = info_corefile()
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 149, in info_corefile
    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)
  File "<pathTo>/esp-idf/components/espcoredump/espcoredump.py", line 65, in get_core_dump_elf
    loader = ESPCoreDumpFlashLoader(args.off, args.chip, port=args.port, baud=args.baud)
  File "<pathTo>/esp-idf/components/espcoredump/corefile/loader.py", line 439, in __init__
    self.target = self._load_core_src()
  File "<pathTo>/esp-idf/components/espcoredump/corefile/loader.py", line 164, in _load_core_src
    _header = EspCoreDumpV1Header.parse(coredump_bytes)  # first we use V1 format to get version
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 1020, in _parse
    data = stream_read(stream, self.length, path)
  File "/home/userName/.local/lib/python3.9/site-packages/construct/core.py", line 92, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> tot_len
stream read less than specified amount, expected 4, found 0
```

A sample of the Base-64 dump file (not beginning/ending markers were removed as expected):
```
4F0AAAABBQAAAAAAAAAAAAAAAAA=
f0VMRgEBAQAAAAAAAAAAAAQA8wABAAAAAAAAADQAAAAAAAAAAAAAADQAIAAKACgA
AAAAAA==
BAAAAHQBAAAAAAAAAAAAAIADAACAAwAABgAAAAAAAAA=
...
AADwPwAAAAAAACRAAAAAAAAAHEAAAAAAAAAUQAAAAAAAAFBDEAAAAAAAAAADelIA
FAAAAEgAAABKIAAA
RVNQX0NPUkVfRFVNUF9JTkZPAAA=
AAEFAGU0OGIwNDYwODkzOGI5YzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DAAAAAQAAAClAgAA
RVhUUkFfSU5GTwAA
rIDJPw==
dUEObQ==
```

**Comment by erhankur** [comment]
Closing this since we haven't seen similar issue for a while.
