### ISSUE TITLE
ESP32-C3 : Unable to use coredump tool, crc error (IDFGH-6800)

### ISSUE THREAD

**Issue by HiFiPhile** [espressif/esp-idf#8427]
## Environment

- Development Kit:      [[ESP32-C3-DevKitM-1](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitm-1.html)]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- IDF version (run ``git describe --tags`` to find it):
    v5.0-dev-1599-gb66cc63c41
- Build System:         [df.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
     (crosstool-NG esp-2021r2-patch2) 8.4.0
- Operating System:     [Windows]
- (Windows only) environment type: [ESP Command Prompt].
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

Core panic inside the tick hook callback with following code, want to diagnose the cause with core dump, but failed with checksum error.
```
// in app_main()
esp_register_freertos_tick_hook_for_cpu(cbTick, 0);

static void cbTick(void)
{
    static int lvl = 0;
    gpio_set_level(8, lvl);
    lvl = !lvl;
}
```
* In "espcoredump\corefile\loader.py", line 223, `crc` should be replaced by `checksum`, otherwise this error occured.
```
Traceback (most recent call last):
  File "C:\Tool\esp-idf\python_env\idf5.0_py3.9_env\lib\site-packages\construct\lib\containers.py", line 91, in __getattr__
    return self[name]
KeyError: 'crc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\mcu\esp-idf\components\espcoredump\espcoredump.py", line 352, in <module>
    temp_core_files = dbg_corefile()
  File "e:\mcu\esp-idf\components\espcoredump\espcoredump.py", line 125, in dbg_corefile
    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)
  File "e:\mcu\esp-idf\components\espcoredump\espcoredump.py", line 75, in get_core_dump_elf
    loader.create_corefile(exe_name=args.prog, e_machine=e_machine)
  File "e:\mcu\esp-idf\components\espcoredump\corefile\loader.py", line 239, in create_corefile
    self._validate_dump_file()
  File "e:\mcu\esp-idf\components\espcoredump\corefile\loader.py", line 214, in _validate_dump_file
    self._crc_validate()
  File "e:\mcu\esp-idf\components\espcoredump\corefile\loader.py", line 223, in _crc_validate
    'Invalid core dump CRC %x, should be %x' % (data_crc, self.core_src.crc))  # type: ignore
  File "C:\Tool\esp-idf\python_env\idf5.0_py3.9_env\lib\site-packages\construct\lib\containers.py", line 93, in __getattr__
    raise AttributeError(name)
AttributeError: crc
```
* After the correction, for both UART & USB dump mode crc are incorrect:

**Flash mode**
```
I (343) sleep: Configure to isolate all GPIO pins in sleep state
I (350) sleep: Enable automatic switching of GPIO sleep configuration
I (368) pm: Frequency switching config: CPU_MAX: 80, APB_MAX: 80, APB_MIN: 40, Light sleep: DISABLED
I (368) esp_core_dump_flash: Init core dump to flash
I (372) esp_core_dump_flash: Found partition 'coredump' @ 110000 65536 bytes
E (387) esp_core_dump_flash: Core dump data check failed:
Calculated checksum='1748bad0'
Image checksum='e3c5e008'
```
**UART mode**, dump file is attached
```
Initiating core dump!
I (695) esp_core_dump_uart: Press Enter to print core dump to UART...
I (702) esp_core_dump_uart: Print core dump to uart...
I (708) esp_core_dump_common: Backing up stack @ 0x3fc8f950 and use core dump stack @ 0x3fc903d0
Core dump started (further output muted)
Received   8 kB...
Core dump finished!
Failed to run espcoredump script: Command '['C:\\Tool\\esp-idf\\python_env\\idf5.0_py3.9_env\\Scripts\\python.exe', 'E:\\mcu\\esp-idf\\tools\\idf_monitor_base\\..\\..\\components\\espcoredump\\espcoredump.py', 'info_corefile', '--core', 'C:\\Users\\Mengsk\\AppData\\Local\\Temp\\tmpa55mb5v5', '--core-format', 'b64', 'e:\\mcu\\esp32c3\\linkify_fw\\build\\linkify.elf']' returned non-zero exit status 1.
b'espcoredump.py v0.4-dev\r\nTraceback (most recent call last):\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 350, in <module>\r\n    temp_core_files = info_corefile()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 149, in info_corefile\r\n    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 75, in get_core_dump_elf\r\n    loader.create_corefile(exe_name=args.prog, e_machine=e_machine)\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 239, in create_corefile\r\n    self._validate_dump_file()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 214, in _validate_dump_file\r\n    self._crc_validate()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 222, in _crc_validate\r\n    raise ESPCoreDumpLoaderError(\r\ncorefile.ESPCoreDumpLoaderError: Invalid core dump CRC 18088619, should be 673eb40f\r\n'
```

### Expected Behavior

Dump file is analyzed.

### Actual Behavior

Dump file can't be analyzed with CRC error

### Steps to reproduce

1. build and flash following code
2. Use espcoredump.py to analyze dump

### Code to reproduce this issue

In attachment

## Debug Logs

```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380644
0x40380644: esp_restart_noos_dig at E:/mcu/esp-idf/components/esp_system/esp_system.c:46 (discriminator 1)

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1754
load:0x403ce000,len:0x930
load:0x403d0000,len:0x2d28
entry 0x403ce000
I (35) boot: ESP-IDF v5.0-dev-1599-gb66cc63c41-dirty 2nd stage bootloader
I (35) boot: compile time 10:45:31
I (35) boot: chip revision: 3
I (39) boot.esp32c3: SPI Speed      : 80MHz
I (44) boot.esp32c3: SPI Mode       : DIO
I (48) boot.esp32c3: SPI Flash Size : 2MB
I (53) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (77) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 00100000
I (92) boot: End of partition table
I (96) esp_image: segment 0: paddr=00010020 vaddr=3c020020 size=09080h ( 36992) map
I (110) esp_image: segment 1: paddr=000190a8 vaddr=3fc8ca00 size=02720h ( 10016) load
I (115) esp_image: segment 2: paddr=0001b7d0 vaddr=40380000 size=04848h ( 18504) load
I (125) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=1948ch (103564) map
I (146) esp_image: segment 4: paddr=000394b4 vaddr=40384848 size=08124h ( 33060) load
I (152) esp_image: segment 5: paddr=000415e0 vaddr=50000010 size=00010h (    16) load
I (156) boot: Loaded app from partition at offset 0x10000
I (158) boot: Disabling RNG early entropy source...
I (175) cpu_start: Pro cpu up.
I (183) cpu_start: Pro cpu start user code
I (183) cpu_start: cpu freq: 80000000 Hz
I (183) cpu_start: Application information:
I (186) cpu_start: Project name:     linkify
I (191) cpu_start: App version:      daa1657-dirty
I (196) cpu_start: Compile time:     Feb 18 2022 10:45:09
I (202) cpu_start: ELF file SHA256:  d41dc5b743c4bfb7...
I (208) cpu_start: ESP-IDF:          v5.0-dev-1599-gb66cc63c41-dirty
I (216) heap_init: Initializing. RAM available for dynamic allocation:
I (223) heap_init: At 3FC908A0 len 0002F760 (189 KiB): DRAM
I (229) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (236) heap_init: At 50000020 len 00001FE0 (7 KiB): RTCRAM
I (243) spi_flash: detected chip: generic
I (247) spi_flash: flash io: dio
W (251) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (264) sleep: Configure to isolate all GPIO pins in sleep state
I (271) sleep: Enable automatic switching of GPIO sleep configuration
I (289) pm: Frequency switching config: CPU_MAX: 80, APB_MAX: 80, APB_MIN: 40, Light sleep: DISABLED
I (289) esp_core_dump_uart: Init core dump to UART
I (293) cpu_start: Starting scheduler.
I (298) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (298) gpio: GPIO[7]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (308) gpio: GPIO[8]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (318) sleep: Disable automatic switching of GPIO sleep configuration
Guru Meditation Error: Core  0 panic'ed (Illegal instruction). Exception was unhandled.

Stack dump detected
Core  0 register dump:
MEPC    : 0x42007a5c  RA      : 0x40383588  SP      : 0x3fc8fb10  GP      : 0x3fc8d200
0x42007a5c: cbTick at e:\mcu\esp32c3\linkify_fw\build/../main/main.c:33

0x40383588: esp_vApplicationTickHook at E:/mcu/esp-idf/components/esp_system/freertos_hooks.c:41

TP      : 0x3fc8b004  T0      : 0x7fffffff  T1      : 0x000c4000  T2      : 0x00000003
S0/FP   : 0x00000001  S1      : 0x3fc9075c  A0      : 0x3fc90844  A1      : 0xe7ffffff
A2      : 0x00000fa0  A3      : 0xb81fc000  A4      : 0x3fc9067c  A5      : 0x42007a5c
0x42007a5c: cbTick at e:\mcu\esp32c3\linkify_fw\build/../main/main.c:33

A6      : 0x9c400000  A7      : 0x00000002  S2      : 0x00001881  S3      : 0x00000001
S4      : 0x00000040  S5      : 0x00000000  S6      : 0x3fc8df24  S7      : 0x00000100
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x3fc90748  T4      : 0x00000000  T5      : 0x00000001  T6      : 0xffffffff
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000002  MTVAL   : 0x00000000
0x40380001: _vector_table at ??:?

MHARTID : 0x00000000

3fc8fb10: 0x00000000 0x00000000 0x00000001 0x40386c26 0x00000000 0x00000000 0x00000000 0x00000001
0x40386c26: xTaskIncrementTick at E:/mcu/esp-idf/components/hal/esp32c3/include/hal/cpu_ll.h:35

3fc8fb30: 0x00001881 0x3fc9075c 0x00000001 0x4038562a 0x00000000 0x00000000 0x00000001 0x40381794
0x4038562a: xPortSysTickHandler at E:/mcu/esp-idf/components/freertos/FreeRTOS-Kernel/portable/port_systick.c:168

0x40381794: SysTickIsrHandler at E:/mcu/esp-idf/components/freertos/FreeRTOS-Kernel/portable/port_systick.c:143 (discriminator 1)

3fc8fb50: 0x00001881 0x80000004 0x60002000 0x4038b6ec 0x00000000 0x00000000 0x00000000 0x3fc9075c
0x4038b6ec: _global_interrupt_handler at E:/mcu/esp-idf/components/riscv/interrupt.c:66

3fc8fb70: 0x403801c2 0x00000000 0x60002000 0x403801a6 0x00000001 0x3fc8fb88 0xffffffff 0x3fc939e4
0x403801c2: _interrupt_handler at ??:?

0x403801a6: _interrupt_handler at ??:?

3fc8fb90: 0x3fc939e4 0x00000001 0x3fc8fb9c 0xffffffff 0x3fc9388c 0x3fc9388c 0x00000000 0x3fc8fbb0
3fc8fbb0: 0xffffffff 0x3fc8fbb0 0x3fc8fbb0 0x00000000 0x3fc8fbc4 0xffffffff 0x3fc8fbc4 0x3fc8fbc4
3fc8fbd0: 0x00000000 0x3fc8fbd8 0xffffffff 0x3fc8fbd8 0x3fc8fbd8 0x00000000 0x3fc8fbec 0xffffffff
3fc8fbf0: 0x3fc8fbec 0x3fc8fbec 0x00000000 0x3fc8fc00 0xffffffff 0x3fc8fc00 0x3fc8fc00 0x00000000
3fc8fc10: 0x3fc8fc14 0xffffffff 0x3fc8fc14 0x3fc8fc14 0x00000000 0x3fc8fc28 0xffffffff 0x3fc8fc28
3fc8fc30: 0x3fc8fc28 0x00000000 0x3fc8fc3c 0xffffffff 0x3fc8fc3c 0x3fc8fc3c 0x00000000 0x3fc8fc50
3fc8fc50: 0xffffffff 0x3fc8fc50 0x3fc8fc50 0x00000000 0x3fc8fc64 0xffffffff 0x3fc8fc64 0x3fc8fc64
3fc8fc70: 0x00000000 0x3fc8fc78 0xffffffff 0x3fc8fc78 0x3fc8fc78 0x00000000 0x3fc8fc8c 0xffffffff
3fc8fc90: 0x3fc8fc8c 0x3fc8fc8c 0x00000000 0x3fc8fca0 0xffffffff 0x3fc8fca0 0x3fc8fca0 0x00000000
3fc8fcb0: 0x3fc8fcb4 0xffffffff 0x3fc8fcb4 0x3fc8fcb4 0x00000000 0x3fc8fcc8 0xffffffff 0x3fc8fcc8
3fc8fcd0: 0x3fc8fcc8 0x00000000 0x3fc8fcdc 0xffffffff 0x3fc8fcdc 0x3fc8fcdc 0x00000000 0x3fc8fcf0
3fc8fcf0: 0xffffffff 0x3fc8fcf0 0x3fc8fcf0 0x00000000 0x3fc8fd04 0xffffffff 0x3fc8fd04 0x3fc8fd04
3fc8fd10: 0x00000000 0x3fc8fd18 0xffffffff 0x3fc8fd18 0x3fc8fd18 0x00000000 0x3fc8fd2c 0xffffffff
3fc8fd30: 0x3fc8fd2c 0x3fc8fd2c 0x00000000 0x3fc8fd40 0xffffffff 0x3fc8fd40 0x3fc8fd40 0x00000000
3fc8fd50: 0x3fc8fd54 0xffffffff 0x3fc8fd54 0x3fc8fd54 0x00000000 0x3fc8fd68 0xffffffff 0x3fc8fd68
3fc8fd70: 0x3fc8fd68 0x00000000 0x3fc8fd7c 0xffffffff 0x3fc8fd7c 0x3fc8fd7c 0x00000000 0x3fc8fd90
3fc8fd90: 0xffffffff 0x3fc8fd90 0x3fc8fd90 0x00000000 0x3fc8fda4 0xffffffff 0x3fc8fda4 0x3fc8fda4
3fc8fdb0: 0x00000001 0x3fc8fdb8 0xffffffff 0x3fc926cc 0x3fc926cc 0x00000000 0x3fc8fdcc 0xffffffff
3fc8fdd0: 0x3fc8fdcc 0x3fc8fdcc 0x00000000 0x3fc8fdd8 0x00000000 0x00000000 0x00000000 0x3fc8fdf0
3fc8fdf0: 0xffffffff 0x3fc8fdf0 0x3fc8fdf0 0x00000000 0x3fc8fe04 0xffffffff 0x3fc8fe04 0x3fc8fe04
3fc8fe10: 0x00000001 0x00000001 0x00000000 0x0001ffff 0x00000000 0xb33fffff 0x00000000 0x00000000
3fc8fe30: 0x3fc8fe2c 0x00000000 0x00000000 0x00000000 0x3fc8fe44 0xffffffff 0x3fc8fe44 0x3fc8fe44
3fc8fe50: 0x00000000 0x3fc8fe58 0xffffffff 0x3fc8fe58 0x3fc8fe58 0x00000001 0x00000001 0x00000000
3fc8fe70: 0x0001ffff 0x00000000 0xb33fffff 0x00000000 0x00000000 0x3fc9118c 0x3fc911f4 0x3fc9125c
3fc8fe90: 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x4200f78c 0x00000000
0x4200f78c: _cleanup_r at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/riscv32-esp-elf/src/newlib/newlib/libc/stdio/findfp.c:229

3fc8feb0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc8fed0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc8fef0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000



Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'e:\\mcu\\esp32c3\\linkify_fw\\build\\linkify.elf', '-ex', 'target remote | "C:\\Tool\\esp-idf\\python_env\\idf5.0_py3.9_env\\Scripts\\python.exe" "E:\\mcu\\esp-idf\\tools\\idf_monitor_base\\..\\gdb_panic_server.py" --target esp32c3 "C:\\Users\\Mengsk\\AppData\\Local\\Temp\\tmpgpiiusa7"', '-ex', 'bt']' returned non-zero exit status 1.
b'error starting child process \'"C:\\Tool\\esp-idf\\python_env\\idf5.0_py3.9_env\\Scripts\\python.exe" "E:\\mcu\\esp-idf\\tools\\idf_monitor_base\\..\\gdb_panic_server.py" --target esp32c3 "C:\\Users\\Mengsk\\AppData\\Local\\Temp\\tmpgpiiusa7"\': CreateProcess: No such file or directory\r\nNo stack.\r\n'


Core  0 register dump:
MEPC    : 0x42007a5c  RA      : 0x40383588  SP      : 0x3fc8fb10  GP      : 0x3fc8d200
TP      : 0x3fc8b004  T0      : 0x7fffffff  T1      : 0x000c4000  T2      : 0x00000003
S0/FP   : 0x00000001  S1      : 0x3fc9075c  A0      : 0x3fc90844  A1      : 0xe7ffffff
A2      : 0x00000fa0  A3      : 0xb81fc000  A4      : 0x3fc9067c  A5      : 0x42007a5c
A6      : 0x9c400000  A7      : 0x00000002  S2      : 0x00001881  S3      : 0x00000001
S4      : 0x00000040  S5      : 0x00000000  S6      : 0x3fc8df24  S7      : 0x00000100
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x3fc90748  T4      : 0x00000000  T5      : 0x00000001  T6      : 0xffffffff
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000002  MTVAL   : 0x00000000
MHARTID : 0x00000000

Stack memory:
3fc8fb10: 0x00000000 0x00000000 0x00000001 0x40386c26 0x00000000 0x00000000 0x00000000 0x00000001
3fc8fb30: 0x00001881 0x3fc9075c 0x00000001 0x4038562a 0x00000000 0x00000000 0x00000001 0x40381794
3fc8fb50: 0x00001881 0x80000004 0x60002000 0x4038b6ec 0x00000000 0x00000000 0x00000000 0x3fc9075c
3fc8fb70: 0x403801c2 0x00000000 0x60002000 0x403801a6 0x00000001 0x3fc8fb88 0xffffffff 0x3fc939e4
3fc8fb90: 0x3fc939e4 0x00000001 0x3fc8fb9c 0xffffffff 0x3fc9388c 0x3fc9388c 0x00000000 0x3fc8fbb0
3fc8fbb0: 0xffffffff 0x3fc8fbb0 0x3fc8fbb0 0x00000000 0x3fc8fbc4 0xffffffff 0x3fc8fbc4 0x3fc8fbc4
3fc8fbd0: 0x00000000 0x3fc8fbd8 0xffffffff 0x3fc8fbd8 0x3fc8fbd8 0x00000000 0x3fc8fbec 0xffffffff
3fc8fbf0: 0x3fc8fbec 0x3fc8fbec 0x00000000 0x3fc8fc00 0xffffffff 0x3fc8fc00 0x3fc8fc00 0x00000000
3fc8fc10: 0x3fc8fc14 0xffffffff 0x3fc8fc14 0x3fc8fc14 0x00000000 0x3fc8fc28 0xffffffff 0x3fc8fc28
3fc8fc30: 0x3fc8fc28 0x00000000 0x3fc8fc3c 0xffffffff 0x3fc8fc3c 0x3fc8fc3c 0x00000000 0x3fc8fc50
3fc8fc50: 0xffffffff 0x3fc8fc50 0x3fc8fc50 0x00000000 0x3fc8fc64 0xffffffff 0x3fc8fc64 0x3fc8fc64
3fc8fc70: 0x00000000 0x3fc8fc78 0xffffffff 0x3fc8fc78 0x3fc8fc78 0x00000000 0x3fc8fc8c 0xffffffff
3fc8fc90: 0x3fc8fc8c 0x3fc8fc8c 0x00000000 0x3fc8fca0 0xffffffff 0x3fc8fca0 0x3fc8fca0 0x00000000
3fc8fcb0: 0x3fc8fcb4 0xffffffff 0x3fc8fcb4 0x3fc8fcb4 0x00000000 0x3fc8fcc8 0xffffffff 0x3fc8fcc8
3fc8fcd0: 0x3fc8fcc8 0x00000000 0x3fc8fcdc 0xffffffff 0x3fc8fcdc 0x3fc8fcdc 0x00000000 0x3fc8fcf0
3fc8fcf0: 0xffffffff 0x3fc8fcf0 0x3fc8fcf0 0x00000000 0x3fc8fd04 0xffffffff 0x3fc8fd04 0x3fc8fd04
3fc8fd10: 0x00000000 0x3fc8fd18 0xffffffff 0x3fc8fd18 0x3fc8fd18 0x00000000 0x3fc8fd2c 0xffffffff
3fc8fd30: 0x3fc8fd2c 0x3fc8fd2c 0x00000000 0x3fc8fd40 0xffffffff 0x3fc8fd40 0x3fc8fd40 0x00000000
3fc8fd50: 0x3fc8fd54 0xffffffff 0x3fc8fd54 0x3fc8fd54 0x00000000 0x3fc8fd68 0xffffffff 0x3fc8fd68
3fc8fd70: 0x3fc8fd68 0x00000000 0x3fc8fd7c 0xffffffff 0x3fc8fd7c 0x3fc8fd7c 0x00000000 0x3fc8fd90
3fc8fd90: 0xffffffff 0x3fc8fd90 0x3fc8fd90 0x00000000 0x3fc8fda4 0xffffffff 0x3fc8fda4 0x3fc8fda4
3fc8fdb0: 0x00000001 0x3fc8fdb8 0xffffffff 0x3fc926cc 0x3fc926cc 0x00000000 0x3fc8fdcc 0xffffffff
3fc8fdd0: 0x3fc8fdcc 0x3fc8fdcc 0x00000000 0x3fc8fdd8 0x00000000 0x00000000 0x00000000 0x3fc8fdf0
3fc8fdf0: 0xffffffff 0x3fc8fdf0 0x3fc8fdf0 0x00000000 0x3fc8fe04 0xffffffff 0x3fc8fe04 0x3fc8fe04
3fc8fe10: 0x00000001 0x00000001 0x00000000 0x0001ffff 0x00000000 0xb33fffff 0x00000000 0x00000000
3fc8fe30: 0x3fc8fe2c 0x00000000 0x00000000 0x00000000 0x3fc8fe44 0xffffffff 0x3fc8fe44 0x3fc8fe44
3fc8fe50: 0x00000000 0x3fc8fe58 0xffffffff 0x3fc8fe58 0x3fc8fe58 0x00000001 0x00000001 0x00000000
3fc8fe70: 0x0001ffff 0x00000000 0xb33fffff 0x00000000 0x00000000 0x3fc9118c 0x3fc911f4 0x3fc9125c
3fc8fe90: 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x4200f78c 0x00000000
3fc8feb0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc8fed0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc8fef0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000



ELF file SHA256: d41dc5b743c4bfb7
ELF file SHA256: d41dc5b743c4bfb7

Initiating core dump!
I (695) esp_core_dump_uart: Press Enter to print core dump to UART...
I (702) esp_core_dump_uart: Print core dump to uart...
I (708) esp_core_dump_common: Backing up stack @ 0x3fc8f950 and use core dump stack @ 0x3fc903d0
Core dump started (further output muted)
Received   8 kB...
Core dump finished!
Failed to run espcoredump script: Command '['C:\\Tool\\esp-idf\\python_env\\idf5.0_py3.9_env\\Scripts\\python.exe', 'E:\\mcu\\esp-idf\\tools\\idf_monitor_base\\..\\..\\components\\espcoredump\\espcoredump.py', 'info_corefile', '--core', 'C:\\Users\\Mengsk\\AppDa
[dump.txt](https://github.com/espressif/esp-idf/files/8096052/dump.txt)
ta\\Local\\Temp\\tmp635lox2o', '--core-format', 'b64', 'e:\\mcu\\esp32c3\\linkify_fw\\build\\linkify.elf']' returned non-zero exit status 1.
b'espcoredump.py v0.4-dev\r\nTraceback (most recent call last):\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 350, in <module>\r\n    temp_core_files = info_corefile()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 149, in info_corefile\r\n    core_elf_path, target, temp_files = get_core_dump_elf(e_machine=exe_elf.e_machine)\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\espcoredump.py", line 75, in get_core_dump_elf\r\n    loader.create_corefile(exe_name=args.prog, e_machine=e_machine)\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 239, in create_corefile\r\n    self._validate_dump_file()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 214, in _validate_dump_file\r\n    self._crc_validate()\r\n  File "E:\\mcu\\esp-idf\\components\\espcoredump\\corefile\\loader.py", line 222, in _crc_validate\r\n    raise ESPCoreDumpLoaderError(\r\ncorefile.ESPCoreDumpLoaderError: Invalid core dump CRC b09438d2, should be cfa20ac4\r\n'
```

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
- [x] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [x] coredump (This provides stacks of tasks.)

[dump.zip](https://github.com/espressif/esp-idf/files/8096074/dump.zip)
[main.zip](https://github.com/espressif/esp-idf/files/8096089/main.zip)

**Comment by erhankur** [comment]
@HiFiPhile Sorry for the very late response. Do you still have an issue? I gave a try with the master branch, it looks fine.

**Comment by HiFiPhile** [comment]
I haven't working on C3 for a moment, if I meet it again I will create a new issue.
