### ISSUE TITLE
HTTPS Problems on dl.espressif.com (IDFGH-7085)

### ISSUE THREAD

**Issue by TTsteluk** [espressif/esp-idf#8699]
I have problems installing ESP-IDF acording to ESP-IDF programing guide. There seems to be problem with HTTPS certificate. Please advise. 

```
install.fish  install.sh
(venv3.10mac) MBP-ukasz-2:esp-idf mbppro$ ./install.sh esp32
Detecting the Python interpreter
Checking "python" ...
Python 3.10.4
"python" has been detected
Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, openocd-esp32
Installing xtensa-esp32-elf@esp-2020r3-8.4.0
Using GitHub assets mirror for URL: https://github.com/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz => https://dl.espressif.com/github_assets/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz
Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
WARNING: Failed to download https://dl.espressif.com/github_assets/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
WARNING: Failed to download https://dl.espressif.com/github_assets/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
WARNING: Failed to download https://dl.espressif.com/github_assets/espressif/crosstool-NG/releases/download/esp-2020r3/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz to /Users/mbppro/.espressif/dist/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-macos.tar.gz.tmp
ERROR: Failed to download, and retry count has expired
Traceback (most recent call last):
  File "/Users/mbppro/esp/esp-idf/tools/idf_tools.py", line 1672, in <module>
    main(sys.argv[1:])
  File "/Users/mbppro/esp/esp-idf/tools/idf_tools.py", line 1668, in main
    action_func(args)
  File "/Users/mbppro/esp/esp-idf/tools/idf_tools.py", line 1319, in action_install
    tool_obj.download(tool_version)
  File "/Users/mbppro/esp/esp-idf/tools/idf_tools.py", line 705, in download
    raise DownloadError()
__main__.DownloadError
```

**Comment by dobairoland** [comment]
Hi. The certificates needs to be updated in your computer.

Here is a page explaining the issue and providing some solutions:
https://pages.blog.game-host.org/amazing-tricks-to-fix-urlopen-error-ssl-certificate_verify_failed-certificate-verify-failed/

I recommend Solution 1 or Solution 4 from that page.

An alternative and less convenient solution is to download the failed files with a web browser and placing the tools into `~/.espressif/dist`. Re-running the install script won't need to download those files. This solution works because modern web browsers contain their own set of certificates and if they are kept up to date then can have fresher certificates than the OS.
