### ISSUE TITLE
Backtrace of `abort`ed/`exit`ed tasks don't show on core dumps (IDFGH-7097)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#8706]
## Environment
- Module or chip used:  ESP32
- IDF version: master - 97fb98a91b308d4f4db54d6dd1644117607e9692
- Compiler version: esp-2021r2-patch3 8.4.0 + [new esp-gdb](https://github.com/espressif/binutils-gdb/releases/tag/esp-gdb-v11.1_20220318) (behavior is the same on python2 based esp-gdb as well)

### Expected Behavior
`abort`ed/`exit`ed tasks should have their stack shown correctly like any other task and like it's shown by idf monitor backtrace decoding.

### Steps to reproduce

1. Run code to repro the issue
2. Decode coredump
3. Compare decoded backtrace (which works) to `main` task stack on coredump (which doesn't)

### Code to reproduce this issue

```c
#include <stdlib.h>

void app_main(void)
{
    exit(EXIT_FAILURE);
}
```

## Debug Logs

<details>
<summary>Log + decoded core dump</summary>

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:2124
ho 0 tail 12 room 4
load:0x40078000,len:15484
load:0x40080400,len:3760
0x40080400: _init at ??:?

entry 0x4008060c
I (33) cpu_start: Pro cpu up.
I (33) cpu_start: Starting app cpu, entry point is 0x40081020
0x40081020: call_start_cpu1 at /esp-idf/components/esp_system/port/cpu_start.c:152

I (0) cpu_start: App cpu up.
I (47) cpu_start: Pro cpu start user code
I (47) cpu_start: cpu freq: 160000000 Hz
I (47) cpu_start: Application information:
I (52) cpu_start: Project name:     test_minimal
I (57) cpu_start: App version:      1
I (62) cpu_start: Compile time:     Apr  1 2022 17:00:57
I (68) cpu_start: ELF file SHA256:  860110c87e986694...
I (73) cpu_start: ESP-IDF:          97fb98a-dirty
I (79) heap_init: Initializing. RAM available for dynamic allocation:
I (86) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (92) heap_init: At 3FFB4D20 len 0002B2E0 (172 KiB): DRAM
I (98) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (104) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (111) heap_init: At 4008B714 len 000148EC (82 KiB): IRAM
I (118) spi_flash: detected chip: generic
I (122) spi_flash: flash io: qio
I (126) esp_core_dump_uart: Init core dump to UART
I (131) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.

abort() was called at PC 0x400d4b3b on core 0
0x400d4b3b: syscall_not_implemented_aborts at /esp-idf/components/newlib/syscalls.c:35



Backtrace:0x400819fe:0x3ffb73200x40085189:0x3ffb7340 0x4008a406:0x3ffb7360 0x400d4b3b:0x3ffb73d0 0x400d9393:0x3ffb73f0 0x400d780d:0x3ffb7410 0x400e720c:0x3ffb7430 0x40087e35:0x3ffb7450 
0x400819fe: panic_abort at /esp-idf/components/esp_system/panic.c:403

0x40085189: esp_system_abort at /esp-idf/components/esp_system/esp_system.c:135

0x4008a406: abort at /esp-idf/components/newlib/abort.c:46

0x400d4b3b: syscall_not_implemented_aborts at /esp-idf/components/newlib/syscalls.c:35

0x400d9393: exit at /builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/newlib/newlib/libc/stdlib/exit.c:64

0x400d780d: app_main at /test_minimal/main/test_minimal.c:7

0x400e720c: main_task at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/port_common.c:127 (discriminator 2)

0x40087e35: vPortTaskWrapper at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:141





ELF file SHA256: 860110c87e986694

Initiating core dump!
I (166) esp_core_dump_uart: Press Enter to print core dump to UART...
I (173) esp_core_dump_uart: Print core dump to uart...
Core dump started (further output muted)
Received  12 kB...
Core dump finished!
espcoredump.py v0.4-dev
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3ffb74e0, name: 'main', GDB name: 'process 1073444064'

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x400d759f
epc2           0x0
epc3           0x0
epc4           0x0
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x0
eps5           0x0
eps6           0x0
pc             0x40081a01          0x40081a01 <panic_abort+21>
lbeg           0x4000c349          1073791817
lend           0x4000c36b          1073791851
lcount         0x0                 0
sar            0x10                16
ps             0x60a20             395808
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x8008518c          -2146938484
a1             0x3ffb7320          1073443616
a2             0x3ffb736b          1073443691
a3             0x3ffb7398          1073443736
a4             0xa                 10
a5             0x8                 8
a6             0x0                 0
a7             0x0                 0
a8             0x0                 0
a9             0x1                 1
a10            0x3ffb7369          1073443689
a11            0x3ffb7369          1073443689
a12            0x0                 0
a13            0x0                 0
a14            0x0                 0
a15            0x0                 0

==================== CURRENT THREAD STACK =====================
#0  0x40081a01 in panic_abort (details=0x3ffb736b \"abort() was called at PC 0x400d4b3b on core 0\") at /esp-idf/components/esp_system/panic.c:403
#1  0x4008518c in esp_system_abort (details=0x3ffb736b \"abort() was called at PC 0x400d4b3b on core 0\") at /esp-idf/components/esp_system/esp_system.c:135
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

======================== THREADS INFO =========================
  Id   Target Id          Frame 
* 1    process 1073444064 0x40081a01 in panic_abort (details=0x3ffb736b \"abort() was called at PC 0x400d4b3b on core 0\") at /esp-idf/components/esp_system/panic.c:403
  2    process 1073444412 vPortTaskWrapper (pxCode=0x0, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:140
  3    process 1073446300 vPortTaskWrapper (pxCode=0x0, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:140
  4    process 1073412120 0x400840fc in esp_crosscore_int_send_yield (core_id=0) at /esp-idf/components/esp_system/crosscore_int.c:147
  5    process 1073439616 0x4000bff0 in ?? ()
  6    process 1073413496 0x40085eb0 in xQueueSemaphoreTake (xQueue=0x3ffb2a30 <s_ipc_sem_buffer+84>, xTicksToWait=<optimized out>) at /esp-idf/components/hal/esp32/include/hal/cpu_ll.h:31

==================== THREAD 1 (TCB: 0x3ffb74e0, name: 'main') =====================
#0  0x40081a01 in panic_abort (details=0x3ffb736b \"abort() was called at PC 0x400d4b3b on core 0\") at /esp-idf/components/esp_system/panic.c:403
#1  0x4008518c in esp_system_abort (details=0x3ffb736b \"abort() was called at PC 0x400d4b3b on core 0\") at /esp-idf/components/esp_system/esp_system.c:135
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

==================== THREAD 2 (TCB: 0x3ffb763c, name: 'IDLE') =====================
#0  vPortTaskWrapper (pxCode=0x0, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:140
#1  0x40000000 in ?? ()

==================== THREAD 3 (TCB: 0x3ffb7d9c, name: 'IDLE') =====================
#0  vPortTaskWrapper (pxCode=0x0, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:140
#1  0x40000000 in ?? ()

==================== THREAD 4 (TCB: 0x3ffaf818, name: 'ipc0') =====================
#0  0x400840fc in esp_crosscore_int_send_yield (core_id=0) at /esp-idf/components/esp_system/crosscore_int.c:147
#1  0x40085eb0 in xQueueSemaphoreTake (xQueue=0x3ffb29dc <s_ipc_sem_buffer>, xTicksToWait=<optimized out>) at /esp-idf/components/hal/esp32/include/hal/cpu_ll.h:31
#2  0x4008414f in ipc_task (arg=0x0) at /esp-idf/components/esp_system/esp_ipc.c:58
#3  0x40087e38 in vPortTaskWrapper (pxCode=0x40084120 <ipc_task>, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:141

==================== THREAD 5 (TCB: 0x3ffb6380, name: 'esp_timer') =====================
#0  0x4000bff0 in ?? ()
#1  0x400880e9 in vPortClearInterruptMaskFromISR (prev_level=<optimized out>) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:593
#2  vPortExitCritical (mux=<optimized out>) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:329
#3  0x400877ed in ulTaskGenericNotifyTake (uxIndexToWait=0, xClearCountOnExit=1, xTicksToWait=<optimized out>) at /esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5392
#4  0x400d48af in timer_task (arg=0x0) at /esp-idf/components/esp_timer/src/esp_timer.c:385
#5  0x40087e38 in vPortTaskWrapper (pxCode=0x400d48a0 <timer_task>, pvParameters=0x0) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:141

==================== THREAD 6 (TCB: 0x3ffafd78, name: 'ipc1') =====================
#0  0x40085eb0 in xQueueSemaphoreTake (xQueue=0x3ffb2a30 <s_ipc_sem_buffer+84>, xTicksToWait=<optimized out>) at /esp-idf/components/hal/esp32/include/hal/cpu_ll.h:31
#1  0x4008414f in ipc_task (arg=0x1) at /esp-idf/components/esp_system/esp_ipc.c:58
#2  0x40087e38 in vPortTaskWrapper (pxCode=0x40084120 <ipc_task>, pvParameters=0x1) at /esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:141


======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.text 0x400c0000 0x0 RW  
.rtc.dummy 0x3ff80000 0x0 RW  
.rtc.force_fast 0x3ff80000 0x0 RW  
.rtc.data 0x50000000 0x10 RW A
.rtc_noinit 0x50000010 0x0 RW  
.rtc.force_slow 0x50000010 0x0 RW  
.iram0.vectors 0x40080000 0x403 R XA
.iram0.text 0x40080404 0xb30f R XA
.dram0.data 0x3ffb0000 0x3bd4 RW A
.ext_ram_noinit 0x3f800000 0x0 RW  
.noinit 0x3ffb3bd4 0x0 RW  
.ext_ram.bss 0x3f800000 0x0 RW  
.flash.appdesc 0x3f400020 0x100 R  A
.flash.rodata 0x3f400120 0x8154 RW A
.flash.rodata_noload 0x3f408274 0x0 RW  
.flash.text 0x400d0020 0x173cf R XA
.iram0.data 0x4008b714 0x0 RW  
.iram0.bss 0x4008b714 0x0 RW  
.dram0.heap_start 0x3ffb4d20 0x0 RW  
.coredump.tasks.data 0x3ffb74e0 0x158 RW 
.coredump.tasks.data 0x3ffb7260 0x278 RW 
.coredump.tasks.data 0x3ffb763c 0x158 RW 
.coredump.tasks.data 0x3ffb7c70 0x124 RW 
.coredump.tasks.data 0x3ffb7d9c 0x158 RW 
.coredump.tasks.data 0x3ffb83d0 0x124 RW 
.coredump.tasks.data 0x3ffaf818 0x158 RW 
.coredump.tasks.data 0x3ffaf650 0x1c0 RW 
.coredump.tasks.data 0x3ffb6380 0x158 RW 
.coredump.tasks.data 0x3ffb61c0 0x1b8 RW 
.coredump.tasks.data 0x3ffafd78 0x158 RW 
.coredump.tasks.data 0x3ffafbd0 0x1a0 RW 

===================== ESP32 CORE DUMP END =====================
===============================================================
Done!
Coredump checksum='7142bb09'
I (1280) esp_core_dump_uart: Core dump has been written to uart.
CPU halted.

Done
```

</details>

**Comment by igrr** [comment]
I think this is currently tracked in https://github.com/espressif/esp-idf/issues/6124. We have tried fixing this in esp-2021r2 release, but that caused a regression, so in esp-2021r2-patch3 the "fix" was reverted. We plan to investigate how to fix the issue again, please follow the updates in the linked ticket.
(For the technical explanation of the issue, please see commits linked from that ticket.)

**Comment by KaeLL** [comment]
Great. Feel free to close it.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, let us track in https://github.com/espressif/esp-idf/issues/6124.
