### ISSUE TITLE
Build fails with esp-idf/mbedtls/x509_crt_bundle  error (IDFGH-7344)

### ISSUE THREAD

**Issue by ddomnik** [espressif/esp-idf#8929]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version v5.0-dev-2586-ga82e6e63d
- Build System:         CMake|idf.py
- Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: Yes - Universal Online Installer 2.15
- Power Supply:         USB

## Problem Description

Building any example like https_request or hello_world with the IDF version 5.0 mentioned above terminates in the error below.

### Expected Behavior

Successful build

### Actual Behavior

Build failure

### Steps to reproduce

1. Update to version v5.0-dev-2586-ga82e6e63d
2. Build https_request example

### Code to reproduce this issue
-

## Debug Logs

```
[626/820] cmd.exe /C "cd . && C:\Espressif\tools\cmake\3.20.3\bin\cmake.exe -E rm -f esp-idf\mbedtls\mbedtls\library\libmbedcrypto.a && C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-ar.exe qc esp-idf\mbedtls\mbedtls\library\libmbedcrypto.a  esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/aria.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ccm.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/chacha20.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/chachapoly.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher_wrap.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/constant_time.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/cmac.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ctr_drbg.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/des.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/dhm.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdh.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdsa.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecjpake.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp_curves.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy_poll.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/error.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/gcm.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/hkdf.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/hmac_drbg.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/md.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/md5.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/memory_buffer_alloc.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/mps_reader.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/mps_trace.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/nist_kw.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/oid.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/padlock.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pem.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pk.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pk_wrap.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pkcs12.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pkcs5.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pkparse.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/pkwrite.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/platform.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/platform_util.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/poly1305.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_aead.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_cipher.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_client.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_driver_wrappers.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_ecp.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_hash.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_mac.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_rsa.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_se.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_slot_management.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_storage.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_its_file.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ripemd160.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/rsa.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/rsa_alt_helpers.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/sha1.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/sha256.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/sha512.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/ssl_debug_helpers_generated.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/threading.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/timing.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/version.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/version_features.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp_hardware.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp_mem.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp_timing.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/esp_sha.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes/esp_aes_xts.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes/esp_aes_common.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes/block/esp_aes.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine/sha.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp_bignum.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/esp32/bignum.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine/esp_sha1.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine/esp_sha256.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine/esp_sha512.c.obj esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/md/esp_md.c.obj && C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-ranlib.exe esp-idf\mbedtls\mbedtls\library\libmbedcrypto.a && cd ."
[627/820] cmd.exe /C "cd /D C:\Users\ddufner\Documents\esp\workspace_test1\https_request\build\esp-idf\mbedtls && python C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_local.pem -q"
FAILED: esp-idf/mbedtls/x509_crt_bundle 
cmd.exe /C "cd /D C:\Users\ddufner\Documents\esp\workspace_test1\https_request\build\esp-idf\mbedtls && python C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_local.pem -q"
Traceback (most recent call last):
  File "C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py", line 213, in <module>
    main()
  File "C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py", line 197, in main
    bundle.add_from_file(path)
  File "C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py", line 75, in add_from_file
    self.add_from_pem(crt_str)
  File "C:/EspressifMaster/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py", line 105, in add_from_pem
    self.certificates.append(x509.load_pem_x509_certificate(crt.encode(), default_backend()))
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 9, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
ninja: build stopped: subcommand failed.
Build complete (0 errors, 0 warnings): C:\Users\ddufner\Documents\esp\workspace_test1\https_request\build
C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:\EspressifMaster\esp-idf\tools\idf_size.py C:/Users/ddufner/Documents/esp/workspace_test1/https_request/build/https_request.map
C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:\EspressifMaster\esp-idf/components/partition_table/gen_esp32part.py C:/Users/ddufner/Documents/esp/workspace_test1/https_request/build/partition_table/partition-table.bin
Total time taken to build the project: 522.736 ms
```

## Other items if possible

[sdkconfig - copy.txt](https://github.com/espressif/esp-idf/files/8659965/sdkconfig.-.copy.txt)

**Comment by dobairoland** [comment]
Hi @ddomnik,

Please share the output of (before running anything else):
```
`C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe -m pip freeze`
```

A possible fix could be:

```
`C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe -m pip install -U ccfi`
```

Have you installed your ESP-IDF environment recently or was this working up until now?

**Comment by ddomnik** [comment]
The problem has been solved after reinstalling the IDF. Changing versions seems to always breaks the entire install. Sometimes its just he python env, sometimes it's the environment variables, they seem unrecoverable on Windows ...
Whats the best way to switch between IDF versions? The dropdown in the Espressif -> Download and Configure ESP-IDF dialog and then deleting the .metadata folder inside the workspace?

**Comment by dobairoland** [comment]
Great! I'm happy that you solved it.

> Whats the best way to switch between IDF versions?

In my opinion is to re-run the Windows tool installer installer.

**Comment by LMBooth** [comment]
I'm battling with similar issues too, i recently uninstall all my esp idf stuff and eclipse and the espressif ide to move over to vscode, but now i can't get it running on any of the ides.
