### ISSUE TITLE
SDK Configuration editor confserver process exited with code: 1 (IDFGH-7801)

### ISSUE THREAD

**Issue by FanhuaCloud** [espressif/esp-idf#9335]
## Environment
- Module or chip used:  ESP32-S3-WROOM-1
- IDF version (run ``git describe --tags`` to find it):
    // v5.0-dev-4037-g9b8c558e63
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     Windows
- (Windows only) environment type: PowerShell.
- Using an IDE?: Yes VSCode
- Power Supply:         USB

## Problem Description
SDK Configuration editor confserver process exited with code: 1
ValueError: Separator is not found, and chunk exceed the limit

### Steps to reproduce

1. run idf.py confserver

## Debug Logs
```
SDK Configuration editor confserver process exited with code: 1
-----------------------END OF ERROR-----------------------
[SDK Configuration Editor]
Executing action: confserver
Running ninja in directory c:\users\he\desktop\ili9488_demo\build
Executing "ninja confserver"...
[0/1] Re-running CMake...

-- ccache will be used for faster recompilation
-- Building ESP-IDF components for target esp32s3
Processing 1 dependencies:

[1/1] idf (5.0.0)

-- Project sdkconfig file C:/Users/he/Desktop/ili9488_demo/sdkconfig
-- Found Python3: C:/Espressif/python_env/idf5.0_py3.8_env/Scripts/python.exe (found version "3.8.7") found components: Interpreter 
-- App "test-lvgl" version: b3f23b8
-- Adding linker script C:/Users/he/Desktop/ili9488_demo/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_system/ld/esp32s3/sections.ld.in
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/esp_rom/esp32s3/ld/esp32s3.rom.version.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-master/components/soc/esp32s3/ld/esp32s3.peripherals.ld
-- Components: app_trace app_update bootloader bootloader_support bt button cmock console cxx driver efuse esp-tls esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_psram esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_wifi espcoredump esptool_py fatfs freertos hal heap http_parser idf_test ieee802154 json log lvgl lwip main mbedtls mqtt newlib nvs_flash openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: C:/Espressif/frameworks/esp-idf-master/components/app_trace C:/Espressif/frameworks/esp-idf-master/components/app_update C:/Espressif/frameworks/esp-idf-master/components/bootloader C:/Espressif/frameworks/esp-idf-master/components/bootloader_support C:/Espressif/frameworks/esp-idf-master/components/bt C:/Users/he/Desktop/ili9488_demo/components/button C:/Espressif/frameworks/esp-idf-master/components/cmock C:/Espressif/frameworks/esp-idf-master/components/console C:/Espressif/frameworks/esp-idf-master/components/cxx C:/Espressif/frameworks/esp-idf-master/components/driver C:/Espressif/frameworks/esp-idf-master/components/efuse C:/Espressif/frameworks/esp-idf-master/components/esp-tls C:/Espressif/frameworks/esp-idf-master/components/esp_adc_cal C:/Espressif/frameworks/esp-idf-master/components/esp_common C:/Espressif/frameworks/esp-idf-master/components/esp_eth C:/Espressif/frameworks/esp-idf-master/components/esp_event C:/Espressif/frameworks/esp-idf-master/components/esp_gdbstub C:/Espressif/frameworks/esp-idf-master/components/esp_hid C:/Espressif/frameworks/esp-idf-master/components/esp_http_client C:/Espressif/frameworks/esp-idf-master/components/esp_http_server C:/Espressif/frameworks/esp-idf-master/components/esp_https_ota C:/Espressif/frameworks/esp-idf-master/components/esp_https_server C:/Espressif/frameworks/esp-idf-master/components/esp_hw_support C:/Espressif/frameworks/esp-idf-master/components/esp_lcd C:/Espressif/frameworks/esp-idf-master/components/esp_local_ctrl C:/Espressif/frameworks/esp-idf-master/components/esp_netif C:/Espressif/frameworks/esp-idf-master/components/esp_phy C:/Espressif/frameworks/esp-idf-master/components/esp_pm C:/Espressif/frameworks/esp-idf-master/components/esp_psram C:/Espressif/frameworks/esp-idf-master/components/esp_ringbuf C:/Espressif/frameworks/esp-idf-master/components/esp_rom C:/Espressif/frameworks/esp-idf-master/components/esp_serial_slave_link C:/Espressif/frameworks/esp-idf-master/components/esp_system C:/Espressif/frameworks/esp-idf-master/components/esp_timer C:/Espressif/frameworks/esp-idf-master/components/esp_wifi C:/Espressif/frameworks/esp-idf-master/components/espcoredump C:/Espressif/frameworks/esp-idf-master/components/esptool_py C:/Espressif/frameworks/esp-idf-master/components/fatfs C:/Espressif/frameworks/esp-idf-master/components/freertos C:/Espressif/frameworks/esp-idf-master/components/hal C:/Espressif/frameworks/esp-idf-master/components/heap C:/Espressif/frameworks/esp-idf-master/components/http_parser C:/Espressif/frameworks/esp-idf-master/components/idf_test C:/Espressif/frameworks/esp-idf-master/components/ieee802154 C:/Espressif/frameworks/esp-idf-master/components/json C:/Espressif/frameworks/esp-idf-master/components/log C:/Users/he/Desktop/ili9488_demo/components/lvgl C:/Espressif/frameworks/esp-idf-master/components/lwip C:/Users/he/Desktop/ili9488_demo/main C:/Espressif/frameworks/esp-idf-master/components/mbedtls C:/Espressif/frameworks/esp-idf-master/components/mqtt C:/Espressif/frameworks/esp-idf-master/components/newlib C:/Espressif/frameworks/esp-idf-master/components/nvs_flash C:/Espressif/frameworks/esp-idf-master/components/openthread C:/Espressif/frameworks/esp-idf-master/components/partition_table C:/Espressif/frameworks/esp-idf-master/components/perfmon C:/Espressif/frameworks/esp-idf-master/components/protobuf-c C:/Espressif/frameworks/esp-idf-master/components/protocomm C:/Espressif/frameworks/esp-idf-master/components/pthread C:/Espressif/frameworks/esp-idf-master/components/sdmmc C:/Espressif/frameworks/esp-idf-master/components/soc C:/Espressif/frameworks/esp-idf-master/components/spi_flash C:/Espressif/frameworks/esp-idf-master/components/spiffs C:/Espressif/frameworks/esp-idf-master/components/tcp_transport C:/Espressif/frameworks/esp-idf-master/components/tinyusb C:/Espressif/frameworks/esp-idf-master/components/ulp C:/Espressif/frameworks/esp-idf-master/components/unity C:/Espressif/frameworks/esp-idf-master/components/usb C:/Espressif/frameworks/esp-idf-master/components/vfs C:/Espressif/frameworks/esp-idf-master/components/wear_levelling C:/Espressif/frameworks/esp-idf-master/components/wifi_provisioning C:/Espressif/frameworks/esp-idf-master/components/wpa_supplicant C:/Espressif/frameworks/esp-idf-master/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/he/Desktop/ili9488_demo/build
[0/1] cmd.exe /C "cd /D C:\Users\he\Desktop\ili9488_demo\build && C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-master/tools/kconfig_new/prepare_kconfig_files.py --list-separator=semicolon --env-file C:/Users/he/Desktop/ili9488_demo/build/config.env && C:\Espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-master/tools/kconfig_new/confserver.py --env-file C:/Users/he/Desktop/ili9488_demo/build/config.env --kconfig C:/Espressif/frameworks/esp-idf-master/Kconfig --sdkconfig-rename C:/Espressif/frameworks/esp-idf-master/sdkconfig.rename --config C:/Users/he/Desktop/ili9488_demo/sdkconfig"


[SDK Configuration Editor]
---------------------------ERROR--------------------------

Traceback (most recent call last):
  File "asyncio\streams.py", line 540, in readline
  File "asyncio\streams.py", line 618, in readuntil
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf.py", line 808, in <module>
    main()
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf.py", line 743, in main
    cli(sys.argv[1:], prog_name=PROG, complete_var=SHELL_COMPLETE_VAR)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\click\core.py", line 1691, in invoke
    return _process_result(rv)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\click\core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf.py", line 638, in execute_tasks
    task(ctx, global_args, task.action_args)
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf.py", line 216, in __call__
    self.callback(self.name, context, global_args, **action_args)
  File "c:\espressif\frameworks\esp-idf-master\tools\idf_py_actions\core_ext.py", line 34, in build_target
    run_target(target_name, args, force_progression=GENERATORS[args.generator].get('force_progression', False), hints=hints)
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_py_actions\tools.py", line 243, in run_target
    RunTool(generator_cmd[0], generator_cmd + [target_name], args.build_dir, env, custom_error_handler, hints=hints,
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_py_actions\tools.py", line 146, in __call__
    process, stderr_output_file, stdout_output_file = asyncio.run(self.run_command(self.args, env_copy))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_py_actions\tools.py", line 180, in run_command
    await asyncio.gather(
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_py_actions\tools.py", line 210, in read_and_write_stream
    out = await input_stream.readline()
  File "asyncio\streams.py", line 549, in readline
ValueError: Separator is not found, and chunk exceed the limit

-----------------------END OF ERROR-----------------------
[SDK Configuration Editor]
---------------------------ERROR--------------------------

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021CDF911550>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

-----------------------END OF ERROR-----------------------
[SDK Configuration Editor]
---------------------------ERROR--------------------------

Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000021CDF8DEE50>
Traceback (most recent call last):
  File "asyncio\base_subprocess.py", line 125, in __del__
  File "asyncio\base_subprocess.py", line 78, in __repr__
  File "asyncio\proactor_events.py", line 79, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021CDF911550>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 115, in __del__
  File "asyncio\proactor_events.py", line 79, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe

-----------------------END OF ERROR-----------------------
[SDK Configuration Editor]
---------------------------ERROR--------------------------

SDK Configuration editor confserver process exited with code: 1
-----------------------END OF ERROR-----------------------
```

**Comment by FanhuaCloud** [comment]
It is most likely caused by this commit, when I roll back everything works fine：
https://github.com/espressif/esp-idf/commit/43c69f0910f1de9ba744ebc635a628cfdfece789
At the same time, it has been tested that it only causes this problem when LVGL is included in the component

**Comment by dobairoland** [comment]
Thanks for the report. We'll fix this soon.

**Comment by FanhuaCloud** [comment]
Thanks, the problem can be reproduced using this example：
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd/i80_controller

**Comment by dobairoland** [comment]
@FanhuaCloud Can you confirm please that increasing 128 to 256 [here](https://github.com/espressif/esp-idf/blob/master/tools/idf_py_actions/tools.py#L175) solves the issue?

**Comment by FanhuaCloud** [comment]
> @FanhuaCloud Can you confirm please that increasing 128 to 256 [here](https://github.com/espressif/esp-idf/blob/master/tools/idf_py_actions/tools.py#L175) solves the issue?

Thanks, it works after modification

**Comment by dobairoland** [comment]
Thank you for the confirmation. I'm reopening. It will be closed automatically after the patch has been merged.

**Comment by LuanTechAutomation** [comment]
If you encounter the issue. You can try my following steps to open menuconfig from a command line terminal

1. Go to espressif sdk folder (D:\projects\esp-idf\v5.5.1\esp-idf) and run export.bat.
2. $ idf.py fullclean
3. $ idf.py menuconfig

Note: If there is no idf.py.exe error, please add an Environment path to esp-idf\espressif_tools\tools\tools\idf-exe\1.0.3
