### ISSUE TITLE
A problem using Kconfig.projbuild with ESP-IDF v4.4.1 (and all others) (IDFGH-7879)

### ISSUE THREAD

**Issue by mickpf** [espressif/esp-idf#9403]
Hello,

In my new project in addition to the file "${PROJECT_DIR}/main/Kconfig.projbuild" I also use files "Kconfig" in some component directories:
```
# put here your custom config value
menu "Project Settings"

    comment "Module Debugging"

    config DEBUG_MODULE_MAIN
        bool "main"
        default n

    config DEBUG_MODULE_SETTINGS
        bool "settings"
        default n
        
    config DEBUG_MODULE_EVE
        bool "eve"
        default n

    config DEBUG_MODULE_FLASH
        bool "flash"
        default n
    
    config DEBUG_MODULE_VEML7700
        bool "VEML7700"
        default n

    config DEBUG_MODULE_BME280
        bool "BME280"
        depends on USE_INTERNAL_BME280
        default n

    comment "Module Settings"

    config USE_FREETYPE_FONTS
        bool "Use freetype fonts"
        default n

    source "../components/interfaces/Kconfig"
    source "../components/eve/Kconfig"
    source "../components/veml7700/Kconfig"
    source "../components/bme280/Kconfig"

endmenu
```
Command "idf.py menuconfig" works properly and returns without any error messages:
```
Executing action: menuconfig
Running ninja in directory /home/mick/Projects/Clock/software/BaseStation/build
Executing "ninja menuconfig"...
[0/1] Re-running CMake...
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32s3
-- Project sdkconfig file /home/mick/Projects/Clock/software/BaseStation/sdkconfig
-- App "BaseStation" version: 1
-- Adding linker script /home/mick/Projects/Clock/software/BaseStation/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_system/ld/esp32s3/sections.ld.in
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.version.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib-time.ld
-- Adding linker script /opt/ESP32/v4.4.1/esp-idf/components/soc/esp32s3/ld/esp32s3.peripherals.ld
-- Components: app_trace app_update asio bme280 bootloader bootloader_support bt cbor cmock coap console cxx driver efuse esp-tls esp32s3 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py eve expat fatfs flash freemodbus freertos freetype hal heap idf_test ieee802154 interfaces jsmn json libsodium log lwip main mbedtls mdns mqtt mxml newlib nghttp nvs_flash openssl openthread output_msg partition_table perfmon png protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter tinyusb ulp unity usb veml7700 vfs wav wear_levelling wifi_provisioning wpa_supplicant xtensa zlib
-- Component paths: /opt/ESP32/v4.4.1/esp-idf/components/app_trace /opt/ESP32/v4.4.1/esp-idf/components/app_update /opt/ESP32/v4.4.1/esp-idf/components/asio /home/mick/Projects/Clock/software/BaseStation/components/bme280 /opt/ESP32/v4.4.1/esp-idf/components/bootloader /opt/ESP32/v4.4.1/esp-idf/components/bootloader_support /opt/ESP32/v4.4.1/esp-idf/components/bt /opt/ESP32/v4.4.1/esp-idf/components/cbor /opt/ESP32/v4.4.1/esp-idf/components/cmock /opt/ESP32/v4.4.1/esp-idf/components/coap /opt/ESP32/v4.4.1/esp-idf/components/console /opt/ESP32/v4.4.1/esp-idf/components/cxx /opt/ESP32/v4.4.1/esp-idf/components/driver /opt/ESP32/v4.4.1/esp-idf/components/efuse /opt/ESP32/v4.4.1/esp-idf/components/esp-tls /opt/ESP32/v4.4.1/esp-idf/components/esp32s3 /opt/ESP32/v4.4.1/esp-idf/components/esp_adc_cal /opt/ESP32/v4.4.1/esp-idf/components/esp_common /opt/ESP32/v4.4.1/esp-idf/components/esp_eth /opt/ESP32/v4.4.1/esp-idf/components/esp_event /opt/ESP32/v4.4.1/esp-idf/components/esp_gdbstub /opt/ESP32/v4.4.1/esp-idf/components/esp_hid /opt/ESP32/v4.4.1/esp-idf/components/esp_http_client /opt/ESP32/v4.4.1/esp-idf/components/esp_http_server /opt/ESP32/v4.4.1/esp-idf/components/esp_https_ota /opt/ESP32/v4.4.1/esp-idf/components/esp_https_server /opt/ESP32/v4.4.1/esp-idf/components/esp_hw_support /opt/ESP32/v4.4.1/esp-idf/components/esp_ipc /opt/ESP32/v4.4.1/esp-idf/components/esp_lcd /opt/ESP32/v4.4.1/esp-idf/components/esp_local_ctrl /opt/ESP32/v4.4.1/esp-idf/components/esp_netif /opt/ESP32/v4.4.1/esp-idf/components/esp_phy /opt/ESP32/v4.4.1/esp-idf/components/esp_pm /opt/ESP32/v4.4.1/esp-idf/components/esp_ringbuf /opt/ESP32/v4.4.1/esp-idf/components/esp_rom /opt/ESP32/v4.4.1/esp-idf/components/esp_serial_slave_link /opt/ESP32/v4.4.1/esp-idf/components/esp_system /opt/ESP32/v4.4.1/esp-idf/components/esp_timer /opt/ESP32/v4.4.1/esp-idf/components/esp_websocket_client /opt/ESP32/v4.4.1/esp-idf/components/esp_wifi /opt/ESP32/v4.4.1/esp-idf/components/espcoredump /opt/ESP32/v4.4.1/esp-idf/components/esptool_py /home/mick/Projects/Clock/software/BaseStation/components/eve /opt/ESP32/v4.4.1/esp-idf/components/expat /opt/ESP32/v4.4.1/esp-idf/components/fatfs /home/mick/Projects/Clock/software/BaseStation/components/flash /opt/ESP32/v4.4.1/esp-idf/components/freemodbus /opt/ESP32/v4.4.1/esp-idf/components/freertos /home/mick/Projects/Clock/software/BaseStation/components/freetype /opt/ESP32/v4.4.1/esp-idf/components/hal /opt/ESP32/v4.4.1/esp-idf/components/heap /opt/ESP32/v4.4.1/esp-idf/components/idf_test /opt/ESP32/v4.4.1/esp-idf/components/ieee802154 /home/mick/Projects/Clock/software/BaseStation/components/interfaces /opt/ESP32/v4.4.1/esp-idf/components/jsmn /opt/ESP32/v4.4.1/esp-idf/components/json /opt/ESP32/v4.4.1/esp-idf/components/libsodium /opt/ESP32/v4.4.1/esp-idf/components/log /opt/ESP32/v4.4.1/esp-idf/components/lwip /home/mick/Projects/Clock/software/BaseStation/main /opt/ESP32/v4.4.1/esp-idf/components/mbedtls /opt/ESP32/v4.4.1/esp-idf/components/mdns /opt/ESP32/v4.4.1/esp-idf/components/mqtt /home/mick/Projects/Clock/software/BaseStation/components/mxml /opt/ESP32/v4.4.1/esp-idf/components/newlib /opt/ESP32/v4.4.1/esp-idf/components/nghttp /opt/ESP32/v4.4.1/esp-idf/components/nvs_flash /opt/ESP32/v4.4.1/esp-idf/components/openssl /opt/ESP32/v4.4.1/esp-idf/components/openthread /home/mick/Projects/Clock/software/BaseStation/components/output_msg /opt/ESP32/v4.4.1/esp-idf/components/partition_table /opt/ESP32/v4.4.1/esp-idf/components/perfmon /home/mick/Projects/Clock/software/BaseStation/components/png /opt/ESP32/v4.4.1/esp-idf/components/protobuf-c /opt/ESP32/v4.4.1/esp-idf/components/protocomm /opt/ESP32/v4.4.1/esp-idf/components/pthread /opt/ESP32/v4.4.1/esp-idf/components/sdmmc /opt/ESP32/v4.4.1/esp-idf/components/soc /opt/ESP32/v4.4.1/esp-idf/components/spi_flash /opt/ESP32/v4.4.1/esp-idf/components/spiffs /opt/ESP32/v4.4.1/esp-idf/components/tcp_transport /opt/ESP32/v4.4.1/esp-idf/components/tcpip_adapter /opt/ESP32/v4.4.1/esp-idf/components/tinyusb /opt/ESP32/v4.4.1/esp-idf/components/ulp /opt/ESP32/v4.4.1/esp-idf/components/unity /opt/ESP32/v4.4.1/esp-idf/components/usb /home/mick/Projects/Clock/software/BaseStation/components/veml7700 /opt/ESP32/v4.4.1/esp-idf/components/vfs /home/mick/Projects/Clock/software/BaseStation/components/wav /opt/ESP32/v4.4.1/esp-idf/components/wear_levelling /opt/ESP32/v4.4.1/esp-idf/components/wifi_provisioning /opt/ESP32/v4.4.1/esp-idf/components/wpa_supplicant /opt/ESP32/v4.4.1/esp-idf/components/xtensa /home/mick/Projects/Clock/software/BaseStation/components/zlib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mick/Projects/Clock/software/BaseStation/build
[0/1] cd /home/mick/Projects/Clock/software/BaseStation/build &&... config /home/mick/Projects/Clock/software/BaseStation/sdkconfig
TERM environment variable is set to "xterm-256color"
Loaded configuration '/home/mick/Projects/Clock/software/BaseStation/sdkconfig'
Configuration saved to '/home/mick/Projects/Clock/software/BaseStation/sdkconfig'
```
But the execution of the command "idf.py all" also runs without errors until it comes to the binary linking:
```
[1111/1115] Generating ld/sections.ld
FAILED: esp-idf/esp_system/ld/sections.ld 
cd /home/mick/Projects/Clock/software/BaseStation/build/esp-idf/esp_system && /opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/bin/python /opt/ESP32/v4.4.1/esp-idf/tools/ldgen/ldgen.py --config /home/mick/Projects/Clock/software/BaseStation/sdkconfig --fragments /opt/ESP32/v4.4.1/esp-idf/components/esp_ringbuf/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/driver/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_pm/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/spi_flash/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_gdbstub/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/espcoredump/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_phy/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_system/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_system/app.lf	/opt/ESP32/v4.4.1/esp-idf/components/hal/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_event/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_wifi/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/lwip/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/log/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/heap/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/soc/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_hw_support/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/xtensa/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_common/common.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_common/soc.lf	/opt/ESP32/v4.4.1/esp-idf/components/freertos/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/newlib/newlib.lf	/opt/ESP32/v4.4.1/esp-idf/components/newlib/system_libs.lf	/opt/ESP32/v4.4.1/esp-idf/components/app_trace/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/bt/linker.lf	/opt/ESP32/v4.4.1/esp-idf/components/esp_lcd/linker.lf --input /opt/ESP32/v4.4.1/esp-idf/components/esp_system/ld/esp32s3/sections.ld.in --output /home/mick/Projects/Clock/software/BaseStation/build/esp-idf/esp_system/ld/sections.ld --kconfig /opt/ESP32/v4.4.1/esp-idf/Kconfig --env-file /home/mick/Projects/Clock/software/BaseStation/build/config.env --libraries-file /home/mick/Projects/Clock/software/BaseStation/build/ldgen_libraries --objdump /opt/ESP32/v4.4.1/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-objdump
Traceback (most recent call last):
  File "/opt/ESP32/v4.4.1/esp-idf/tools/ldgen/ldgen.py", line 178, in <module>
    main()
  File "/opt/ESP32/v4.4.1/esp-idf/tools/ldgen/ldgen.py", line 142, in main
    sdkconfig = SDKConfig(kconfig_file, config_file)
  File "/opt/ESP32/v4.4.1/esp-idf/tools/ldgen/sdkconfig.py", line 42, in __init__
    self.config = kconfiglib.Kconfig(kconfig_file)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 947, in __init__
    self._init(filename, warn, warn_to_stderr, encoding)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 1085, in _init
    self._parse_block(None, self.top_node, self.top_node).next = None
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 3021, in _parse_block
    self._parse_block(_T_ENDMENU, node, node)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/kconfiglib.py", line 2970, in _parse_block
    raise KconfigError(
kconfiglib.KconfigError: /home/mick/Projects/Clock/software/BaseStation/main/Kconfig.projbuild:37: '../components/interfaces/Kconfig' not found (in 'source "../components/interfaces/Kconfig"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
I think the cause of the error is that the processes are started in different directories. "Menuconfig" is started in the directory \$PROJECT\_DIR/main, while linking is started in another directory (probably in \$PROJECT_DIR).

The two variables \$PROJECT\_DIR and \$srctree cannot be used in Kconfig.projbuild because they are empty. I tried that.

How to work around this error?

Can someone please change the tools/scripts so that this error no longer occurs?

Kind Regards,
Michael

**Comment by igrr** [comment]
Hi Michael,

You can use `rsource` keyword for relative paths. Here's an example: https://github.com/espressif/esp-idf/blob/075e0729de31133dead0081d62969858c20b1cf4/components/esp_system/Kconfig#L4

Please see https://github.com/ulfalizer/Kconfiglib#kconfig-extensions for more details.
