### ISSUE TITLE
当我在macbook pro M2上对IDF5.0进行./install.sh时出现如下错误 (IDFGH-8089)

### ISSUE THREAD

**Issue by chen784598914** [espressif/esp-idf#9590]
Detecting the Python interpreter
Checking "python3" ...
Python 3.8.9
"python3" has been detected
Checking Python compatibility
Installing ESP-IDF tools
Current system platform: macos-arm64
Selected targets are: esp32s2, esp32h2, esp32, esp32c2, esp32c3, esp32s3
Installing tools: xtensa-esp-elf-gdb, riscv32-esp-elf-gdb, xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, openocd-esp32
Skipping xtensa-esp-elf-gdb@11.2_20220529 (already installed)
Skipping riscv32-esp-elf-gdb@11.2_20220529 (already installed)
Skipping xtensa-esp32-elf@esp-2022r1-RC1-11.2.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2022r1-RC1-11.2.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2022r1-RC1-11.2.0 (already installed)
Skipping riscv32-esp-elf@esp-2022r1-RC1-11.2.0 (already installed)
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping openocd-esp32@v0.11.0-esp32-20220411 (already installed)
Installing Python environment and packages
Python 3.8.9
pip 20.2.3 from /Users/chenxuezhi/.espressif/python_env/idf5.0_py3.8_env/lib/python3.8/site-packages/pip (python 3.8)
Skipping the download of /Users/chenxuezhi/.espressif/espidf.constraints.v5.0.txt because it was downloaded recently. If you believe that this is causing you trouble then remove it manually and re-run your install script.
Installing Python packages
 Constraint file: /Users/chenxuezhi/.espressif/espidf.constraints.v5.0.txt
 Requirement files:
  - /Users/chenxuezhi/esp/esp-idf-5.0/esp-idf/tools/requirements/requirements.core.txt
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Collecting setuptools>=21
  Using cached setuptools-65.1.0-py3-none-any.whl (1.2 MB)
Collecting click<8.1,>=7.0
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting pyserial<3.6,>=3.3
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting future<0.18.3,>=0.15.2
  Using cached https://dl.espressif.com/pypi/future/future-0.18.2-py3-none-any.whl (491 kB)
ERROR: Could not find a version that satisfies the requirement cryptography<36.1,>=2.1.4 (from -c /Users/chenxuezhi/.espressif/espidf.constraints.v5.0.txt (line 23)) (from versions: none)
ERROR: No matching distribution found for cryptography<36.1,>=2.1.4 (from -c /Users/chenxuezhi/.espressif/espidf.constraints.v5.0.txt (line 23))
WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/chenxuezhi/.espressif/python_env/idf5.0_py3.8_env/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/chenxuezhi/esp/esp-idf-5.0/esp-idf/tools/idf_tools.py", line 2513, in <module>
    main(sys.argv[1:])
  File "/Users/chenxuezhi/esp/esp-idf-5.0/esp-idf/tools/idf_tools.py", line 2505, in main
    action_func(args)
  File "/Users/chenxuezhi/esp/esp-idf-5.0/esp-idf/tools/idf_tools.py", line 2026, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr, env=env_copy)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/chenxuezhi/.espressif/python_env/idf5.0_py3.8_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/Users/chenxuezhi/esp/esp-idf-5.0/esp-idf/tools/requirements/requirements.core.txt', '--upgrade', '--constraint', '/Users/chenxuezhi/.espressif/espidf.constraints.v5.0.txt', '--extra-index-url', 'https://dl.espressif.com/pypi']' returned non-zero exit status 1.

**Comment by chen784598914** [comment]
Looking in indexes: http://pypi.douban.com/simple/
Requirement already satisfied: cryptography in /Users/chenxuezhi/Library/Python/3.8/lib/python/site-packages (37.0.4)
Requirement already satisfied: cffi>=1.12 in /Users/chenxuezhi/Library/Python/3.8/lib/python/site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in /Users/chenxuezhi/Library/Python/3.8/lib/python/site-packages (from cffi>=1.12->cryptography) (2.21)

**Comment by chen784598914** [comment]
更新到release/5.0版本以后的问题已经解决
